package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class achievements extends MovieClip
	{
		public var configData:Object = null;

		public function achievements()
		{
			Security.allowDomain('*');

			configData = 

{"achievement-001001001":{ "achievementId" : "achievement-001001001", "bonus" : [], "description" : "玩家角色达到10级\n", "icon" : "image/icon/item/item074.png", "name" : "10级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "10", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001002":{ "achievementId" : "achievement-001001002", "bonus" : [], "description" : "玩家角色达到20级\n", "icon" : "image/icon/item/item074.png", "name" : "20级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "20", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001003":{ "achievementId" : "achievement-001001003", "bonus" : [], "description" : "玩家角色达到30级", "icon" : "image/icon/item/item074.png", "name" : "30级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "30", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001004":{ "achievementId" : "achievement-001001004", "bonus" : [], "description" : "玩家角色达到40级", "icon" : "image/icon/item/item074.png", "name" : "40级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "40", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001005":{ "achievementId" : "achievement-001001005", "bonus" : [], "description" : "玩家角色达到50级\n", "icon" : "image/icon/item/item074.png", "name" : "50级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "50", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001006":{ "achievementId" : "achievement-001001006", "bonus" : [], "description" : "玩家角色达到60级", "icon" : "image/icon/item/item074.png", "name" : "60级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "60", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001007":{ "achievementId" : "achievement-001001007", "bonus" : [], "description" : "玩家角色达到70级", "icon" : "image/icon/item/item074.png", "name" : "70级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "70", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001001008":{ "achievementId" : "achievement-001001008", "bonus" : [], "description" : "玩家角色达到80级", "icon" : "image/icon/item/item074.png", "name" : "80级", "objectives" : [ { "category" : "avatarLevel", "text" : "已完成:[curr]/[value]", "name" : "玩家等级", "key" : "", "value" : "80", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004001":{ "achievementId" : "achievement-001004001", "bonus" : [], "description" : "击杀100个怪物", "icon" : "image/icon/gear/beibu006.png", "name" : "野外求生", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "", "value" : "100", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004002":{ "achievementId" : "achievement-001004002", "bonus" : [], "description" : "击杀1000个怪物\n", "icon" : "image/icon/gear/beibu006.png", "name" : "怪物猎人", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "", "value" : "1000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004003":{ "achievementId" : "achievement-001004003", "bonus" : [], "description" : "击杀10000个怪物\n", "icon" : "image/icon/gear/beibu006.png", "name" : "鬼武者", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "", "value" : "10000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004004":{ "achievementId" : "achievement-001004004", "bonus" : [], "description" : "击杀100000个怪物\n", "icon" : "image/icon/gear/beibu006.png", "name" : "战神", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "", "value" : "100000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004005":{ "achievementId" : "achievement-001004005", "bonus" : [], "description" : "击杀1000000个怪物\n", "icon" : "image/icon/gear/beibu006.png", "name" : "生物危机", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "", "value" : "1000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004006":{ "achievementId" : "achievement-001004006", "bonus" : [], "description" : "前往王家内宅，击杀<a href='event:GameSpawnpoint-501101-302'><u><font color='#00FF00'>敖云蛟</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "宝刀屠龙", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0006007", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004007":{ "achievementId" : "achievement-001004007", "bonus" : [], "description" : "前往黑鲨堂，击杀<a href='event:GameSpawnpoint-500801-302'><u><font color='#00FF00'>黑鲨帮主</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "美味鱼翅", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0006016", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004008":{ "achievementId" : "achievement-001004008", "bonus" : [], "description" : "前往深海密穴，击杀<a href='event:GameSpawnpoint-502401-305'><u><font color='#00FF00'>蛟龙将军</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "蛟龙探海", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0006024", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004009":{ "achievementId" : "achievement-001004009", "bonus" : [], "description" : "前往山洞，击杀<a href='event:GameSpawnpoint-500901-302'><u><font color='#00FF00'>山魅</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "深山鬼哭", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0007017", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004010":{ "achievementId" : "achievement-001004010", "bonus" : [], "description" : "前往瑶池圣殿，击杀<a href='event:GameSpawnpoint-501201-302'><u><font color='#00FF00'>青鸾</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "青鸟传书", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0007026", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004011":{ "achievementId" : "achievement-001004011", "bonus" : [], "description" : "前往虎王洞，击杀<a href='event:GameSpawnpoint-501301-302'><u><font color='#00FF00'>雷霆虎王</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "百兽至尊", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0008007", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004012":{ "achievementId" : "achievement-001004012", "bonus" : [], "description" : "前往伏魔古阵，击杀<a href='event:GameSpawnpoint-502601-301'><u><font color='#00FF00'>千年树妖</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "千年树妖", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0008020", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004013":{ "achievementId" : "achievement-001004013", "bonus" : [], "description" : "前往山下石洞，击杀<a href='event:GameSpawnpoint-501401-301'><u><font color='#00FF00'>黄金力士</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "黄金力士", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0009007", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004014":{ "achievementId" : "achievement-001004014", "bonus" : [], "description" : "前往龙之墓副本，击杀<a href='event:GameNpc-000605-801'><u><font color='#00FF00'>鲨王之魂</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "鲨王之魂", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-7006002", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004015":{ "achievementId" : "achievement-001004015", "bonus" : [], "description" : "前往龙之墓副本，击杀<a href='event:GameNpc-000605-801'><u><font color='#00FF00'>青龙之灵</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "青龙之灵", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-7006005", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001004016":{ "achievementId" : "achievement-001004016", "bonus" : [], "description" : "前往后山塔林，击杀<a href='event:GameSpawnpoint-000803-307'><u><font color='#00FF00'>伏虎罗汉镜像</font></u></a>", "icon" : "image/icon/gear/beibu006.png", "name" : "降龙伏虎", "objectives" : [ { "category" : "monsterKill", "text" : "已完成:[curr]/[value]", "name" : "击杀怪物", "key" : "Mob-0008026", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001007001":{ "achievementId" : "achievement-001007001", "bonus" : [], "description" : "共计拾取100铜绑定钱币\n", "icon" : "image/icon/item/item146.png", "name" : "我在马路边，捡到...", "objectives" : [ { "category" : "moneyLoot", "text" : "已完成:[curr]/[value]铜币", "name" : "拾取钱币", "key" : "", "value" : "100", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001007002":{ "achievementId" : "achievement-001007002", "bonus" : [], "description" : "共计拾取10银绑定钱币\n", "icon" : "image/icon/item/item146.png", "name" : "勤俭持家", "objectives" : [ { "category" : "moneyLoot", "text" : "已完成:[curr]/[value]铜币", "name" : "拾取钱币", "key" : "", "value" : "1000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001007003":{ "achievementId" : "achievement-001007003", "bonus" : [], "description" : "共计拾取10金绑定钱币\n", "icon" : "image/icon/item/item146.png", "name" : "积少成多", "objectives" : [ { "category" : "moneyLoot", "text" : "已完成:[curr]/[value]铜币", "name" : "拾取钱币", "key" : "", "value" : "100000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-001007004":{ "achievementId" : "achievement-001007004", "bonus" : [], "description" : "共计拾取10000金绑定钱币\n", "icon" : "image/icon/item/item146.png", "name" : "捡出来的亿万富翁", "objectives" : [ { "category" : "moneyLoot", "text" : "已完成:[curr]/[value]铜币", "name" : "拾取钱币", "key" : "", "value" : "100000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001001":{ "achievementId" : "achievement-002001001", "bonus" : [], "description" : "完成5个任务", "icon" : "image/icon/item/item168.png", "name" : "很简单嘛！", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "5", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001002":{ "achievementId" : "achievement-002001002", "bonus" : [], "description" : "完成10个任务\n", "icon" : "image/icon/item/item168.png", "name" : "小菜一碟", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "10", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001003":{ "achievementId" : "achievement-002001003", "bonus" : [], "description" : "完成50个任务\n", "icon" : "image/icon/item/item168.png", "name" : "东奔西走", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "50", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001004":{ "achievementId" : "achievement-002001004", "bonus" : [], "description" : "完成100个任务\n", "icon" : "image/icon/item/item168.png", "name" : "乐此不疲", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "100", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001005":{ "achievementId" : "achievement-002001005", "bonus" : [], "description" : "完成500个任务\n", "icon" : "image/icon/item/item168.png", "name" : "千锤百炼", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "500", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001006":{ "achievementId" : "achievement-002001006", "bonus" : [], "description" : "完成1000个任务\n", "icon" : "image/icon/item/item168.png", "name" : "无所不知", "objectives" : [ { "category" : "questComplete", "text" : "已完成:[curr]/[value]", "name" : "完成任务", "key" : "", "value" : "1000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001007":{ "achievementId" : "achievement-002001007", "bonus" : [], "description" : "完成太虚幻境的所有任务", "icon" : "image/icon/item/item168.png", "name" : "梦开始的地方", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "天降大任", "key" : "quest-000016", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001008":{ "achievementId" : "achievement-002001008", "bonus" : [], "description" : "完成白云镇的所有任务\n", "icon" : "image/icon/item/item168.png", "name" : "无妄天雷", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "玉楼金阙", "key" : "quest-002069", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "加入家族", "key" : "quest-002105", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001009":{ "achievementId" : "achievement-002001009", "bonus" : [], "description" : "完成天都玉京的所有任务", "icon" : "image/icon/item/item168.png", "name" : "天上白玉京", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "九华求药", "key" : "quest-003065", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001010":{ "achievementId" : "achievement-002001010", "bonus" : [], "description" : "完成九华山的所有任务", "icon" : "image/icon/item/item168.png", "name" : "风动九华山", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "清灵宝鉴", "key" : "quest-004069", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001011":{ "achievementId" : "achievement-002001011", "bonus" : [], "description" : "完成闻香谷的所有任务\n", "icon" : "image/icon/item/item168.png", "name" : "闻香识谷", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "归返玉京", "key" : "quest-005063", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "净化花谷（二十）", "key" : "quest-005120", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "七色花语（九）", "key" : "quest-005129", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001012":{ "achievementId" : "achievement-002001012", "bonus" : [], "description" : "完成东海的所有任务\n", "icon" : "image/icon/item/item168.png", "name" : "纵横四海", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "远去昆仑", "key" : "quest-006075", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "百姓食粮", "key" : "quest-006101", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "海鲜全宴（六）", "key" : "quest-006107", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "父女情深（十五）", "key" : "quest-006122", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "章鱼童话（六）", "key" : "quest-006128", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001013":{ "achievementId" : "achievement-002001013", "bonus" : [], "description" : "完成缘起村的所有任务", "icon" : "image/icon/item/item168.png", "name" : "缘起村", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "千里之行", "key" : "quest-001075", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001014":{ "achievementId" : "achievement-002001014", "bonus" : [], "description" : "完成昆仑山的所有任务", "icon" : "image/icon/item/item168.png", "name" : "昆仑", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "灵山求助", "key" : "quest-007087", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "过冬屯粮", "key" : "quest-007101", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "先祖预言（五）", "key" : "quest-007106", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "风水宝局（七）", "key" : "quest-007113", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "暗恋风波（六）", "key" : "quest-007119", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "朝花夕拾（十四）", "key" : "quest-007133", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "无缝天衣（四）", "key" : "quest-007137", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "仙家药膳（四）", "key" : "quest-007141", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "鬼鬼祟祟", "key" : "quest-007142", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "瑶池问询", "key" : "quest-007143", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001015":{ "achievementId" : "achievement-002001015", "bonus" : [], "description" : "完成灵山的所有任务", "icon" : "image/icon/item/item168.png", "name" : "灵山", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "相谐与共", "key" : "quest-008065", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "收集物资（三）", "key" : "quest-008103", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "落花有意（十七）", "key" : "quest-008125", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "炙火流毒", "key" : "quest-008126", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "解毒树枝", "key" : "quest-008127", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "玄冥术士", "key" : "quest-008135", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "斋菜全宴（五）", "key" : "quest-008140", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001016":{ "achievementId" : "achievement-002001016", "bonus" : [], "description" : "完成太阿山的所有任务", "icon" : "image/icon/item/item168.png", "name" : "太阿山", "objectives" : [ { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "命运之地（二）", "key" : "quest-009068", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "天才少年（七）", "key" : "quest-009107", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "悲惨人间（七）", "key" : "quest-009114", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "绝世神刀（十一）", "key" : "quest-009125", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "女妖角笛", "key" : "quest-009126", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "神秘鬼灵（七）", "key" : "quest-009133", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "破坏阴谋", "key" : "quest-009139", "value" : "1", "serverLimit" : 0 }, { "category" : "specificQuestComplete", "text" : "已完成任务 [name]:[curr]/[value]", "name" : "祭祀之宴", "key" : "quest-009143", "value" : "1", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001018":{ "achievementId" : "achievement-002001018", "bonus" : [], "description" : "通过任务获得总共1000000铜币", "icon" : "image/icon/item/item146.png", "name" : "来点外快（一）", "objectives" : [ { "category" : "moneyQuest", "text" : "已完成:[curr]/[value]铜币", "name" : "任务获得钱币", "key" : "", "value" : "1000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001019":{ "achievementId" : "achievement-002001019", "bonus" : [], "description" : "通过任务获得总共10000000铜币\n", "icon" : "image/icon/item/item146.png", "name" : "来点外快（二）", "objectives" : [ { "category" : "moneyQuest", "text" : "已完成:[curr]/[value]铜币", "name" : "任务获得钱币", "key" : "", "value" : "10000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001020":{ "achievementId" : "achievement-002001020", "bonus" : [], "description" : "通过任务获得总共100000000铜币\n", "icon" : "image/icon/item/item146.png", "name" : "来点外快（三）", "objectives" : [ { "category" : "moneyQuest", "text" : "已完成:[curr]/[value]铜币", "name" : "任务获得钱币", "key" : "", "value" : "100000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-002001021":{ "achievementId" : "achievement-002001021", "bonus" : [], "description" : "通过任务获得总共1000000000铜币\n", "icon" : "image/icon/item/item146.png", "name" : "来点外快（四）", "objectives" : [ { "category" : "moneyQuest", "text" : "已完成:[curr]/[value]铜币", "name" : "任务获得钱币", "key" : "", "value" : "1000000000", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-005001006":{ "achievementId" : "achievement-005001006", "bonus" : [], "description" : "一个坐骑达到50级", "icon" : "image/icon/item/inv_item_misc_bell_001.png", "name" : "悉心照料", "objectives" : [ { "category" : "vehicleLevel", "text" : "已完成:[curr]/[value]", "name" : "坐骑等级", "key" : "", "value" : "50", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
,"achievement-005001007":{ "achievementId" : "achievement-005001007", "bonus" : [], "description" : "一个坐骑达到80级\n", "icon" : "image/icon/item/inv_item_misc_bell_001.png", "name" : "好马配英雄", "objectives" : [ { "category" : "vehicleLevel", "text" : "已完成:[curr]/[value]", "name" : "坐骑等级", "key" : "", "value" : "80", "serverLimit" : 0 } ], "pointReward" : 10, "titleReward" : "" }
};

		}
	}
}