package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class activity extends MovieClip
	{
		public var configData:Object = null;

		public function activity()
		{
			Security.allowDomain('*');

			configData = 

{"act-100001":{ "activityId" : "act-100001", "description" : "7月金仙开通/续费活动", "icon" : "image/icon64/item/jinxian.png", "logicType" : "BuyVipCard", "name" : "7月金仙优惠活动", "param1" : "jxyh", "param2" : "VipcardTemplate-1001", "param3" : "30400", "sFrom" : [ "all" ] }
,"act-100002":{ "activityId" : "act-100002", "description" : "这里是活动描述", "icon" : "", "logicType" : "Witness", "name" : "七夕大抢购", "param1" : "shelfTemplate-321", "param2" : "dict-400014", "param3" : "", "sFrom" : [ "all" ] }
,"act-100003":{ "activityId" : "act-100003", "contentList" : [ { "id" : "daily-001", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 1, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121307", "itemNum" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "任意送豪礼", "param1" : "anniversary_any", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100004":{ "activityId" : "act-100004", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "周年庆大抢购", "param1" : "shelfTemplate-322", "param2" : "dict-400018", "param3" : "", "sFrom" : [ "all" ] }
,"act-100005":{ "activityId" : "act-100005", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购4", "param1" : "GroupbuyTemplate-1000007", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100006":{ "activityId" : "act-100006", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购5", "param1" : "GroupbuyTemplate-1000008", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100007":{ "activityId" : "act-100007", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购6", "param1" : "GroupbuyTemplate-1000009", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100008":{ "activityId" : "act-100008", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购7", "param1" : "GroupbuyTemplate-1000010", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100009":{ "activityId" : "act-100009", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购4", "param1" : "GroupbuyTemplate-1100001", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100010":{ "activityId" : "act-100010", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购5", "param1" : "GroupbuyTemplate-1100002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100011":{ "activityId" : "act-100011", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购6", "param1" : "GroupbuyTemplate-1100003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100012":{ "activityId" : "act-100012", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第三期", "param1" : "400", "param2" : "dict-300006", "param3" : "image/ui/shangcheng/shenmishangren_2.png", "sFrom" : [ "all" ] }
,"act-100013":{ "activityId" : "act-100013", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122075", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122076", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122077", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122078", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122079", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122080", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122081", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122082", "itemNum" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "日消费返利", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100014":{ "activityId" : "act-100014", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100015":{ "activityId" : "act-100015", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第四期", "param1" : "400", "param2" : "dict-300008", "param3" : "image/ui/shangcheng/shenmishangren_2.png", "sFrom" : [ "all" ] }
,"act-100016":{ "activityId" : "act-100016", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "春节限购", "param1" : "shelfTemplate-332", "param2" : "dict-400066", "param3" : "", "sFrom" : [ "all" ] }
,"act-100017":{ "activityId" : "act-100017", "contentList" : [ { "id" : "ljxf-1001", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122161", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1002", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122162", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1003", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 30000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122163", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1004", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122164", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1005", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122165", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1006", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122166", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1007", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 500000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122167", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljxf-1008", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 1000000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122168", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "新年回馈", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100018":{ "activityId" : "act-100018", "contentList" : [], "description" : "", "icon" : "", "logicType" : "DailyLogin", "name" : "新春红包", "param1" : "dict-400067", "param2" : "2014-1-27", "param3" : "", "sFrom" : [ "all" ] }
,"act-100019":{ "activityId" : "act-100019", "contentList" : [ { "id" : "rljcz-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122211", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 200 } ] }, { "id" : "rljcz-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122212", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 500 } ] }, { "id" : "rljcz-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122213", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 1000 } ] }, { "id" : "rljcz-1004", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122214", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 2000 } ] }, { "id" : "rljcz-1005", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122215", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 5000 } ] }, { "id" : "rljcz-1006", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122216", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 10000 } ] }, { "id" : "rljcz-1007", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122217", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 20000 } ] }, { "id" : "rljcz-1008", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122218", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 30000 } ] } ], "description" : "每日充值得仙币", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送礼", "param1" : "anniversary_recharge", "param2" : "shelfTemplate-333", "param3" : "fairyCoin", "sFrom" : [ "all" ] }
,"act-100021":{ "activityId" : "act-100021", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "春节砸蛋活动", "param1" : "goldeneggDict-100003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100022":{ "activityId" : "act-100022", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122199", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122200", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122201", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122202", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122203", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122204", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122205", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122206", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "春节日消费返礼", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100023":{ "activityId" : "act-100023", "contentList" : [], "description" : "1、活动期间，玩家可点击藏宝图中的藏宝点进行挖宝，也可使用“一键挖宝”随机选取藏宝点逐个挖宝，直到元宝不足或挖完全图。\n2、玩家每天有1次免费挖宝机会，若用完免费次数则需使用元宝消费。\n3、玩家每次挖宝都可获得一件宝物，更有几率挖出大奖。\n4、若挖完整张地图则会获得全开奖励，并会刷新藏宝图，玩家可继续挖宝。\n5、蓝黄钻用户挖宝可享受八折优惠哟！", "icon" : "image/ui/main/wabao", "logicType" : "Dig", "name" : "寻珍觅宝", "param1" : "DigTemplate-1000002", "param2" : "1", "param3" : "image/ui/wabao/title.png", "sFrom" : [ "all" ] }
,"act-100024":{ "activityId" : "act-100024", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122219", "itemNum" : 1, "moneyType" : "", "value" : 1, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 25000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122220", "itemNum" : 1, "moneyType" : "", "value" : 1, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 65000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122221", "itemNum" : 1, "moneyType" : "", "value" : 1, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 125000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122222", "itemNum" : 1, "moneyType" : "", "value" : 1, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122223", "itemNum" : 1, "moneyType" : "", "value" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "消费返还徽章", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100025":{ "activityId" : "act-100025", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1004", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100026":{ "activityId" : "act-100026", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第五期", "param1" : "400", "param2" : "dict-300009", "param3" : "image/ui/shangcheng/shenmishangren_5.png", "sFrom" : [ "all" ] }
,"act-100027":{ "activityId" : "act-100027", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "元宵情人节限购", "param1" : "shelfTemplate-336", "param2" : "dict-400076", "param3" : "", "sFrom" : [ "all" ] }
,"act-100028":{ "activityId" : "act-100028", "contentList" : [], "description" : "1. 每次许愿都会获得1份许愿奖励，同时有概率获得超级大奖；\n2. 活动期间许愿次数达到指定数量，再次许愿必得对应超级大奖；\n3. 每日免费许愿1次，之后每次仅需500元宝，蓝黄钻更有8折优惠；\n4. 等级≥30级的玩家才能进行许愿哦！", "icon" : "", "logicType" : "Wishing", "name" : "元宵许愿活动", "param1" : "dict-400077", "param2" : "1", "param3" : "30", "sFrom" : [ "all" ] }
,"act-100029":{ "activityId" : "act-100029", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "2月砸蛋活动", "param1" : "goldeneggDict-100004", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100030":{ "activityId" : "act-100030", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第六期", "param1" : "400", "param2" : "dict-300011", "param3" : "image/ui/shangcheng/shenmishangren_5.png", "sFrom" : [ "all" ] }
,"act-100031":{ "activityId" : "act-100031", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1005", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100032":{ "activityId" : "act-100032", "contentList" : [ { "id" : "rljcz-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122289", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 200 } ] }, { "id" : "rljcz-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122290", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 500 } ] }, { "id" : "rljcz-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122291", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 1000 } ] }, { "id" : "rljcz-1004", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122292", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 2000 } ] }, { "id" : "rljcz-1005", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122293", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 5000 } ] }, { "id" : "rljcz-1006", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122294", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 10000 } ] }, { "id" : "rljcz-1007", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122295", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 20000 } ] }, { "id" : "rljcz-1008", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122296", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 30000 } ] } ], "description" : "每日充值得仙币", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送礼", "param1" : "anniversary_recharge", "param2" : "shelfTemplate-342", "param3" : "fairyCoin", "sFrom" : [ "all" ] }
,"act-100033":{ "activityId" : "act-100033", "contentList" : [], "description" : "跨服消费活动", "icon" : "", "logicType" : "ServerScore", "name" : "跨服消费排行", "param1" : "score-110044", "param2" : "20", "param3" : "2", "sFrom" : [ "all" ] }
,"act-100034":{ "activityId" : "act-100034", "contentList" : [], "description" : "1、活动期间，玩家可点击藏宝图中的藏宝点进行挖宝，也可使用“一键挖宝”随机选取藏宝点逐个挖宝，直到元宝不足或挖完全图。\n2、玩家每天有1次免费挖宝机会，若用完免费次数则需使用元宝消费。\n3、玩家每次挖宝都可获得一件宝物，更有几率挖出大奖。\n4、若挖完整张地图则会获得全开奖励，并会刷新藏宝图，玩家可继续挖宝。\n5、蓝黄钻用户挖宝可享受八折优惠哟！", "icon" : "image/ui/main/wabao", "logicType" : "Dig", "name" : "挖宝第三期", "param1" : "DigTemplate-1000003", "param2" : "1", "param3" : "image/ui/wabao/title.png", "sFrom" : [ "all" ] }
,"act-100035":{ "activityId" : "act-100035", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1006", "param2" : "", "param3" : "", "sFrom" : [ "3366" ] }
,"act-100036":{ "activityId" : "act-100036", "contentList" : [ { "id" : "ljcz-1001", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 1000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122514", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1002", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122515", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1003", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122516", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1004", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 30000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122517", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1005", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122518", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1006", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122519", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1007", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122520", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1008", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 500000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122521", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "ljcz-1009", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 800000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122522", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值返礼", "param1" : "anniversary_recharge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100037":{ "activityId" : "act-100037", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122527", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122528", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122529", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122530", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122531", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122532", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122533", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122534", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] } ], "description" : "每日消费返豪礼", "icon" : "", "logicType" : "GeneralAct", "name" : "日消费返礼", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100038":{ "activityId" : "act-100038", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第七期", "param1" : "400", "param2" : "dict-300012", "param3" : "image/ui/shangcheng/shenmishangren_5.png", "sFrom" : [ "all" ] }
,"act-100039":{ "activityId" : "act-100039", "contentList" : [], "description" : "1. 每次许愿都会获得1份许愿奖励。\n2. 活动期间许愿次数达到指定数量，再次许愿必额外得对应超级大奖\n3. 每日可免费许愿1次，之后每次仅需500元宝，蓝黄钻更有8折优惠", "icon" : "", "logicType" : "Wishing", "name" : "白色情人节许愿活动", "param1" : "dict-400081", "param2" : "1", "param3" : "30", "sFrom" : [ "all" ] }
,"act-100040":{ "activityId" : "act-100040", "contentList" : [ { "id" : "daily-1901", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51124", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "daily-1902", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51124", "itemNum" : 2, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "daily-1903", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51124", "itemNum" : 3, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "daily-1904", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 500000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51124", "itemNum" : 6, "isBound" : true, "moneyType" : "", "value" : 0 } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送浪漫徽章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100041":{ "activityId" : "act-100041", "contentList" : [ { "id" : "rljcz-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122562", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 200 } ] }, { "id" : "rljcz-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122563", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 500 } ] }, { "id" : "rljcz-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122564", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 1000 } ] }, { "id" : "rljcz-1004", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122565", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 2000 } ] }, { "id" : "rljcz-1005", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122566", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 5000 } ] }, { "id" : "rljcz-1006", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122567", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 10000 } ] }, { "id" : "rljcz-1007", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122568", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 20000 } ] }, { "id" : "rljcz-1008", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122569", "itemNum" : 1, "isBound" : true, "moneyType" : "fairyCoin", "value" : 30000 } ] } ], "description" : "每日充值得仙币", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送礼", "param1" : "anniversary_recharge", "param2" : "shelfTemplate-345", "param3" : "fairyCoin", "sFrom" : [ "all" ] }
,"act-100042":{ "activityId" : "act-100042", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "3月砸蛋活动", "param1" : "goldeneggDict-100005", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100043":{ "activityId" : "act-100043", "contentList" : [], "description" : "", "icon" : "", "logicType" : "OpenDiamondAct", "name" : "新服蓝钻开钻活动", "param1" : "xfkz-100001", "param2" : "", "param3" : "", "sFrom" : [ "qqgame", "3366" ] }
,"act-100045":{ "activityId" : "act-100045", "contentList" : [], "description" : "", "icon" : "", "logicType" : "OpenDiamondAct", "name" : "新服黄钻开钻活动", "param1" : "xfkz-100002", "param2" : "", "param3" : "", "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"act-100046":{ "activityId" : "act-100046", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1007", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100047":{ "activityId" : "act-100047", "contentList" : [], "description" : "", "icon" : "", "logicType" : "DailyLogin", "name" : "踏青日登陆礼包", "param1" : "dict-400084", "param2" : "2014-4-4", "param3" : "", "sFrom" : [ "all" ] }
,"act-100048":{ "activityId" : "act-100048", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "踏青砸蛋活动", "param1" : "goldeneggDict-100006", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100049":{ "activityId" : "act-100049", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "踏青限购", "param1" : "shelfTemplate-347", "param2" : "dict-400088", "param3" : "", "sFrom" : [ "all" ] }
,"act-10005":{ "activityId" : "act-10005", "contentList" : [ { "id" : "daily-001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51005", "itemNum" : 1, "isBound" : true } ] }, { "id" : "daily-002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51005", "itemNum" : 2, "isBound" : true } ] }, { "id" : "daily-004", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51005", "itemNum" : 3, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送勋章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100050":{ "activityId" : "act-100050", "contentList" : [], "description" : "1. 每次许愿都会获得1份许愿奖励。\n2. 活动期间许愿次数达到指定数量，再次许愿必获得对应超级大奖\n3. 每日可免费许愿1次，之后每次仅需500元宝，蓝黄钻更有8折优惠", "icon" : "", "logicType" : "Wishing", "name" : "踏青许愿活动", "param1" : "dict-400085", "param2" : "1", "param3" : "30", "sFrom" : [ "all" ] }
,"act-100051":{ "activityId" : "act-100051", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122630", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122631", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122632", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122633", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122634", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122635", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122636", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122637", "itemNum" : 1, "moneyType" : "", "value" : 0, "isBound" : true } ] } ], "description" : "每日消费返豪礼", "icon" : "", "logicType" : "GeneralAct", "name" : "踏青日消费返礼", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100052":{ "activityId" : "act-100052", "contentList" : [], "description" : "1.活动期间，玩家可花费元宝进行翻牌，并根据卡牌品质，几率获得对应道具奖励。更有一定几率获得本次活动的超级大奖！\n2.牌组分蓝色、紫色、橙色三种品质，品质越高所得道具越稀有。每种品质卡牌都有几率出现幸运卡，翻开幸运卡还有更大几率获取稀有道具奖励！\n3.玩家每轮翻牌时，需按品质从低到高依次翻开，只有较低品质卡牌翻完后，才能翻更高品质卡牌。\n4.若所有牌组都已翻完，则系统自动重新发牌。玩家也可自行选择重发卡牌，并从蓝色品质卡牌重新翻起。\n5.玩家每天有3次免费翻蓝卡的机会，可不要错过哟，蓝黄钻特权更有8折特价优惠。", "icon" : "image/ui/main/fanpai", "logicType" : "InvertCard", "name" : "翻牌活动", "param1" : "xyfp-100001", "param2" : "30", "param3" : "", "sFrom" : [ "all" ] }
,"act-100053":{ "activityId" : "act-100053", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122642", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122643", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122644", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122645", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122646", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122647", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122648", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-122649", "itemNum" : 1, "isBound" : true, "moneyType" : "", "value" : 0 } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "日消费返利", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-100054":{ "activityId" : "act-100054", "contentList" : [], "description" : "1、活动期间，玩家可点击藏宝图中的藏宝点进行挖宝，也可使用“一键挖宝”随机选取藏宝点逐个挖宝，直到元宝不足或挖完全图。\n2、玩家每天有1次免费挖宝机会，若用完免费次数则需使用元宝消费。\n3、玩家每次挖宝都可获得一件宝物，更有几率挖出大奖。\n4、若挖完整张地图则会获得全开奖励，并会刷新藏宝图，玩家可继续挖宝。\n5、蓝黄钻用户挖宝可享受八折优惠哟！", "icon" : "image/ui/main/wabao", "logicType" : "Dig", "name" : "挖宝第4期", "param1" : "DigTemplate-1000004", "param2" : "1", "param3" : "image/ui/wabao/title.png", "sFrom" : [ "all" ] }
,"act-100055":{ "activityId" : "act-100055", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1008", "param2" : "", "param3" : "", "sFrom" : [ "3366" ] }
,"act-10006":{ "activityId" : "act-10006", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "砸蛋活动", "param1" : "dict-400021", "param2" : "dict-400022", "param3" : "dict-400023", "sFrom" : [ "all" ] }
,"act-10007":{ "activityId" : "act-10007", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "中秋限购", "param1" : "shelfTemplate-323", "param2" : "dict-400026", "param3" : "", "sFrom" : [ "all" ] }
,"act-10008":{ "activityId" : "act-10008", "contentList" : [ { "id" : "daily-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51008", "itemNum" : 1, "isBound" : true } ] }, { "id" : "daily-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51008", "itemNum" : 2, "isBound" : true } ] }, { "id" : "daily-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51008", "itemNum" : 3, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送金秋徽章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10009":{ "activityId" : "act-10009", "contentList" : [], "description" : "", "icon" : "", "logicType" : "DailyLogin", "name" : "国庆日登陆", "param1" : "dict-400027", "param2" : "2013-09-30", "param3" : "", "sFrom" : [ "all" ] }
,"act-10010":{ "activityId" : "act-10010", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "国庆砸蛋活动", "param1" : "dict-400021", "param2" : "dict-400028", "param3" : "dict-400029", "sFrom" : [ "all" ] }
,"act-10011":{ "activityId" : "act-10011", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "国庆限购", "param1" : "shelfTemplate-324", "param2" : "dict-400030", "param3" : "", "sFrom" : [ "all" ] }
,"act-10012":{ "activityId" : "act-10012", "contentList" : [ { "id" : "daily-11001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51016", "itemNum" : 1, "isBound" : true } ] }, { "id" : "daily-11002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51016", "itemNum" : 2, "isBound" : true } ] }, { "id" : "daily-11003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51016", "itemNum" : 3, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送国庆徽章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10013":{ "activityId" : "act-10013", "contentList" : [], "description" : "", "icon" : "", "logicType" : "CycleSign", "name" : "连续签到礼包", "param1" : "3", "param2" : "dict-400033", "param3" : "http://qqgame.qq.com/act/a20130917gqly/index.html", "sFrom" : [ "qqgame" ] }
,"act-10014":{ "activityId" : "act-10014", "contentList" : [], "description" : "", "icon" : "", "logicType" : "DailyLogin", "name" : "国庆特别行囊", "param1" : "dict-400034", "param2" : "2013-10-1", "param3" : "", "sFrom" : [ "qqgame" ] }
,"act-10015":{ "activityId" : "act-10015", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "金秋砸蛋活动", "param1" : "dict-400021", "param2" : "dict-400035", "param3" : "dict-400036", "sFrom" : [ "all" ] }
,"act-10016":{ "activityId" : "act-10016", "contentList" : [], "description" : "", "icon" : "", "logicType" : "FinanceExchange", "name" : "万圣节元宝兑换", "param1" : "exchangeTemplate-001", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10017":{ "activityId" : "act-10017", "contentList" : [], "description" : "", "icon" : "", "logicType" : "FinanceExchange", "name" : "万圣节绑钱兑换", "param1" : "exchangeTemplate-002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10018":{ "activityId" : "act-10018", "contentList" : [ { "id" : "daily-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51023", "itemNum" : 1, "isBound" : true } ] }, { "id" : "daily-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51023", "itemNum" : 2, "isBound" : true } ] }, { "id" : "daily-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51023", "itemNum" : 3, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送光棍节徽章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10019":{ "activityId" : "act-10019", "contentList" : [], "description" : "", "icon" : "", "logicType" : "FinanceExchange", "name" : "光棍节元宝兑换", "param1" : "exchangeTemplate-003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10020":{ "activityId" : "act-10020", "contentList" : [], "description" : "", "icon" : "", "logicType" : "FinanceExchange", "name" : "光棍节绑钱兑换", "param1" : "exchangeTemplate-004", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10021":{ "activityId" : "act-10021", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "11月砸蛋活动", "param1" : "dict-400021", "param2" : "dict-400037", "param3" : "dict-400038", "sFrom" : [ "all" ] }
,"act-10022":{ "activityId" : "act-10022", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "感恩节砸蛋活动", "param1" : "dict-400021", "param2" : "dict-400040", "param3" : "dict-400041", "sFrom" : [ "all" ] }
,"act-10023":{ "activityId" : "act-10023", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "感恩节限购", "param1" : "shelfTemplate-327", "param2" : "dict-400042", "param3" : "", "sFrom" : [ "all" ] }
,"act-10024":{ "activityId" : "act-10024", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Fund", "name" : "11月月末基金", "param1" : "fundact-100003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10026":{ "activityId" : "act-10026", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "12月砸蛋活动", "param1" : "goldeneggDict-100001", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10027":{ "activityId" : "act-10027", "contentList" : [ { "id" : "daily-2001", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 1, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121817", "itemNum" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "12月任意送豪礼", "param1" : "anniversary_any", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10028":{ "activityId" : "act-10028", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购1", "param1" : "GroupbuyTemplate-1000001", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10029":{ "activityId" : "act-10029", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购2", "param1" : "GroupbuyTemplate-1000002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10030":{ "activityId" : "act-10030", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "土豪级团购3", "param1" : "GroupbuyTemplate-1000003", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10031":{ "activityId" : "act-10031", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购1", "param1" : "GroupbuyTemplate-1000004", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10032":{ "activityId" : "act-10032", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购2", "param1" : "GroupbuyTemplate-1000005", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10033":{ "activityId" : "act-10033", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Groupbuy", "name" : "实用级团购3", "param1" : "GroupbuyTemplate-1000006", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10034":{ "activityId" : "act-10034", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人", "param1" : "400", "param2" : "dict-300004", "param3" : "image/ui/shangcheng/shenmishangren_1.png", "sFrom" : [ "all" ] }
,"act-10035":{ "activityId" : "act-10035", "contentList" : [], "description" : "连开宝箱，惊喜连连！", "icon" : "image/ui/main/liankaibaoxiang", "logicType" : "ConsumeChain", "name" : "连开宝箱", "param1" : "gift-1002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-10036":{ "activityId" : "act-10036", "contentList" : [ { "id" : "ljxf-1001", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121926", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1002", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121927", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1003", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 30000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121928", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1004", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121929", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1005", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121930", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1006", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 300000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121931", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1007", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 500000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121932", "itemNum" : 1, "isBound" : true } ] }, { "id" : "ljxf-1008", "isDaily" : false, "type" : "consume", "param1" : "", "param2" : "", "value" : 1000000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121933", "itemNum" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "累积消费返利", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-1037":{ "activityId" : "act-1037", "contentList" : [ { "id" : "rljxf-1001", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 1000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121934", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1002", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 2000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121935", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1003", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 5000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121936", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1004", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 10000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121937", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1005", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121938", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1006", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121939", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1007", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121940", "itemNum" : 1, "isBound" : true } ] }, { "id" : "rljxf-1008", "isDaily" : true, "type" : "consume", "param1" : "", "param2" : "", "value" : 200000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-121941", "itemNum" : 1, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "日消费返礼", "param1" : "anniversary_consume", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-1038":{ "activityId" : "act-1038", "contentList" : [ { "id" : "daily-1001", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 20000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51046", "itemNum" : 1, "isBound" : true } ] }, { "id" : "daily-1002", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 50000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51046", "itemNum" : 2, "isBound" : true } ] }, { "id" : "daily-1003", "isDaily" : true, "type" : "recharge", "param1" : "", "param2" : "", "value" : 100000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51046", "itemNum" : 3, "isBound" : true } ] }, { "id" : "daily-1004", "isDaily" : false, "type" : "recharge", "param1" : "", "param2" : "", "value" : 500000, "maxTimes" : 1, "rewardList" : [ { "class" : "all", "itemId" : "itemTemplate-51046", "itemNum" : 6, "isBound" : true } ] } ], "description" : "", "icon" : "", "logicType" : "GeneralAct", "name" : "充值送元旦徽章", "param1" : "anniversary_badge", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-1039":{ "activityId" : "act-1039", "contentList" : [], "description" : "", "icon" : "", "logicType" : "DailyLogin", "name" : "元旦日登陆礼包", "param1" : "dict-400046", "param2" : "2013-12-30", "param3" : "", "sFrom" : [ "all" ] }
,"act-1040":{ "activityId" : "act-1040", "contentList" : [], "description" : "", "icon" : "", "logicType" : "Witness", "name" : "圣诞限购", "param1" : "shelfTemplate-329", "param2" : "dict-400047", "param3" : "", "sFrom" : [ "all" ] }
,"act-1041":{ "activityId" : "act-1041", "contentList" : [], "description" : "1、活动期间，玩家可点击藏宝图中的藏宝点进行挖宝，也可使用“一键挖宝”随机选取藏宝点逐个挖宝，直到元宝不足或挖完全图。\n2、玩家每天有1次免费挖宝机会，若用完免费次数则需使用元宝消费。\n3、玩家每次挖宝都可获得一件宝物，更有几率挖出大奖。\n4、若挖完整张地图则会获得全开奖励，并会刷新藏宝图，玩家可继续挖宝。\n5、蓝黄钻用户挖宝可享受八折优惠哟！", "icon" : "image/ui/main/wabao", "logicType" : "Dig", "name" : "寻珍觅宝", "param1" : "DigTemplate-1000001", "param2" : "1", "param3" : "image/ui/wabao/title.png", "sFrom" : [ "all" ] }
,"act-1042":{ "activityId" : "act-1042", "contentList" : [], "description" : "1. 每次许愿都会获得1份许愿奖励，同时有概率获得超级大奖\n2. 活动期间许愿次数达到指定数量，再次许愿必得对应超级大奖\n3. 每日可免费许愿1次，之后每次仅需500元宝，蓝黄钻更有8折优惠", "icon" : "", "logicType" : "Wishing", "name" : "许愿活动", "param1" : "dict-400048", "param2" : "1", "param3" : "30", "sFrom" : [ "all" ] }
,"act-1043":{ "activityId" : "act-1043", "contentList" : [], "description" : "1111", "icon" : "", "logicType" : "Mysterious", "name" : "神秘商人第二期", "param1" : "400", "param2" : "dict-300005", "param3" : "image/ui/shangcheng/shenmishangren_4.png", "sFrom" : [ "all" ] }
,"act-1044":{ "activityId" : "act-1044", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "GoldenEgg", "name" : "1月砸蛋活动", "param1" : "goldeneggDict-100002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-99999":{ "activityId" : "act-99999", "contentList" : [], "description" : "fsaf", "icon" : "", "logicType" : "Purchase", "name" : "周末限购", "param1" : "shelfTemplate-326", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-999991":{ "activityId" : "act-999991", "contentList" : [], "description" : "fsaf", "icon" : "", "logicType" : "RationGoods", "name" : "老服每日限购", "param1" : "rationact-100002", "param2" : "", "param3" : "", "sFrom" : [ "all" ] }
,"act-999992":{ "activityId" : "act-999992", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "ServerScore", "name" : "测试消费积分", "param1" : "score-999941", "param2" : "20", "param3" : "2", "sFrom" : [ "all" ] }
,"act-999993":{ "activityId" : "act-999993", "contentList" : [], "description" : "fsaf", "icon" : "/image/ui/zhongqiu/egg.png", "logicType" : "ServerScore", "name" : "测试充值积分", "param1" : "score-999942", "param2" : "20", "param3" : "2", "sFrom" : [ "all" ] }
};

		}
	}
}