package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class bodylineLevel extends MovieClip
	{
		public var configData:Object = null;

		public function bodylineLevel()
		{
			Security.allowDomain('*');

			configData = 

{"bodylineLevel-1":{ "baseFailTimes" : 0, "baseRate" : 0.3, "breakItem" : "itemTemplate-50187", "breakItemNum" : 2, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 50000, "deltaRate" : 0.08, "imgStateLevelBg" : "image/ui/jingmai/dazuo.png", "imgStateLevelLabel" : "image/ui/jingmai/yiceng.png", "imgStateLevelName" : "image/ui/jingmai/tong.png", "levelId" : "bodylineLevel-1", "luckyRate" : 0.001, "potentialMaxLevel" : 40, "rateModify" : 0.08, "reward" : 0, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 1 }
,"bodylineLevel-10":{ "baseFailTimes" : 4, "baseRate" : 1, "breakItem" : "itemTemplate-43014", "breakItemNum" : 1, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 0, "deltaRate" : 0.04, "imgStateLevelBg" : "image/ui/jingmai/dazuohong.png", "imgStateLevelLabel" : "image/ui/jingmai/dierceng.png", "imgStateLevelName" : "image/ui/jingmai/huntian.png", "levelId" : "bodylineLevel-10", "luckyRate" : 0, "potentialMaxLevel" : 80, "rateModify" : 0.25, "reward" : 22000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "qiannengjifadan", "stateLevel" : 2 }
,"bodylineLevel-11":{ "baseFailTimes" : 15, "baseRate" : 0.05, "breakItem" : "itemTemplate-50187", "breakItemNum" : 10, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 200000, "deltaRate" : 0.08, "imgStateLevelBg" : "image/ui/jingmai/dazuo3.png", "imgStateLevelLabel" : "image/ui/jingmai/sanceng.png", "imgStateLevelName" : "image/ui/jingmai/nitian.png", "levelId" : "bodylineLevel-11", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 22000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 3 }
,"bodylineLevel-12":{ "baseFailTimes" : 20, "baseRate" : 0.04, "breakItem" : "itemTemplate-50187", "breakItemNum" : 12, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 300000, "deltaRate" : 0.07000000000000001, "imgStateLevelBg" : "image/ui/jingmai/dazuo3.png", "imgStateLevelLabel" : "image/ui/jingmai/sanceng.png", "imgStateLevelName" : "image/ui/jingmai/nitian.png", "levelId" : "bodylineLevel-12", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 25000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 3 }
,"bodylineLevel-13":{ "baseFailTimes" : 25, "baseRate" : 0.03, "breakItem" : "itemTemplate-50187", "breakItemNum" : 14, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 400000, "deltaRate" : 0.06, "imgStateLevelBg" : "image/ui/jingmai/dazuo3.png", "imgStateLevelLabel" : "image/ui/jingmai/sanceng.png", "imgStateLevelName" : "image/ui/jingmai/nitian.png", "levelId" : "bodylineLevel-13", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 28000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 3 }
,"bodylineLevel-14":{ "baseFailTimes" : 30, "baseRate" : 0.02, "breakItem" : "itemTemplate-50187", "breakItemNum" : 16, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 500000, "deltaRate" : 0.05, "imgStateLevelBg" : "image/ui/jingmai/dazuo3.png", "imgStateLevelLabel" : "image/ui/jingmai/sanceng.png", "imgStateLevelName" : "image/ui/jingmai/nitian.png", "levelId" : "bodylineLevel-14", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 32000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 3 }
,"bodylineLevel-15":{ "baseFailTimes" : 0, "baseRate" : 0, "breakItem" : "itemTemplate-43014", "breakItemNum" : 0, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 0, "deltaRate" : 0.04, "imgStateLevelBg" : "image/ui/jingmai/dazuo3.png", "imgStateLevelLabel" : "image/ui/jingmai/sanceng.png", "imgStateLevelName" : "image/ui/jingmai/nitian.png", "levelId" : "bodylineLevel-15", "luckyRate" : 0, "potentialMaxLevel" : 80, "rateModify" : 0, "reward" : 36000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 3 }
,"bodylineLevel-2":{ "baseFailTimes" : 5, "baseRate" : 0.2, "breakItem" : "itemTemplate-50187", "breakItemNum" : 3, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 100000, "deltaRate" : 0.07000000000000001, "imgStateLevelBg" : "image/ui/jingmai/dazuo.png", "imgStateLevelLabel" : "image/ui/jingmai/yiceng.png", "imgStateLevelName" : "image/ui/jingmai/tong.png", "levelId" : "bodylineLevel-2", "luckyRate" : 0.001, "potentialMaxLevel" : 40, "rateModify" : 0.05, "reward" : 2000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 1 }
,"bodylineLevel-3":{ "baseFailTimes" : 10, "baseRate" : 0.1, "breakItem" : "itemTemplate-50187", "breakItemNum" : 4, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 250000, "deltaRate" : 0.06, "imgStateLevelBg" : "image/ui/jingmai/dazuo.png", "imgStateLevelLabel" : "image/ui/jingmai/yiceng.png", "imgStateLevelName" : "image/ui/jingmai/tong.png", "levelId" : "bodylineLevel-3", "luckyRate" : 0.001, "potentialMaxLevel" : 40, "rateModify" : 0.02, "reward" : 4000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 1 }
,"bodylineLevel-4":{ "baseFailTimes" : 15, "baseRate" : 0.05, "breakItem" : "itemTemplate-50187", "breakItemNum" : 5, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 500000, "deltaRate" : 0.05, "imgStateLevelBg" : "image/ui/jingmai/dazuo.png", "imgStateLevelLabel" : "image/ui/jingmai/yiceng.png", "imgStateLevelName" : "image/ui/jingmai/tong.png", "levelId" : "bodylineLevel-4", "luckyRate" : 0.001, "potentialMaxLevel" : 40, "rateModify" : 0.01, "reward" : 7000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 1 }
,"bodylineLevel-5":{ "baseFailTimes" : 1, "baseRate" : 1, "breakItem" : "itemTemplate-43014", "breakItemNum" : 1, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 0, "deltaRate" : 0.04, "imgStateLevelBg" : "image/ui/jingmai/dazuo.png", "imgStateLevelLabel" : "image/ui/jingmai/yiceng.png", "imgStateLevelName" : "image/ui/jingmai/tong.png", "levelId" : "bodylineLevel-5", "luckyRate" : 0, "potentialMaxLevel" : 40, "rateModify" : 1, "reward" : 10000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "qiannengjifadan", "stateLevel" : 1 }
,"bodylineLevel-6":{ "baseFailTimes" : 15, "baseRate" : 0.05, "breakItem" : "itemTemplate-50187", "breakItemNum" : 5, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 200000, "deltaRate" : 0.08, "imgStateLevelBg" : "image/ui/jingmai/dazuohong.png", "imgStateLevelLabel" : "image/ui/jingmai/dierceng.png", "imgStateLevelName" : "image/ui/jingmai/huntian.png", "levelId" : "bodylineLevel-6", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 10000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 2 }
,"bodylineLevel-7":{ "baseFailTimes" : 20, "baseRate" : 0.04, "breakItem" : "itemTemplate-50187", "breakItemNum" : 6, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 300000, "deltaRate" : 0.07000000000000001, "imgStateLevelBg" : "image/ui/jingmai/dazuohong.png", "imgStateLevelLabel" : "image/ui/jingmai/dierceng.png", "imgStateLevelName" : "image/ui/jingmai/huntian.png", "levelId" : "bodylineLevel-7", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 12500, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 2 }
,"bodylineLevel-8":{ "baseFailTimes" : 25, "baseRate" : 0.03, "breakItem" : "itemTemplate-50187", "breakItemNum" : 7, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 400000, "deltaRate" : 0.06, "imgStateLevelBg" : "image/ui/jingmai/dazuohong.png", "imgStateLevelLabel" : "image/ui/jingmai/dierceng.png", "imgStateLevelName" : "image/ui/jingmai/huntian.png", "levelId" : "bodylineLevel-8", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 15000, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 2 }
,"bodylineLevel-9":{ "baseFailTimes" : 30, "baseRate" : 0.02, "breakItem" : "itemTemplate-50187", "breakItemNum" : 8, "breakPointItem" : "itemTemplate-43015", "breakPointItemNumMax" : 5, "consumeMoney" : 500000, "deltaRate" : 0.05, "imgStateLevelBg" : "image/ui/jingmai/dazuohong.png", "imgStateLevelLabel" : "image/ui/jingmai/dierceng.png", "imgStateLevelName" : "image/ui/jingmai/huntian.png", "levelId" : "bodylineLevel-9", "luckyRate" : 0.001, "potentialMaxLevel" : 80, "rateModify" : 0.01, "reward" : 18500, "rewardProGrpList" : { "defaultClass" : { "proGrpId" : 1040 } }, "serviceType" : "humaidan", "stateLevel" : 2 }
};

		}
	}
}