package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class chapter extends MovieClip
	{
		public var configData:Object = null;

		public function chapter()
		{
			Security.allowDomain('*');

			configData = 

{"chapter-1":{ "chapterId" : "chapter-1", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao2.png", "goalList" : [ { "goalId" : "goal-101", "title" : "", "name" : "收获一次摇钱树", "key" : "0", "targetId" : null, "category" : "getMoneyTree", "moneyType" : "boundmoney", "moneyIcon" : "image/icon/item/bangqian.png", "description" : "0", "value" : 1, "money" : 10000, "exp" : 0, "bonus" : [] }, { "goalId" : "goal-102", "title" : "", "name" : "激活1个坐骑图鉴", "key" : "0", "targetId" : null, "category" : "vehiclePic", "moneyType" : "boundmoney", "moneyIcon" : "0", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-9079", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-103", "title" : "", "name" : "升至20级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 20, "money" : 100, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "732", "name" : "第一章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 3000 }, { "class" : "", "attr" : "mpMax", "value" : 1000 }, { "class" : "", "attr" : "baseDamage", "value" : 20 } ], "startLevel" : 10, "title" : "初心" }
,"chapter-2":{ "chapterId" : "chapter-2", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao1.png", "goalList" : [ { "goalId" : "goal-201", "title" : "", "name" : "家族上香", "key" : "0", "targetId" : null, "category" : "FamilyPray", "moneyType" : "", "moneyIcon" : "", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-8876", "count" : 2, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-202", "title" : "", "name" : "添加5个好友", "key" : "0", "targetId" : null, "category" : "friendAmount", "moneyType" : "boundmoney", "moneyIcon" : "image/icon/item/bangqian.png", "description" : "0", "value" : 5, "money" : 10000, "exp" : 0, "bonus" : [] }, { "goalId" : "goal-203", "title" : "", "name" : "升至30级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 30, "money" : 200, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "1038", "name" : "第二章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 4500 }, { "class" : "", "attr" : "mpMax", "value" : 1300 }, { "class" : "", "attr" : "baseDamage", "value" : 30 } ], "startLevel" : 20, "title" : "入世" }
,"chapter-3":{ "chapterId" : "chapter-3", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao2.png", "goalList" : [ { "goalId" : "goal-301", "title" : "", "name" : "第一次组队", "key" : "0", "targetId" : null, "category" : "hasEnterTeam", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-149", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-302", "title" : "", "name" : "击杀白骨洞BOSS-人尸白纤纤", "key" : "Mob-7001005", "targetId" : "GameNpc-000202-802", "category" : "monsterKill", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-6123", "count" : 20, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-303", "title" : "", "name" : "将任意装备强化到4星", "key" : "0", "targetId" : null, "category" : "equipmentStrong", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 4, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-170", "count" : 5, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-304", "title" : "", "name" : "升至40级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 40, "money" : 300, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "1410", "name" : "第三章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 6000 }, { "class" : "", "attr" : "mpMax", "value" : 1600 }, { "class" : "", "attr" : "baseDamage", "value" : 30 }, { "class" : "", "attr" : "criticalResist", "value" : 30 }, { "class" : "", "attr" : "criticalRating", "value" : 30 } ], "startLevel" : 30, "title" : "闻道" }
,"chapter-4":{ "chapterId" : "chapter-4", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao1.png", "goalList" : [ { "goalId" : "goal-401", "title" : "", "name" : "英雄塔层数达到10", "key" : "0", "targetId" : null, "category" : "HeroTowerLevel", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 10, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-13089", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-402", "title" : "", "name" : "冲开5个穴位", "key" : "0", "targetId" : null, "category" : "punchingHole", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 5, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43024", "count" : 15, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-403", "title" : "", "name" : "将任意仙纹铭刻至5级", "key" : "0", "targetId" : null, "category" : "immortalLinesAmount", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 5, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-50184", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-404", "title" : "", "name" : "升至50级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 50, "money" : 500, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "1815", "name" : "第四章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 7500 }, { "class" : "", "attr" : "mpMax", "value" : 1900 }, { "class" : "", "attr" : "baseDamage", "value" : 35 }, { "class" : "", "attr" : "criticalRating", "value" : 60 }, { "class" : "", "attr" : "criticalResist", "value" : 60 } ], "startLevel" : 40, "title" : "守中" }
,"chapter-5":{ "chapterId" : "chapter-5", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao2.png", "goalList" : [ { "goalId" : "goal-501", "title" : "", "name" : "将坐骑锻造至绿色", "key" : "0", "targetId" : null, "category" : "vehicleForging", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 3, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43144", "count" : 15, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-502", "title" : "", "name" : "法宝炼器至3阶", "key" : "0", "targetId" : null, "category" : "magicHeater", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 3, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43151", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-503", "title" : "", "name" : "战力达到28000", "key" : "0", "targetId" : null, "category" : "avatarWorth", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 28000, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43062", "count" : 1, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-504", "title" : "", "name" : "升至60级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 60, "money" : 1000, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "2220", "name" : "第五章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 9000 }, { "class" : "", "attr" : "mpMax", "value" : 2200 }, { "class" : "", "attr" : "baseDamage", "value" : 40 }, { "class" : "", "attr" : "criticalRating", "value" : 90 }, { "class" : "", "attr" : "criticalResist", "value" : 90 } ], "startLevel" : 50, "title" : "归元" }
,"chapter-6":{ "chapterId" : "chapter-6", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao2.png", "goalList" : [ { "goalId" : "goal-601", "title" : "", "name" : "参与1次困难闯关", "key" : "InstanceGroup-7900", "targetId" : "", "category" : "finishSpecialCopyTeam", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43120", "count" : 3, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-602", "title" : "", "name" : "真龙升至3级", "key" : "0", "targetId" : "", "category" : "dragonLevel", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 3, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43156", "count" : 5, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-603", "title" : "", "name" : "战力达到40000", "key" : "0", "targetId" : null, "category" : "avatarWorth", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 40000, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43062", "count" : 3, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-604", "title" : "", "name" : "升至70级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 70, "money" : 2000, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "2625", "name" : "第六章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 10500 }, { "class" : "", "attr" : "mpMax", "value" : 2500 }, { "class" : "", "attr" : "baseDamage", "value" : 45 }, { "class" : "", "attr" : "criticalRating", "value" : 120 }, { "class" : "", "attr" : "criticalResist", "value" : 120 } ], "startLevel" : 60, "title" : "问情" }
,"chapter-7":{ "chapterId" : "chapter-7", "entryIcon1" : "xintiao1.png", "entryIcon2" : "xintiao2.png", "goalList" : [ { "goalId" : "goal-701", "title" : "", "name" : "拥有1个橙色妖核", "key" : "0", "targetId" : null, "category" : "OrangeGoblinAmount", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 1, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43009", "count" : 3, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-702", "title" : "", "name" : "开启5个坐骑图鉴", "key" : "0", "targetId" : null, "category" : "vehiclePic", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 5, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43110", "count" : 5, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-703", "title" : "", "name" : "战力达到55000", "key" : "0", "targetId" : null, "category" : "avatarWorth", "moneyType" : "", "moneyIcon" : "0", "description" : "0", "value" : 55000, "money" : 0, "exp" : 0, "bonus" : [ { "itemId" : "itemTemplate-43062", "count" : 5, "optional" : 0, "bound" : 1, "class" : "", "overdue" : 0 } ] }, { "goalId" : "goal-704", "title" : "", "name" : "升至80级", "key" : "0", "targetId" : null, "category" : "avatarLevel", "moneyType" : "token", "moneyIcon" : "image/icon/giftpack/2.png", "description" : "0", "value" : 80, "money" : 5000, "exp" : 0, "bonus" : [] } ], "icon" : "xunzhang1.png", "medalName" : "", "medalNumber" : "", "medalWorth" : "3030", "name" : "第七章", "reward" : [ { "class" : "", "attr" : "hpMax", "value" : 12000 }, { "class" : "", "attr" : "mpMax", "value" : 2800 }, { "class" : "", "attr" : "baseDamage", "value" : 50 }, { "class" : "", "attr" : "criticalRating", "value" : 150 }, { "class" : "", "attr" : "criticalResist", "value" : 150 } ], "startLevel" : 70, "title" : "斩道" }
};

		}
	}
}