package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class exchangeRecipe extends MovieClip
	{
		public var configData:Object = null;

		public function exchangeRecipe()
		{
			Security.allowDomain('*');

			configData = 

{"peifang-10001":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 88, "moneyAmount" : 0, "moneyType" : "money", "name" : "鸣鸾仙光（激活卡）配方", "outputItemId" : "itemTemplate-51038", "recipeId" : "peifang-10001", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 30 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 30 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 30 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 30 } ] }
,"peifang-10002":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "周年庆徽章配方", "outputItemId" : "itemTemplate-51005", "recipeId" : "peifang-10002", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 100 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 100 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 100 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 100 } ] }
,"peifang-10003":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "中秋徽章配方", "outputItemId" : "itemTemplate-51008", "recipeId" : "peifang-10003", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 100 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 100 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 100 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 100 } ] }
,"peifang-10004":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "坐骑玄灵配方", "outputItemId" : "itemTemplate-43166", "recipeId" : "peifang-10004", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 100 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 100 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 100 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 100 } ] }
,"peifang-10005":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "坐骑元灵配方", "outputItemId" : "itemTemplate-43110", "recipeId" : "peifang-10005", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 6 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 6 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 6 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 6 } ] }
,"peifang-10006":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 60, "moneyAmount" : 0, "moneyType" : "money", "name" : "炫星配方", "outputItemId" : "itemTemplate-50992", "recipeId" : "peifang-10006", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 3 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 4 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10007":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 60, "moneyAmount" : 0, "moneyType" : "money", "name" : "陨星配方", "outputItemId" : "itemTemplate-43156", "recipeId" : "peifang-10007", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 3 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 4 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10008":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "潜能激发丹配方", "outputItemId" : "itemTemplate-43014", "recipeId" : "peifang-10008", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 20 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 20 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 20 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 20 } ] }
,"peifang-10009":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 88, "moneyAmount" : 0, "moneyType" : "money", "name" : "凤凰血石大礼包配方", "outputItemId" : "itemTemplate-121867", "recipeId" : "peifang-10009", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 25 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 25 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 25 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 25 } ] }
,"peifang-10010":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 80, "moneyAmount" : 0, "moneyType" : "money", "name" : "三倍经验丹配方", "outputItemId" : "itemTemplate-51044", "recipeId" : "peifang-10010", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 8 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 8 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 8 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 8 } ] }
,"peifang-10011":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 60, "moneyAmount" : 0, "moneyType" : "money", "name" : "天外陨铁礼包配方", "outputItemId" : "itemTemplate-121868", "recipeId" : "peifang-10011", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 2 } ] }
,"peifang-10012":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 88, "moneyAmount" : 0, "moneyType" : "money", "name" : "采光石礼包配方", "outputItemId" : "itemTemplate-121869", "recipeId" : "peifang-10012", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10013":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 88, "moneyAmount" : 0, "moneyType" : "money", "name" : "凤凰血石礼包配方", "outputItemId" : "itemTemplate-121870", "recipeId" : "peifang-10013", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 2 } ] }
,"peifang-10014":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 84, "moneyAmount" : 0, "moneyType" : "money", "name" : "奇门要术礼包配方", "outputItemId" : "itemTemplate-121871", "recipeId" : "peifang-10014", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 4 } ] }
,"peifang-10015":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 82, "moneyAmount" : 0, "moneyType" : "money", "name" : "炼体丹礼包配方", "outputItemId" : "itemTemplate-121872", "recipeId" : "peifang-10015", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10016":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 45, "moneyAmount" : 0, "moneyType" : "money", "name" : "星空之沙礼包配方", "outputItemId" : "itemTemplate-121873", "recipeId" : "peifang-10016", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10017":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 86, "moneyAmount" : 0, "moneyType" : "money", "name" : "源灵琼浆礼包配方", "outputItemId" : "itemTemplate-121874", "recipeId" : "peifang-10017", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 2 } ] }
,"peifang-10018":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "闪亮的珍珠配方", "outputItemId" : "itemTemplate-43242", "recipeId" : "peifang-10018", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 0 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 4 } ] }
,"peifang-10019":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 100, "moneyAmount" : 0, "moneyType" : "money", "name" : "六阶装备升阶卷轴配方", "outputItemId" : "itemTemplate-50977", "recipeId" : "peifang-10019", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 1 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 1 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 1 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 1 } ] }
,"peifang-10020":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "活络丹礼包配方", "outputItemId" : "itemTemplate-121876", "recipeId" : "peifang-10020", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 2 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 2 } ] }
,"peifang-10021":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "冰龙配方", "outputItemId" : "itemTemplate-170024", "recipeId" : "peifang-10021", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 888 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 888 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 888 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 888 } ] }
,"peifang-10022":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "国庆徽章配方", "outputItemId" : "itemTemplate-51016", "recipeId" : "peifang-10022", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 100 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 100 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 100 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 100 } ] }
,"peifang-10023":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "脱光徽章配方", "outputItemId" : "itemTemplate-51023", "recipeId" : "peifang-10023", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 100 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 100 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 100 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 100 } ] }
,"peifang-10024":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "坐骑升阶符礼包配方", "outputItemId" : "itemTemplate-122010", "recipeId" : "peifang-10024", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 0 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 5 } ] }
,"peifang-10025":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 65, "moneyAmount" : 0, "moneyType" : "money", "name" : "明光火种礼包配方", "outputItemId" : "itemTemplate-122011", "recipeId" : "peifang-10025", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 2 } ] }
,"peifang-10026":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "清琉天翼配方", "outputItemId" : "itemTemplate-51051", "recipeId" : "peifang-10026", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 688 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 688 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 688 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 688 } ] }
,"peifang-10027":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "小僵尸配方", "outputItemId" : "itemTemplate-51030", "recipeId" : "peifang-10027", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 200 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 200 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 200 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 200 } ] }
,"peifang-10028":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 86, "moneyAmount" : 0, "moneyType" : "money", "name" : "甘露丹（10000）配方", "outputItemId" : "itemTemplate-51045", "recipeId" : "peifang-10028", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 2 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10029":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "小妖精（激活卡）配方", "outputItemId" : "itemTemplate-51028", "recipeId" : "peifang-10029", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 200 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 200 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 200 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 200 } ] }
,"peifang-10030":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 80, "moneyAmount" : 0, "moneyType" : "money", "name" : "经验池（1000万）配方", "outputItemId" : "itemTemplate-51058", "recipeId" : "peifang-10030", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 20 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 20 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 20 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 20 } ] }
,"peifang-10031":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 72, "moneyAmount" : 0, "moneyType" : "money", "name" : "言灵符礼包配方", "outputItemId" : "itemTemplate-122088", "recipeId" : "peifang-10031", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 2 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 4 } ] }
,"peifang-10032":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "天灵符礼包配方", "outputItemId" : "itemTemplate-122229", "recipeId" : "peifang-10032", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 0 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 5 } ] }
,"peifang-10033":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "朱盈天翼", "outputItemId" : "itemTemplate-51107", "recipeId" : "peifang-10033", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 688 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 688 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 688 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 688 } ] }
,"peifang-10034":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "一只兔子兑换配方", "outputItemId" : "itemTemplate-170025", "recipeId" : "peifang-10034", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 888 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 888 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 888 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 888 } ] }
,"peifang-10035":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "圣焰彤心时装配方", "outputItemId" : "itemTemplate-51114", "recipeId" : "peifang-10035", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 608 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 608 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 608 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 608 } ] }
,"peifang-10036":{ "TVNotice" : 0, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "琼月之华礼包配方", "outputItemId" : "itemTemplate-122283", "recipeId" : "peifang-10036", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 0 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 4 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 4 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 8 } ] }
,"peifang-10037":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 62, "moneyAmount" : 0, "moneyType" : "money", "name" : "补天石大礼包配方", "outputItemId" : "itemTemplate-122535", "recipeId" : "peifang-10037", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 10 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 20 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 20 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 20 } ] }
,"peifang-10038":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 62, "moneyAmount" : 0, "moneyType" : "money", "name" : "补天石礼包配方", "outputItemId" : "itemTemplate-122536", "recipeId" : "peifang-10038", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 3 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 3 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 3 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 3 } ] }
,"peifang-10039":{ "TVNotice" : 1, "TVNoticeContent" : "{0}成功兑换了{1}*{2}", "level" : 30, "moneyAmount" : 0, "moneyType" : "money", "name" : "仙侣锦梦（永久）配方", "outputItemId" : "itemTemplate-51103", "recipeId" : "peifang-10039", "recipeStuffList" : [ { "itemId" : "itemTemplate-51040", "itemName" : "欢沁竹卡", "amount" : 288 }, { "itemId" : "itemTemplate-51041", "itemName" : "乐游帛卡", "amount" : 288 }, { "itemId" : "itemTemplate-51042", "itemName" : "九转玉卡", "amount" : 288 }, { "itemId" : "itemTemplate-51043", "itemName" : "仙域锦卡", "amount" : 288 } ] }
};

		}
	}
}