package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class fashionBook extends MovieClip
	{
		public var configData:Object = null;

		public function fashionBook()
		{
			Security.allowDomain('*');

			configData = 

{"sztj-100001":{ "activateItemDict" : "dict-400071", "activateItemId" : "itemTemplate-51102", "activateTvText" : "{0}激活了{1}时装，顿时羡煞旁人！", "addExp" : 100, "class" : "all", "duration" : 7, "genderInfoList" : [ { "gender" : "male", "nameText" : "雪羽凌冰（男）", "nameIcon" : "image/ui/shizhuang/mingzi1.png", "icon" : "image/icon64/item/xueyu64.png", "icon48" : "image/icon48/item/xueyu48.png", "description" : "以天地灵气制成的男子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangbingxuenan", "wing" : "leiyin" }, { "gender" : "female", "nameText" : "雪羽凌冰（女）", "nameIcon" : "image/ui/shizhuang/mingzi1.png", "icon" : "image/icon64/item/xueyufemale64.png", "icon48" : "image/icon48/item/xueyufemale48.png", "description" : "以天地灵气制成的女子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangbingxuenv", "wing" : "tianxiang" } ], "getTip" : "可在商城中购买获得", "gradeExpDict" : "dict-200151", "gradePropDict" : "dict-100057", "gradeWorthDict" : "dict-200152", "id" : "sztj-100001", "isActivateTv" : true, "isPermanentTv" : true, "name" : "雪羽凌冰", "permanentDuration" : 42, "permanentTvText" : "{0}累计获得42天{1}的使用权后，终于将其变为终身所有！", "quality" : 5, "reinforceBaseExpDict" : "dict-200150", "reinforceBoxList" : [ { "box" : 1, "weight" : 850 }, { "box" : 3, "weight" : 150 } ], "reinforceItemId" : "itemTemplate-51101", "reinforceItemNumDict" : "dict-200149", "reinforceServiceType" : "shizhuangqianghua", "reinforceTvGrade" : 6, "reinforceTvText" : "{0}将{1}时装强化到{2}星，更加光彩照人了！", "reinforceWardrobeExpDict" : "dict-200153", "serviceType" : "xianyinglanyu", "showEffect" : "image/swf/shizhuang/shizhuang1.swf" }
,"sztj-100002":{ "activateItemDict" : "dict-400072", "activateItemId" : "itemTemplate-51102", "activateTvText" : "{0}激活了{1}时装，顿时羡煞旁人！", "addExp" : null, "class" : "all", "duration" : null, "genderInfoList" : [ { "gender" : "male", "nameText" : "仙侣锦梦（男）", "nameIcon" : "image/ui/shizhuang/mingzi4.png", "icon" : "image/icon64/item/meiguimale64.png", "icon48" : "image/icon48/item/meiguimale48.png", "description" : "以玫瑰花露制成的男子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangqingrenjienan", "wing" : "leiyin" }, { "gender" : "female", "nameText" : "仙侣锦梦（女）", "nameIcon" : "image/ui/shizhuang/mingzi4.png", "icon" : "image/icon64/item/meiguifemale64.png", "icon48" : "image/icon48/item/meiguifemale48.png", "description" : "以玫瑰花露制成的女子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangqingrenjienv", "wing" : "leiyin" } ], "getTip" : "参加情人节活动可获得", "gradeExpDict" : "dict-200151", "gradePropDict" : "dict-100058", "gradeWorthDict" : "dict-200152", "id" : "sztj-100002", "isActivateTv" : true, "isPermanentTv" : true, "name" : "仙侣锦梦", "permanentDuration" : 42, "permanentTvText" : "{0}累计获得42天{1}的使用权后，终于将其变为终身所有！", "quality" : 5, "reinforceBaseExpDict" : "dict-200150", "reinforceBoxList" : [ { "box" : 1, "weight" : 850 }, { "box" : 3, "weight" : 150 } ], "reinforceItemId" : "itemTemplate-51101", "reinforceItemNumDict" : "dict-200149", "reinforceServiceType" : "shizhuangqianghua", "reinforceTvGrade" : 6, "reinforceTvText" : "{0}将{1}时装强化到{2}星，更加光彩照人了！", "reinforceWardrobeExpDict" : "dict-200153", "serviceType" : null, "showEffect" : "image/swf/shizhuang/shizhuang4.swf" }
,"sztj-100003":{ "activateItemDict" : "dict-400073", "activateTvText" : "{0}激活了{1}时装，顿时羡煞旁人！", "addExp" : 100, "class" : "all", "duration" : 7, "genderInfoList" : [ { "gender" : "male", "nameText" : "曜日春晖（男）", "nameIcon" : "image/ui/shizhuang/mingzi3.png", "icon" : "image/icon64/item/chunhuimale64.png", "icon48" : "image/icon48/item/chunhuimale48.png", "description" : "新春的气息编织而成的男子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangchunjienan", "wing" : "leiyin" }, { "gender" : "female", "nameText" : "曜日春晖（女）", "nameIcon" : "image/ui/shizhuang/mingzi3.png", "icon" : "image/icon64/item/chunhuifemale64.png", "icon48" : "image/icon48/item/chunhuifemale48.png", "description" : "新春的气息编织而成的女子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangchunjienv", "wing" : "leiyin" } ], "getTip" : "可在商城中购买获得", "gradeExpDict" : "dict-200151", "gradePropDict" : "dict-100059", "gradeWorthDict" : "dict-200152", "id" : "sztj-100003", "isActivateTv" : true, "isPermanentTv" : true, "name" : "曜日春晖", "permanentDuration" : 42, "permanentTvText" : "{0}累计获得42天{1}的使用权后，终于将其变为终身所有！", "quality" : 5, "reinforceBaseExpDict" : "dict-200150", "reinforceBoxList" : [ { "box" : 3, "weight" : 150 }, { "box" : 1, "weight" : 850 } ], "reinforceItemId" : "itemTemplate-51101", "reinforceItemNumDict" : "dict-200149", "reinforceServiceType" : "shizhuangqianghua", "reinforceTvGrade" : 6, "reinforceTvText" : "{0}将{1}时装强化到{2}星，更加光彩照人了！", "reinforceWardrobeExpDict" : "dict-200153", "serviceType" : "shizhuang2", "showEffect" : "image/swf/shizhuang/shizhuang3.swf" }
,"sztj-100004":{ "activateItemDict" : "dict-400078", "activateTvText" : "{0}激活了{1}时装，顿时羡煞旁人！", "addExp" : null, "class" : "all", "duration" : null, "genderInfoList" : [ { "gender" : "female", "nameText" : "圣焰彤心（女）", "nameIcon" : "image/ui/shizhuang/mingzi2.png", "icon" : "image/icon64/item/shengyanfemale64.png", "icon48" : "image/icon48/item/shengyanfemale48.png", "description" : "以火焰之核制成的女子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuanglietianshimonv", "wing" : "leiyin" }, { "gender" : "male", "nameText" : "圣焰彤心（男）", "nameIcon" : "image/ui/shizhuang/mingzi2.png", "icon" : "image/icon64/item/shengyan64.png", "icon48" : "image/icon48/item/shengyan48.png", "description" : "以火焰之核制成的男子仙衣。\n此时装累计续费达到42天后，即可变为永久使用哦！", "appearance" : "shizhuangguiqinan", "wing" : "leiyin" } ], "getTip" : "可在某些神秘商人活动中兑换", "gradeExpDict" : "dict-200155", "gradePropDict" : "dict-100061", "gradeWorthDict" : "dict-200156", "id" : "sztj-100004", "isActivateTv" : true, "isPermanentTv" : true, "name" : "圣焰彤心", "permanentDuration" : 42, "permanentTvText" : "{0}累计获得42天{1}的使用权后，终于将其变为终身所有！", "quality" : 6, "reinforceBaseExpDict" : "dict-200150", "reinforceBoxList" : [ { "box" : 3, "weight" : 150 }, { "box" : 1, "weight" : 850 } ], "reinforceItemId" : "itemTemplate-51101", "reinforceItemNumDict" : "dict-200149", "reinforceServiceType" : "shizhuangqianghua", "reinforceTvGrade" : 6, "reinforceTvText" : "{0}将{1}时装强化到{2}星，更加光彩照人了！", "reinforceWardrobeExpDict" : "dict-200153", "serviceType" : null, "showEffect" : "image/swf/shizhuang/shizhuang2.swf" }
};

		}
	}
}