package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class giftcallback extends MovieClip
	{
		public var configData:Object = null;

		public function giftcallback()
		{
			Security.allowDomain('*');

			configData = 

{"gift-111":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2012-12-05 23:59:59", "expire" : 0, "giftId" : "gift-111", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2012-11-20 00:00:00" }
,"gift-112":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-01-13 23:59:59", "expire" : 0, "giftId" : "gift-112", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-01-07 00:00:00" }
,"gift-113":{ "afkDay" : 15, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-02-28 23:59:59", "expire" : 0, "giftId" : "gift-113", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-02-25 00:00:00" }
,"gift-114":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-03-18 23:59:59", "expire" : 0, "giftId" : "gift-114", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-03-12 00:00:00" }
,"gift-115":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-04-13 23:59:59", "expire" : 0, "giftId" : "gift-115", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-04-09 00:00:00" }
,"gift-116":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-05-16 23:59:59", "expire" : 0, "giftId" : "gift-116", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-05-10 00:00:00" }
,"gift-117":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-05-31 23:59:59", "expire" : 0, "giftId" : "gift-117", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-05-25 00:00:00" }
,"gift-118":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-06-17 23:59:59", "expire" : 0, "giftId" : "gift-118", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-06-08 00:00:00" }
,"gift-119":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-06-30 23:59:59", "expire" : 0, "giftId" : "gift-119", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-06-25 00:00:00" }
,"gift-120":{ "afkDay" : 10, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>的感恩宝箱！", "endTime" : "2013-07-18 00:00:00", "expire" : 0, "giftId" : "gift-120", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了感恩宝箱。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-07-12 00:00:00" }
,"gift-121":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-07-31 23:59:59", "expire" : 0, "giftId" : "gift-121", "itemId" : "itemTemplate-121190", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-07-25 00:00:00" }
,"gift-122":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-07-31 23:59:59", "expire" : 0, "giftId" : "gift-122", "itemId" : "itemTemplate-121191", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-07-25 00:00:00" }
,"gift-123":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-07-31 23:59:59", "expire" : 0, "giftId" : "gift-123", "itemId" : "itemTemplate-121192", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-07-25 00:00:00" }
,"gift-124":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-07-31 23:59:59", "expire" : 0, "giftId" : "gift-124", "itemId" : "itemTemplate-121193", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-07-25 00:00:00" }
,"gift-125":{ "UIType" : "", "afkDay" : 10, "afkDayMax" : 0, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>！", "endTime" : "2013-08-18 23:59:59", "expire" : 0, "giftId" : "gift-125", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-14 00:00:00" }
,"gift-126":{ "UIType" : "", "afkDay" : 10, "afkDayMax" : 0, "bound" : 1, "description" : "QQ九仙非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙。<font color='#FFFF00'>{sFrom}</font>为您提供了含有<font color='#FFFF00'>海量经验</font>以及大量<font color='#FFFF00'>商城道具</font>！", "endTime" : "2013-08-31 23:59:59", "expire" : 0, "giftId" : "gift-126", "itemId" : "itemTemplate-120445", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-26 00:00:00" }
,"gift-127":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-08-24 23:59:59", "expire" : 0, "giftId" : "gift-127", "itemId" : "itemTemplate-121190", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-19 00:00:00" }
,"gift-128":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-08-24 23:59:59", "expire" : 0, "giftId" : "gift-128", "itemId" : "itemTemplate-121191", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-19 00:00:00" }
,"gift-129":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-08-24 23:59:59", "expire" : 0, "giftId" : "gift-129", "itemId" : "itemTemplate-121192", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-19 00:00:00" }
,"gift-130":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-08-24 23:59:59", "expire" : 0, "giftId" : "gift-130", "itemId" : "itemTemplate-121193", "name" : "回流活动", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了回流礼包。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-08-19 00:00:00" }
,"gift-131":{ "UIType" : "zhounianqing", "afkDay" : 14, "afkDayMax" : 0, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-09-15 23:59:59", "expire" : 0, "giftId" : "gift-131", "itemId" : "itemTemplate-121315", "name" : "周年庆回流活动", "sFrom" : [ "website", "qzone", "xiaoyou", "qqgame", "3366", "qplus", "qqvip" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-09-06 00:00:00" }
,"gift-132":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-09-25 23:59:59", "expire" : 0, "giftId" : "gift-132", "itemId" : "itemTemplate-121190", "name" : "大厅周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-09-19 00:00:00" }
,"gift-133":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-09-25 23:59:59", "expire" : 0, "giftId" : "gift-133", "itemId" : "itemTemplate-121191", "name" : "大厅双周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-09-19 00:00:00" }
,"gift-134":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-09-25 23:59:59", "expire" : 0, "giftId" : "gift-134", "itemId" : "itemTemplate-121192", "name" : "大厅月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-09-19 00:00:00" }
,"gift-135":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-09-25 23:59:59", "expire" : 0, "giftId" : "gift-135", "itemId" : "itemTemplate-121193", "name" : "大厅三月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-09-19 00:00:00" }
,"gift-136":{ "UIType" : "", "afkDay" : 30, "afkDayMax" : 0, "bound" : 1, "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-10-21 23:59:59", "expire" : 0, "giftId" : "gift-136", "itemId" : "itemTemplate-121493", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-10-17 00:00:00" }
,"gift-137":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "buttonUrl" : "http://qqgame.qq.com/act/a20131015shjq/index.html", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-10-31 23:59:59", "expire" : 0, "giftId" : "gift-137", "itemId" : "itemTemplate-121190", "name" : "大厅周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-10-25 00:00:00" }
,"gift-138":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "buttonUrl" : "http://qqgame.qq.com/act/a20131015shjq/index.html", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-10-31 23:59:59", "expire" : 0, "giftId" : "gift-138", "itemId" : "itemTemplate-121191", "name" : "大厅双周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-10-25 00:00:00" }
,"gift-139":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "buttonUrl" : "http://qqgame.qq.com/act/a20131015shjq/index.html", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-10-31 23:59:59", "expire" : 0, "giftId" : "gift-139", "itemId" : "itemTemplate-121192", "name" : "大厅月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-10-25 00:00:00" }
,"gift-140":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "http://qqgame.qq.com/act/a20131015shjq/index.html", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-10-31 23:59:59", "expire" : 0, "giftId" : "gift-140", "itemId" : "itemTemplate-121193", "name" : "大厅三月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-10-25 00:00:00" }
,"gift-141":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-11-18 23:59:59", "expire" : 0, "giftId" : "gift-141", "itemId" : "itemTemplate-121190", "name" : "大厅周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-11-11 00:00:00" }
,"gift-142":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-11-18 23:59:59", "expire" : 0, "giftId" : "gift-142", "itemId" : "itemTemplate-121191", "name" : "大厅双周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-11-11 00:00:00" }
,"gift-143":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-11-18 23:59:59", "expire" : 0, "giftId" : "gift-143", "itemId" : "itemTemplate-121192", "name" : "大厅月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-11-11 00:00:00" }
,"gift-144":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-11-18 23:59:59", "expire" : 0, "giftId" : "gift-144", "itemId" : "itemTemplate-121193", "name" : "大厅三月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-11-11 00:00:00" }
,"gift-145":{ "UIType" : "", "afkDay" : 10, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-12-24 23:59:59", "expire" : 0, "giftId" : "gift-145", "itemId" : "itemTemplate-121842", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-12-20 00:00:00" }
,"gift-146":{ "UIType" : "summer", "afkDay" : 7, "afkDayMax" : 14, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-12-15 23:59:59", "expire" : 0, "giftId" : "gift-146", "itemId" : "itemTemplate-121190", "name" : "大厅周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-12-10 00:00:00" }
,"gift-147":{ "UIType" : "summer", "afkDay" : 14, "afkDayMax" : 30, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-12-15 23:59:59", "expire" : 0, "giftId" : "gift-147", "itemId" : "itemTemplate-121191", "name" : "大厅双周回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-12-10 00:00:00" }
,"gift-148":{ "UIType" : "summer", "afkDay" : 30, "afkDayMax" : 90, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-12-15 23:59:59", "expire" : 0, "giftId" : "gift-148", "itemId" : "itemTemplate-121192", "name" : "大厅月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-12-10 00:00:00" }
,"gift-149":{ "UIType" : "summer", "afkDay" : 90, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2013-12-15 23:59:59", "expire" : 0, "giftId" : "gift-149", "itemId" : "itemTemplate-121193", "name" : "大厅三月回流", "sFrom" : [ "qqgame" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2013-12-10 00:00:00" }
,"gift-150":{ "UIType" : "", "afkDay" : 10, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2014-01-18 23:59:59", "expire" : 0, "giftId" : "gift-150", "itemId" : "itemTemplate-121842", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2014-01-13 00:00:00" }
,"gift-151":{ "UIType" : "", "afkDay" : 10, "afkDayMax" : 0, "bound" : 1, "buttonUrl" : "", "description" : "非常感谢您长久以来的支持，为了使您能够更好的畅玩QQ九仙，<font color='#FFFF00'>{sFrom}</font>特意为您准备了<font color='#FFFF00'>丰厚的礼物</font>，包括：<font color='#FFFF00'>海量经验</font>以及多种稀有的<font color='#FFFF00'>商城道具</font>！\n希望您能在九仙的世界里，享受到更多的乐趣！", "endTime" : "2014-03-25 23:59:59", "expire" : 0, "giftId" : "gift-151", "itemId" : "itemTemplate-121842", "name" : "回流活动", "sFrom" : [ "qzone", "xiaoyou", "qqgame", "3366" ], "share" : "我通过{sFrom}在QQ九仙中成功领取了海量经验及商城道具。QQ九仙新玩法、新追求、新体验！", "startTime" : "2014-03-21 00:00:00" }
};

		}
	}
}