package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class goals extends MovieClip
	{
		public var configData:Object = null;

		public function goals()
		{
			Security.allowDomain('*');

			configData = 

{"goal-0101":{ "bonus" : [], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "在解决了太虚幻境中的种种乱象之后，你来到现实的缘起村，帮助解决缘起村的困境，进入白云镇开始种种的历练，结识共同除妖卫道的好友，你已经渐渐融入了九仙的世界，开始另一次奇妙的旅程。", "dayNum" : 1, "description" : "迅速完成主线任务是前期提升自身等级的最快速的方法，快速达到20级对你来说只是小菜一碟而已。", "exp" : 0, "goalId" : "goal-0101", "key" : "", "money" : 0, "name" : "提升角色等级至[curr]/[value]级", "title" : "现世", "token" : 50, "value" : 20 }
,"goal-0102":{ "bonus" : [], "boundMoney" : 0, "category" : "friendAmount", "dayDescription" : "在解决了太虚幻境中的种种乱象之后，你来到现实的缘起村，帮助解决缘起村的困境，进入白云镇开始种种的历练，结识共同除妖卫道的好友，你已经渐渐融入了九仙的世界，开始另一次奇妙的旅程。", "dayNum" : 1, "description" : "添加好友则会对你今后的游戏过程给予很大的助力，交到越多的朋友，属于你的游戏才会越精彩，你可以点击其他玩家菜单选择添加好友。快去交5个朋友吧！", "exp" : 0, "goalId" : "goal-0102", "key" : "", "money" : 0, "name" : "好友数量达到[curr]/[value]", "title" : "现世", "token" : 50, "value" : 5 }
,"goal-0201":{ "bonus" : [ { "itemId" : "itemTemplate-3449", "count" : 25, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "随着时间的推移，你觉得自己的仙法愈加纯熟，开始接触到传说中神秘的无字天书，不懈努力击败妖魔收集着天书残页和天书残卷。现在的你变得更为强大，无字天书的奥秘也开始渐渐展现出来……", "dayNum" : 2, "description" : "你的等级提升的很快，当你达到20级的时候，可以领取天书任务，也是所有玩家可以获得大量经验的来源，快点升级到28级吧！", "exp" : 0, "goalId" : "goal-0201", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "天机", "token" : 0, "value" : 28 }
,"goal-0202":{ "bonus" : [], "boundMoney" : 0, "category" : "questCategoryComplete", "dayDescription" : "随着时间的推移，你觉得自己的仙法愈加纯熟，开始接触到传说中神秘的无字天书，不懈努力击败妖魔收集着天书残页和天书残卷。现在的你变得更为强大，无字天书的奥秘也开始渐渐展现出来……", "dayNum" : 2, "description" : "天书任务是游戏中贯穿始终的任务，你可以通过消耗非绑定钱币和八卦图来刷新天书任务的奖励。随着你等级的提升，每天可以完成的天书任务次数还会增加。你需要先完成5个天书任务。", "exp" : 0, "goalId" : "goal-0202", "key" : "wuji", "money" : 0, "name" : "完成[curr]/[value]个天书任务", "title" : "天机", "token" : 75, "value" : 5 }
,"goal-0301":{ "bonus" : [], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "通过不断修习仙法，你很快已经找到了属于自己的仙法法门，仙术力量提升的速度一日千里，精纯仙法之道和合与心间。同时，你找到了志同道合的仙友家族，成为了一个庞大家庭的一份子，新的力量和新的责任都在等待着你。", "dayNum" : 3, "description" : "你的等级提升的很快，当你达到等级25以后，还可以接取师门任务也是所有玩家可以获得经验的另一个重要来源，快点升级到34级吧！", "exp" : 0, "goalId" : "goal-0301", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "入道", "token" : 100, "value" : 34 }
,"goal-0302":{ "bonus" : [], "boundMoney" : 0, "category" : "questCategoryComplete", "dayDescription" : "通过不断修习仙法，你很快已经找到了属于自己的仙法法门，仙术力量提升的速度一日千里，精纯仙法之道和合与心间。同时，你找到了志同道合的仙友家族，成为了一个庞大家庭的一份子，新的力量和新的责任都在等待着你。", "dayNum" : 3, "description" : "当你拜师之后，你就开始了你所在门派的修习。师门任务是所有玩家的另一大量经验的来源，每天可以完成10环，当更多的环任务被完成后，你还可以获得经验加成。", "exp" : 0, "goalId" : "goal-0302", "key" : "class", "money" : 0, "name" : "完成[curr]/[value]环师门任务", "title" : "入道", "token" : 100, "value" : 10 }
,"goal-0303":{ "bonus" : [ { "itemId" : "itemTemplate-178", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "joinFamily", "dayDescription" : "通过不断修习仙法，你很快已经找到了属于自己的仙法法门，仙术力量提升的速度一日千里，精纯仙法之道和合与心间。同时，你找到了志同道合的仙友家族，成为了一个庞大家庭的一份子，新的力量和新的责任都在等待着你。", "dayNum" : 3, "description" : "当你20级可以加入一个家族，30级则可以创建家族。创建家族需要300非绑定铜币，点击社会按钮中的家族面板就可以创建或者加入家族。快点加入一个家族，或者成为一个家族的族长，家族的荣耀需要你的支持与努力！", "exp" : 0, "goalId" : "goal-0303", "key" : "", "money" : 0, "name" : "加入一个家族[curr]/[value]", "title" : "入道", "token" : 0, "value" : 1 }
,"goal-0401":{ "bonus" : [ { "itemId" : "itemTemplate-149", "count" : 2, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "在玉京城的历练中，你得知银钩赌坊的坊主慕容冲贩卖女子，为了钱财不择手段，是时候除掉这颗毒瘤了。焦躁和怀疑是你此时最大的敌人，平和和睿智才是你的朋友。你依靠同伴的帮助，巧施暗计，混入赌坊之中，而等待你的是更加危险的挑战……", "dayNum" : 4, "description" : "你的等级提升的很快，已经俨然有点高手的风范了，继续努力快点升级到39级吧！", "exp" : 0, "goalId" : "goal-0401", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "守中", "token" : 0, "value" : 39 }
,"goal-0402":{ "bonus" : [], "boundMoney" : 0, "category" : "monsterKill", "dayDescription" : "在玉京城的历练中，你得知银钩赌坊的坊主慕容冲贩卖女子，为了钱财不择手段，是时候除掉这颗毒瘤了。焦躁和怀疑是你此时最大的敌人，平和和睿智才是你的朋友。你依靠同伴的帮助，巧施暗计，混入赌坊之中，而等待你的是更加危险的挑战……", "dayNum" : 4, "description" : "慕容冲是玉京城银钩赌坊的坊主，是你在九仙世界中前期会遇到的一个比较强大的首领，可以单独击杀他表示你的能力已经达到了较高的层次。另外，变身成帅气的慕容冲造型也有较强的能力加成。\n\n<font color='#00FF00'>目标</font>\n前往赌坊密室，击杀<a href='event:GameSpawnpoint-500601-302'><u><font color='#00FF00'>慕容冲</font></u></a>", "exp" : 0, "goalId" : "goal-0402", "key" : "Mob-0003007", "money" : 0, "name" : "击杀慕容冲[curr]/[value]", "title" : "守中", "token" : 150, "value" : 1 }
,"goal-0501":{ "bonus" : [ { "itemId" : "itemTemplate-6123", "count" : 75, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "在此时，你全心全力的强化自己的仙术造诣，力求一次又一次的仙术力量的飞跃和突破。在玉京城的经历，磨砺了你的精神意志，你的力量已经达到了新的层次，光明未来已经可以看见。", "dayNum" : 5, "description" : "你的等级提升的很快，在玉京城已经小有名气，继续努力快点升级到44级吧！", "exp" : 0, "goalId" : "goal-0501", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "潜心", "token" : 0, "value" : 44 }
,"goal-0502":{ "bonus" : [], "boundMoney" : 0, "category" : "avatarAbility", "dayDescription" : "在此时，你全心全力的强化自己的仙术造诣，力求一次又一次的仙术力量的飞跃和突破。在玉京城的经历，磨砺了你的精神意志，你的力量已经达到了新的层次，光明未来已经可以看见。", "dayNum" : 5, "description" : "攻击能力是九仙中的一项重要数值，这项数值代表了对你当前的攻击力的评分，评分越高，说明你能够输出的伤害越大。众多玩家都在为能不断提高攻击能力而努力着。", "exp" : 0, "goalId" : "goal-0502", "key" : "attack", "money" : 0, "name" : "攻击能力达到[curr]/[value]", "title" : "潜心", "token" : 200, "value" : 4500 }
,"goal-0601":{ "bonus" : [ { "itemId" : "itemTemplate-179", "count" : 4, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "有邪恶的地方，正义之光就会照耀到那里。阴森森的白骨洞，妖魔鬼怪在黑暗的角落发出阵阵冷笑，而你与同伴毅然决然的踏入这里，你知道在你的力量面前，邪恶无法阻止你的脚步。", "dayNum" : 6, "description" : "你的等级提升的很快，是时候试试自己的身手向邪恶挑战了，继续努力快点升级到49级吧！", "exp" : 0, "goalId" : "goal-0601", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "辟邪", "token" : 0, "value" : 49 }
,"goal-0602":{ "bonus" : [], "boundMoney" : 0, "category" : "monsterKill", "dayDescription" : "有邪恶的地方，正义之光就会照耀到那里。阴森森的白骨洞，妖魔鬼怪在黑暗的角落发出阵阵冷笑，而你与同伴毅然决然的踏入这里，你知道在你的力量面前，邪恶无法阻止你的脚步。", "dayNum" : 6, "description" : "九仙的世界中，副本是伴随玩家始终的重要游戏系统，许多你梦寐以求的极品装备都在击杀副本BOSS之后可以获得，而白骨洞副本的人尸白纤纤是所玩家所接触的第一个副本BOSS，完成对她的击杀将是对你的一次重要考验。\n\n<font color='#00FF00'>目标</font>\n前往白骨洞副本，击杀<a href='event:GameNpc-000202-802'><u><font color='#00FF00'>人尸白纤纤</font></u></a>", "exp" : 0, "goalId" : "goal-0602", "key" : "Mob-7001005", "money" : 0, "name" : "击杀白骨洞Boss人尸白纤纤[curr]/[value]", "title" : "辟邪", "token" : 200, "value" : 1 }
,"goal-0701":{ "bonus" : [ { "itemId" : "itemTemplate-8964", "count" : 10, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "不断的前行中，好的坐骑是你忠实的帮手。每一刻他都给予你力量，让你飞的更高，看的更远。你渐渐看到一个合二为一的境界，成为仙中之王者，畅游在天地宇宙之间。", "dayNum" : 7, "description" : "你的等级提升的很快，应该寻求更多的方式更好的提升自己的能力，继续努力快点升级到53级吧！", "exp" : 0, "goalId" : "goal-0701", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "融合", "token" : 0, "value" : 53 }
,"goal-0702":{ "bonus" : [], "boundMoney" : 0, "category" : "refineVehicle", "dayDescription" : "不断的前行中，好的坐骑是你忠实的帮手。每一刻他都给予你力量，让你飞的更高，看的更远。你渐渐看到一个合二为一的境界，成为仙中之王者，畅游在天地宇宙之间。", "dayNum" : 7, "description" : "在不断提升你自己的等级的同时，一个优良的坐骑将赋予你更强大的力量。而坐骑的资质可以通过洗练的方法来提升其附加属性，当洗练出更加优秀的附加属性之后，你就可以替换原有附加属性，使得坐骑为你提供更大的助益。", "exp" : 0, "goalId" : "goal-0702", "key" : "", "money" : 0, "name" : "洗炼一次坐骑资质[curr]/[value]", "title" : "融合", "token" : 250, "value" : 1 }
,"goal-0801":{ "bonus" : [ { "itemId" : "itemTemplate-4738", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "法宝神器是修仙者的生命。穿梭于六大门派之间，克服困难，斩妖除魔，蕴含神秘力量的宝石帮助你将法宝神器的力量发挥到极致，当宝石的伟大力量流动于全身，你眼前展开另一片仙者的天地。", "dayNum" : 8, "description" : "你的等级提升的很快，你的名气已经传播开来，一鼓作气，继续努力快点升级到56级吧！", "exp" : 0, "goalId" : "goal-0801", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "炼器", "token" : 0, "value" : 56 }
,"goal-0802":{ "bonus" : [], "boundMoney" : 0, "category" : "rune", "dayDescription" : "法宝神器是修仙者的生命。穿梭于六大门派之间，克服困难，斩妖除魔，蕴含神秘力量的宝石帮助你将法宝神器的力量发挥到极致，当宝石的伟大力量流动于全身，你眼前展开另一片仙者的天地。", "dayNum" : 8, "description" : "在九仙的世界中，玩家可以通过为装备镶嵌宝石的形式大幅度的提升装备的性能，使得装备在攻击、防御、生命值、法力值、暴击等级等方面获得更强大的能力。熟练合理的运用装备的镶嵌一定会帮你在众多玩家中脱颖而出。", "exp" : 0, "goalId" : "goal-0802", "key" : "", "money" : 0, "name" : "给装备镶嵌一颗宝石[curr]/[value]", "title" : "炼器", "token" : 300, "value" : 1 }
,"goal-0901":{ "bonus" : [], "boundMoney" : 0, "category" : "avatarLevel", "dayDescription" : "仙之大者，万灵归寂。你的仙法渐渐炉火纯青，开始飞入大乘世界，返璞归真的力量已经开始涌现，但是你知道这仅仅是修仙之路的第一步，灵寂的境界仅仅是新的开始，天顶依然在远方……", "dayNum" : 9, "description" : "等级达到60代表你完成了游戏的一个里程碑，这表示你已经具备了很强大的力量，可以通过各种副本和副本任务获得你所需要的金钱和经验等等。但是同时，也表示更加强大的对手等待着你的挑战，真正的战斗才刚刚开始。", "exp" : 0, "goalId" : "goal-0901", "key" : "", "money" : 0, "name" : "升至[curr]/[value]级", "title" : "腾龙", "token" : 500, "value" : 60 }
,"goal-1001":{ "bonus" : [], "boundMoney" : 0, "category" : "", "dayNum" : 10, "description" : "", "exp" : 0, "goalId" : "goal-1001", "key" : "", "money" : 0, "name" : "完成九仙所有目标[curr]/[value]", "title" : "", "token" : 500, "value" : 0 }
};

		}
	}
}