package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class growgifts extends MovieClip
	{
		public var configData:Object = null;

		public function growgifts()
		{
			Security.allowDomain('*');

			configData = 

{"gift-24001":{ "bonus" : [ { "name" : "1级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "1阶强化石*10、修理锤*5", "isOpen" : null, "itemId" : "itemTemplate-9244", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "1级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "1阶强化石*10、修理锤*5", "isOpen" : null, "itemId" : "itemTemplate-50224", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24001", "levelLimit" : 1, "name" : "1级升级礼包" }
,"gift-24002":{ "bonus" : [ { "name" : "10级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "仙灵丹*1", "isOpen" : null, "itemId" : "itemTemplate-9245", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "10级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "仙灵丹*1", "isOpen" : null, "itemId" : "itemTemplate-50225", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24002", "levelLimit" : 10, "name" : "10级升级礼包" }
,"gift-24003":{ "bonus" : [ { "name" : "20级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*20、还魂符*2", "isOpen" : null, "itemId" : "itemTemplate-9246", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "20级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*20、还魂符*2", "isOpen" : null, "itemId" : "itemTemplate-50226", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24003", "levelLimit" : 20, "name" : "20级升级礼包" }
,"gift-24004":{ "bonus" : [ { "name" : "30级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "灵芝续命丹*1、灵芝回气丸*1、邀月套装灵玉·颈部", "isOpen" : null, "itemId" : "itemTemplate-9247", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "30级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "灵芝续命丹*1、灵芝回气丸*1、邀月套装灵玉·颈部", "isOpen" : null, "itemId" : "itemTemplate-50227", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24004", "levelLimit" : 30, "name" : "30级升级礼包" }
,"gift-24005":{ "bonus" : [ { "name" : "40级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "仙灵丹*2、还魂符*2、八卦图*20", "isOpen" : null, "itemId" : "itemTemplate-9248", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "40级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "仙灵丹*2、还魂符*2、八卦图*20", "isOpen" : null, "itemId" : "itemTemplate-50228", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24005", "levelLimit" : 40, "name" : "40级升级礼包" }
,"gift-24006":{ "bonus" : [ { "name" : "50级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "3阶强化石*20、1阶尖晶宝石*1、坐骑资质丹*5", "isOpen" : null, "itemId" : "itemTemplate-9249", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "50级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "3阶强化石*20、1阶尖晶宝石*1、坐骑资质丹*5", "isOpen" : null, "itemId" : "itemTemplate-50229", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24006", "levelLimit" : 50, "name" : "50级升级礼包" }
,"gift-24007":{ "bonus" : [ { "name" : "60级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "修理锤*20、初级保险符*3、洗炼石*5", "isOpen" : null, "itemId" : "itemTemplate-9250", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "60级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "修理锤*20、初级保险符*3、洗炼石*5", "isOpen" : null, "itemId" : "itemTemplate-50230", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24007", "levelLimit" : 60, "name" : "60级升级礼包" }
,"gift-24008":{ "bonus" : [ { "name" : "65级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*40、2阶红宝石*1、坐骑锻造丹*15", "isOpen" : null, "itemId" : "itemTemplate-9251", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "65级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*40、2阶红宝石*1、坐骑锻造丹*15", "isOpen" : null, "itemId" : "itemTemplate-50231", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24008", "levelLimit" : 65, "name" : "65级升级礼包" }
,"gift-24009":{ "bonus" : [ { "name" : "70级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*4、高级坐骑资质丹*2", "isOpen" : null, "itemId" : "itemTemplate-9252", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "70级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*4、高级坐骑资质丹*2", "isOpen" : null, "itemId" : "itemTemplate-50232", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24009", "levelLimit" : 70, "name" : "70级升级礼包" }
,"gift-24010":{ "bonus" : [ { "name" : "75级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "4阶强化石*10、2阶尖晶宝石*1、2阶狂砂宝石* 1、八卦图*40", "isOpen" : null, "itemId" : "itemTemplate-9253", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "75级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "4阶强化石*10、2阶尖晶宝石*1、2阶狂砂宝石* 1、八卦图*40", "isOpen" : null, "itemId" : "itemTemplate-50233", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24010", "levelLimit" : 75, "name" : "75级升级礼包" }
,"gift-24011":{ "bonus" : [ { "name" : "80级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*2、坎离续命丹*1、坎离回气丸*1", "isOpen" : null, "itemId" : "itemTemplate-9254", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "80级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*2、坎离续命丹*1、坎离回气丸*1", "isOpen" : null, "itemId" : "itemTemplate-50234", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24011", "levelLimit" : 80, "name" : "80级升级礼包" }
,"gift-24012":{ "bonus" : [ { "name" : "85级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*40、高级坐骑资质丹*5、仙灵丹*2", "isOpen" : null, "itemId" : "itemTemplate-9255", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "85级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "八卦图*40、高级坐骑资质丹*5、仙灵丹*2", "isOpen" : null, "itemId" : "itemTemplate-50235", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24012", "levelLimit" : 85, "name" : "85级升级礼包" }
,"gift-24013":{ "bonus" : [ { "name" : "90级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "坐骑锻造丹*40、洗炼石*20、中级保险符*1", "isOpen" : null, "itemId" : "itemTemplate-9256", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "90级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "坐骑锻造丹*40、洗炼石*20、中级保险符*1", "isOpen" : null, "itemId" : "itemTemplate-50236", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24013", "levelLimit" : 90, "name" : "90级升级礼包" }
,"gift-24014":{ "bonus" : [ { "name" : "95级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "5阶强化石*5、2阶金盾宝石*3、2阶彩光宝石*3、修理锤*20", "isOpen" : null, "itemId" : "itemTemplate-9257", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "95级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "5阶强化石*5、2阶金盾宝石*3、2阶彩光宝石*3、修理锤*20", "isOpen" : null, "itemId" : "itemTemplate-50237", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24014", "levelLimit" : 95, "name" : "95级升级礼包" }
,"gift-24015":{ "bonus" : [ { "name" : "100级黄钻升级礼包", "sFrom" : [ "qzone", "xiaoyou", "box" ], "privilegeName" : "yellow", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*5、高级坐骑资质丹*5、中级保险符*2", "isOpen" : null, "itemId" : "itemTemplate-9258", "count" : 1, "bound" : 1, "class" : "" }, { "name" : "100级蓝钻升级礼包", "sFrom" : [ "qqgame", "3366" ], "privilegeName" : "blue", "privilegeValue" : 1, "privilegeLevelLimit" : -1, "description" : "还魂符*5、高级坐骑资质丹*5、中级保险符*2", "isOpen" : null, "itemId" : "itemTemplate-50238", "count" : 1, "bound" : 1, "class" : "" } ], "giftId" : "gift-24015", "levelLimit" : 100, "name" : "100级升级礼包" }
};

		}
	}
}