package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class guide extends MovieClip
	{
		public var configData:Object = null;

		public function guide()
		{
			Security.allowDomain('*');

			configData = 

{"guideTemplate-1":{ "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 2 } ], "description" : "<font color='#00FF00'><font color='#FFFF00'>高经验副本</font>（与众圣殿、龙之墓、舍利塔、百鬼夜行共用次数）</font>", "guideId" : "guideTemplate-1", "icon" : "image/icon/guide/baigudong.png", "index" : 99, "instanceGroupId" : "InstanceGroup-7100", "instanceId" : "Instance-7101", "label" : [ "经验副本" ], "level" : 28, "name" : "白骨洞", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-12":{ "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : "历练声望", "value" : 5 } ], "bonus" : [ { "type" : "2", "value" : "dict-000003" } ], "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>海量经验</font><font color='#FFFF00'>海量历练声望</font>", "guideId" : "guideTemplate-12", "icon" : "image/icon/guide/jingyanrenwu.png", "index" : 4, "instanceGroupId" : "", "label" : [ "任务", "经验任务" ], "level" : 25, "name" : "经验历练", "questlineId" : "questline-403001", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-16":{ "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 2 } ], "description" : "<font color='#00FF00'><font color='#FFFF00'>高经验副本</font>（与白骨洞、龙之墓、舍利塔、百鬼夜行共用次数）</font>", "guideId" : "guideTemplate-16", "icon" : "image/icon/guide/zhongshengdian.png", "index" : 95, "instanceGroupId" : "InstanceGroup-7100", "instanceId" : "Instance-7102", "label" : [ "经验副本" ], "level" : 58, "name" : "众圣殿", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-2":{ "appraise" : [ { "type" : "绑定钱币", "value" : 5 }, { "type" : " 钱  币 ", "value" : 5 }, { "type" : " 经  验 ", "value" : 4 } ], "bonus" : [ { "type" : "2", "value" : "dict-000004" } ], "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>海量绑定钱币</font><font color='#FFFF00'>海量钱币</font>", "guideId" : "guideTemplate-2", "icon" : "image/icon/guide/shangjinlieren.png", "index" : 3, "instanceGroupId" : "", "label" : [ "任务", "赏金猎人" ], "level" : 30, "name" : "赏金猎人", "questlineId" : "questline-404001", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-26":{ "appraise" : [ { "type" : "家族经验", "value" : 5 }, { "type" : "家族声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 4 } ], "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量家族声望</font>", "guideId" : "guideTemplate-26", "icon" : "image/icon/guide/jiazujianshe.png", "index" : 10, "instanceGroupId" : "", "instanceId" : "", "label" : [ "家族任务", "家族建设" ], "level" : 30, "name" : "家族建设", "questlineId" : "questline-700101", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-27":{ "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : "历练声望", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000001" } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font>", "guideId" : "guideTemplate-27", "icon" : "image/icon/guide/wuzitianshu.png", "index" : 1, "instanceGroupId" : "", "instanceId" : "", "label" : [ "任务", "无字" ], "level" : 20, "name" : "无字天书", "questlineId" : "questline-900001", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-28":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "leiyin", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-28", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900002", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-29":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "jiuzhou", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-29", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900003", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-30":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "tianxiang", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-30", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900004", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-31":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "taishang", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-31", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900005", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-32":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "tianlong", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-32", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900006", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-33":{ "appraise" : [ { "type" : "师门声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 5 }, { "type" : "绑定钱币", "value" : 4 } ], "bonus" : [ { "type" : "5", "value" : "dict-000002" }, { "type" : "10", "value" : "dict-000002" } ], "class" : "yaochi", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量经验</font></font>", "guideId" : "guideTemplate-33", "icon" : "image/icon/guide/shimenrenwu.png", "index" : 0, "instanceGroupId" : "", "instanceId" : "", "label" : [ "师门任务" ], "level" : 25, "name" : "师门任务", "questlineId" : "questline-900007", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-37":{ "appraise" : [ { "type" : " 经  验 ", "value" : 3 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 2 }, { "type" : "副本声望", "value" : 5 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>海量副本声望</font></font>", "guideId" : "guideTemplate-37", "icon" : "image/icon/guide/sanqingdian.png", "index" : 98, "instanceGroupId" : "InstanceGroup-7200", "instanceId" : "Instance-7201", "label" : [ "声望副本" ], "level" : 36, "name" : "三清殿", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-38":{ "appraise" : [ { "type" : " 经  验 ", "value" : 3 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : " 钱  币 ", "value" : 5 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>海量钱币</font></font>", "guideId" : "guideTemplate-38", "icon" : "image/icon/guide/leifengta.png", "index" : 97, "instanceGroupId" : "InstanceGroup-7300", "instanceId" : "Instance-7301", "label" : [ "钱币副本" ], "level" : 40, "name" : "雷峰塔", "questlineId" : "", "triggerTime" : "", "type" : 2 }
,"guideTemplate-39":{ "appraise" : [ { "type" : " 经  验 ", "value" : 3 }, { "type" : " 装  备 ", "value" : 2 }, { "type" : "绑定钱币", "value" : 2 }, { "type" : "套装灵玉", "value" : 5 } ], "bonus" : [ { "type" : "1", "value" : "dict-000005" }, { "type" : "2", "value" : "dict-000006" } ], "class" : "", "description" : "<font color='#00FF00'>产出<font color='#FFFF00'>道具、灵玉</font>，通关有<font color='#FFFF00'>额外奖励</font></font>", "guideId" : "guideTemplate-39", "icon" : "image/icon/guide/shituoling.png", "index" : 96, "instanceGroupId" : "InstanceGroup-7400", "instanceId" : "Instance-7401", "label" : [ "灵玉副本" ], "level" : 46, "name" : "狮驼岭", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-41":{ "appraise" : [ { "type" : "帮会经验", "value" : 5 }, { "type" : "帮会声望", "value" : 5 }, { "type" : " 经  验 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 4 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>帮会经验</font>、<font color='#FFFF00'>帮会声望</font>", "guideId" : "guideTemplate-41", "icon" : "image/icon/guide/guide_family_default.png", "index" : 12, "instanceGroupId" : "", "instanceId" : "", "label" : [ "帮会" ], "level" : 30, "name" : "帮会建设", "questlineId" : "questline-700301", "triggerTime" : "全天", "type" : 1 }
,"guideTemplate-42":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "class" : "", "description" : "第一次充值，无论多少，即可领取超值的首充豪华大礼包，内含本门派2阶2孔至尊法器*1、2阶2孔至尊护腕*1以及仙鹤幻化丹（7天）*1。", "giftId" : "gift-900001", "giftType" : 2, "guideId" : "guideTemplate-42", "icon" : "image/icon/guide/shouchonghaohua.png", "index" : 1, "instanceGroupId" : "", "instanceId" : "", "label" : [ "首充豪华大礼包" ], "level" : 20, "name" : "首充豪华大礼包", "questlineId" : "", "triggerTime" : "全天", "type" : 4 }
,"guideTemplate-43":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "class" : "", "description" : "只要首次消费满2000元宝即可获得洗练石、坐骑资质丹、坐骑资质重铸丹给力大礼包，内含洗练石*10、坐骑资质丹*10、坐骑资质重铸丹*1。", "giftId" : "gift-900002", "giftType" : 3, "guideId" : "guideTemplate-43", "icon" : "image/icon/guide/feixiangeili.png", "index" : 1, "instanceGroupId" : "", "instanceId" : "", "label" : [ "礼包" ], "level" : 20, "name" : "飞仙给力大礼包", "questlineId" : "", "triggerTime" : "全天", "type" : 4 }
,"guideTemplate-45":{ "actCount" : "每日2次", "actId" : "act-001001@act-001002", "actType" : 1, "appraise" : [ { "type" : " 经  验 ", "value" : 2 }, { "type" : "绑定钱币", "value" : 2 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>丰厚经验</font>和<font color='#FFFF00'>稀有道具</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-45", "icon" : "image/icon/guide/datihuodong.png", "index" : 400, "instanceGroupId" : "", "instanceId" : "", "label" : [ "活动指引" ], "level" : 20, "name" : "答题活动", "questlineId" : "", "triggerTime" : "11:30-11:40、19:40-19:50", "type" : 5 }
,"guideTemplate-46":{ "actCount" : "每日2次", "actId" : "act-002001", "actType" : 2, "appraise" : [ { "type" : "经验", "value" : 5 }, { "type" : "宝石", "value" : 5 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量宝石、冲穴丹、魔晶、魔界宝箱等。</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-46", "icon" : "image/icon/guide/mojieruqin.png", "index" : 300, "instanceGroupId" : "", "instanceId" : "", "label" : [ "活动指引" ], "level" : 28, "name" : "魔界远征", "questlineId" : "", "triggerTime" : "15:00-15:10、21:25-21:35", "type" : 5 }
,"guideTemplate-47":{ "actCount" : "每日1次", "actId" : "act-990001", "actType" : 3, "appraise" : [ { "type" : "商城道具", "value" : 5 }, { "type" : "非绑宝石", "value" : 5 } ], "class" : "", "description" : "<font color='#00FF00'>奖励<font color='#FFFF00'>大量珍奇道具</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-47", "icon" : "image/icon/guide/shijieboss.png", "index" : 200, "instanceGroupId" : "", "instanceId" : "", "label" : [ "活动指引" ], "level" : 40, "name" : "野外BOSS活动", "questlineId" : "", "triggerTime" : "每天21:40-22:00", "type" : 5 }
,"guideTemplate-54":{ "actCount" : "每天一次", "actId" : "", "actType" : 0, "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : " 好感度 ", "value" : 5 } ], "class" : "", "description" : "<font color='#00FF00'>互为好友通关加<font color='#FFFF00'>好感度2000</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-54", "icon" : "image/icon/guide/xianyuanfuben.png", "index" : 100, "instanceGroupId" : "InstanceGroup-8000", "instanceId" : "Instance-8000", "label" : [ "婚姻" ], "level" : 35, "name" : "仙缘副本", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-56":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'><font color='#FFFF00'>高经验副本</font>（与白骨洞、众圣殿、龙之墓、百鬼夜行共用次数）</font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-56", "icon" : "image/icon/guide/shelita.png", "index" : 93, "instanceGroupId" : "InstanceGroup-7100", "instanceId" : "Instance-7104", "label" : [ "经验副本" ], "level" : 100, "name" : "舍利塔", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-59":{ "actCount" : "1", "actId" : "act-006002", "actType" : 6, "appraise" : [], "bonus" : [], "class" : "", "description" : "杀怪、打坐可以获得双倍经验哦！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-59", "icon" : "image/icon/guide/shuangbeijingyan.png", "index" : 90, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 30, "name" : "双倍经验活动", "questlineId" : "", "triggerTime" : "每天17:00-17:30", "type" : 5 }
,"guideTemplate-60":{ "actCount" : "", "actId" : "", "actType" : 5, "appraise" : [], "bonus" : [], "class" : "", "description" : "无上荣耀尽在仙道会！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-60", "icon" : "image/icon/guide/xiandaohui.png", "index" : 80, "instanceGroupId" : "", "instanceId" : "Instance-8101", "label" : [], "level" : 40, "name" : "仙道斗法", "questlineId" : "", "triggerTime" : "每周一、二、四19:55-20:30", "type" : 5 }
,"guideTemplate-61":{ "actCount" : "", "actId" : "act-006003", "actType" : 6, "appraise" : [], "bonus" : [], "class" : "", "description" : "打坐可以获得5倍经验和灵气收益！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-61", "icon" : "image/icon/guide/huanlexiuxing.png", "index" : 85, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 23, "name" : "欢乐修行活动", "questlineId" : "", "triggerTime" : "每天12:00到12:30", "type" : 5 }
,"guideTemplate-62":{ "actCount" : "", "actId" : "act-007001", "actType" : 7, "appraise" : [], "bonus" : [], "class" : "", "description" : "宝箱天降玉京城，珍稀道具免费领！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-62", "icon" : "image/icon/guide/tianjiangbaoxiang.png", "index" : 84, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 30, "name" : "天降宝箱活动", "questlineId" : "", "triggerTime" : "每天11:45到11:55", "type" : 5 }
,"guideTemplate-63":{ "actCount" : "每天一次", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>奖励：<font color='#FFFF00'>普通仙宠卡、天灵符、琼月之华、仙果等</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-63", "icon" : "image/icon/guide/shengshoudao.png", "index" : 92, "instanceGroupId" : "InstanceGroup-8300", "instanceId" : "Instance-8301", "label" : [ "单人副本" ], "level" : 45, "name" : "圣兽岛", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-64":{ "actCount" : "", "actId" : "ld-1001", "actType" : 8, "appraise" : [], "bonus" : [], "class" : "", "description" : "全民炼丹！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-64", "icon" : "image/icon/guide/liandan.png", "index" : 85, "instanceGroupId" : "", "instanceId" : "", "label" : [ "" ], "level" : 30, "name" : "炼丹活动", "questlineId" : "", "triggerTime" : "每天13:00到13:30", "type" : 5 }
,"guideTemplate-65":{ "actCount" : "warcraftTemplate-001", "actId" : "", "actType" : 9, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>奖励：<font color='#FFFF00'>大量战功、目标礼包</font></font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-65", "icon" : "image/icon/guide/xianwangzhanchang.png", "index" : 83, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 40, "name" : "仙王战场", "questlineId" : "", "triggerTime" : "每周二、四、六20:35-21:00", "type" : 5 }
,"guideTemplate-66":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 2 } ], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'><font color='#FFFF00'>高经验副本</font>（与白骨洞、众圣殿、龙之墓、舍利塔共用次数）</font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-66", "icon" : "image/icon/guide/baiguiyexing.png", "index" : 92, "instanceGroupId" : "InstanceGroup-7100", "instanceId" : "Instance-7105", "label" : [ "经验副本" ], "level" : 121, "name" : "百鬼夜行", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
,"guideTemplate-67":{ "actCount" : "", "actId" : "spring-001", "actType" : 10, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'><font color='#FFFF00'>随时可以</font>进入温泉，活动期间乐享<font color='#FFFF00'>5倍</font>沐浴经验！</font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-67", "icon" : "image/icon/guide/hotspring.png", "index" : 84, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 31, "name" : "仙界温泉", "questlineId" : "", "triggerTime" : "19:20-19:50（5倍收益）", "type" : 5 }
,"guideTemplate-68":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>奖励：<font color='#FFFF00'>大量经验、魔晶等</font></font>\n不同难度的天魔古堡副本共用次数。\n此模式通关42波可解锁普通模式。", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-68", "icon" : "image/icon/guide/tianmogubao1.png", "index" : 10, "instanceGroupId" : "InstanceGroup-8700", "instanceId" : "Instance-8701", "label" : [ "" ], "level" : 28, "name" : "天魔古堡", "questlineId" : "", "triggerTime" : "全天", "type" : 6 }
,"guideTemplate-69":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>奖励：<font color='#FFFF00'>大量经验、魔晶等</font></font>\n不同难度的天魔古堡副本共用次数。\n解锁此模式需要简单模式通关42波；此模式通关42波可解锁困难模式。", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-69", "icon" : "image/icon/guide/tianmogubao2.png", "index" : 9, "instanceGroupId" : "InstanceGroup-8700", "instanceId" : "Instance-8702", "label" : [], "level" : 28, "name" : "天魔古堡", "questlineId" : "", "triggerTime" : "全天", "type" : 6 }
,"guideTemplate-70":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>奖励：<font color='#FFFF00'>大量经验、魔晶等</font></font>\n不同难度的天魔古堡副本共用次数。\n解锁此模式需要普通模式通关42波。", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-70", "icon" : "image/icon/guide/tianmogubao3.png", "index" : 8, "instanceGroupId" : "InstanceGroup-8700", "instanceId" : "Instance-8703", "label" : [ "" ], "level" : 28, "name" : "天魔古堡", "questlineId" : "", "triggerTime" : "全天", "type" : 6 }
,"guideTemplate-72":{ "actCount" : "", "actId" : "", "actType" : 0, "appraise" : [], "bonus" : [], "class" : "", "description" : "<font color='#00FF00'>击杀该副本内怪物可获得让您意想不到的<font color='#FFFF00'>海量绑定钱币</font>！击杀其中等级≥86级的怪物还能获得超多玉净瓶升级所需的<font color='#FFFF00'>甘露</font>哦！\n温馨提示：该副本次数不会因服务器重启而重置。</font>", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-72", "icon" : "image/icon/guide/jinyumantang.png", "index" : 100, "instanceGroupId" : "InstanceGroup-9300", "instanceId" : "Instance-9301", "label" : [ "绑钱副本" ], "level" : 50, "name" : "金玉满堂", "questlineId" : "", "triggerTime" : "", "type" : 2 }
,"guideTemplate-73":{ "actCount" : "", "actId" : "GameWaypoint-000301-533", "actType" : 11, "appraise" : [], "bonus" : [], "class" : "", "description" : "灵丹、宝珠产地，挂机的不二选择！", "giftId" : "", "giftType" : 0, "guideId" : "guideTemplate-73", "icon" : "image/icon/guide/youmingfu.png", "index" : 82, "instanceGroupId" : "", "instanceId" : "", "label" : [], "level" : 50, "name" : "恶魔深渊", "questlineId" : "", "triggerTime" : "全天开放", "type" : 5 }
,"guideTemplate-8":{ "appraise" : [ { "type" : " 经  验 ", "value" : 5 }, { "type" : " 装  备 ", "value" : 4 }, { "type" : "绑定钱币", "value" : 2 } ], "description" : "<font color='#00FF00'><font color='#FFFF00'>高经验副本</font>（与众圣殿、白骨洞、舍利塔、百鬼夜行共用次数）</font>", "guideId" : "guideTemplate-8", "icon" : "image/icon/guide/longzhimu.png", "index" : 94, "instanceGroupId" : "InstanceGroup-7100", "instanceId" : "Instance-7103", "label" : [ "经验副本" ], "level" : 82, "name" : "龙之墓", "questlineId" : "", "triggerTime" : "全天", "type" : 2 }
};

		}
	}
}