package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class hdltLevel extends MovieClip
	{
		public var configData:Object = null;

		public function hdltLevel()
		{
			Security.allowDomain('*');

			configData = 

{"1":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1130 } ], "baseFailTimes" : 0, "baseRate" : 1, "breakType" : "0", "grade" : 1, "id" : 1, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位1", "rateModify" : 0.01, "serviceType" : "liantidan", "x" : 100, "y" : 240 }
,"2":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 380 } ], "baseFailTimes" : 2, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 2, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位2", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 160, "y" : 170 }
,"3":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 85 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 85 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 85 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 85 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 170 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 170 } ], "baseFailTimes" : 2, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 3, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位3", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 170, "y" : 240 }
,"4":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 170 } ], "baseFailTimes" : 2, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 4, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位4", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 275, "y" : 210 }
,"5":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 170 } ], "baseFailTimes" : 2, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 5, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位5", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 270, "y" : 270 }
,"6":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 60 } ], "baseFailTimes" : 2, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 6, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位6", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 320, "y" : 320 }
,"7":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 60 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 7, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位7", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 380, "y" : 240 }
,"8":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 220 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 220 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 110 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 110 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 110 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 110 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 220 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 220 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 8, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位8", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 440, "y" : 190 }
,"9":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1580 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 9, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位9", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 470, "y" : 240 }
,"10":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 1, "id" : 10, "itemId" : "itemTemplate-51002", "itemNum" : 1, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位10", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 530, "y" : 190 }
,"11":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 20 }, { "class" : "all", "attr" : "hpMax", "value" : 1000 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 1, "id" : 11, "itemId" : "itemTemplate-51003", "itemNum" : 1, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位11", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 550, "y" : 270 }
,"12":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1390 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 12, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位12", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 100, "y" : 240 }
,"13":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 460 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 13, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位13", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 165, "y" : 190 }
,"14":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 210 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 210 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 105 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 105 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 105 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 105 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 210 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 210 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 14, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位14", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 220, "y" : 220 }
,"15":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 210 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 15, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位15", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 150, "y" : 300 }
,"16":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 210 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 16, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位16", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 270, "y" : 280 }
,"17":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 70 } ], "baseFailTimes" : 3, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 17, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位17", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 350, "y" : 180 }
,"18":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 80 } ], "baseFailTimes" : 4, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 18, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位18", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 390, "y" : 240 }
,"19":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 270 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 270 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 135 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 135 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 135 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 135 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 270 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 270 } ], "baseFailTimes" : 4, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 19, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位19", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 370, "y" : 320 }
,"20":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 4, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 20, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位20", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 460, "y" : 340 }
,"21":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2090 } ], "baseFailTimes" : 4, "baseRate" : 0.6, "breakType" : "0", "grade" : 2, "id" : 21, "itemId" : "itemTemplate-51002", "itemNum" : 3, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位21", "rateModify" : 0.06, "serviceType" : "liantidan", "x" : 500, "y" : 260 }
,"22":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 24 }, { "class" : "all", "attr" : "hpMax", "value" : 1200 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 2, "id" : 22, "itemId" : "itemTemplate-51003", "itemNum" : 3, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位22", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 550, "y" : 300 }
,"23":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 480 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 23, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位23", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 100, "y" : 350 }
,"24":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1440 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 24, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位24", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 130, "y" : 280 }
,"25":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 20 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 25, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位25", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 200, "y" : 280 }
,"26":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 220 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 220 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 110 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 110 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 110 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 110 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 220 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 220 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 26, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位26", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 230, "y" : 210 }
,"27":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 220 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 27, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位27", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 270, "y" : 180 }
,"28":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 220 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 28, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位28", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 322, "y" : 230 }
,"29":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 70 } ], "baseFailTimes" : 5, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 29, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位29", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 350, "y" : 330 }
,"30":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 80 } ], "baseFailTimes" : 6, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 30, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位30", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 390, "y" : 260 }
,"31":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 280 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 280 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 140 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 140 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 140 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 140 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 280 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 280 } ], "baseFailTimes" : 6, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 31, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位31", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 420, "y" : 200 }
,"32":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2020 } ], "baseFailTimes" : 6, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 32, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位32", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 497, "y" : 287 }
,"33":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 6, "baseRate" : 0.5, "breakType" : "0", "grade" : 3, "id" : 33, "itemId" : "itemTemplate-51002", "itemNum" : 8, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位33", "rateModify" : 0.05, "serviceType" : "liantidan", "x" : 520, "y" : 220 }
,"34":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 27 }, { "class" : "all", "attr" : "hpMax", "value" : 1350 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 3, "id" : 34, "itemId" : "itemTemplate-51003", "itemNum" : 8, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位34", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 580, "y" : 210 }
,"35":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 240 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 35, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位35", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 100, "y" : 170 }
,"36":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 240 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 36, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位36", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 165, "y" : 154 }
,"37":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 70 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 37, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位37", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 188, "y" : 225 }
,"38":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 70 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 38, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位38", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 275, "y" : 201 }
,"39":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 240 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 240 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 120 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 120 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 120 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 120 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 240 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 240 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 39, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位39", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 230, "y" : 302 }
,"40":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1560 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 40, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位40", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 280, "y" : 360 }
,"41":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 20 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 41, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位41", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 382, "y" : 347 }
,"42":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 80 } ], "baseFailTimes" : 7, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 42, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位42", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 348, "y" : 250 }
,"43":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 80 } ], "baseFailTimes" : 8, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 43, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位43", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 390, "y" : 194 }
,"44":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 310 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 310 } ], "baseFailTimes" : 8, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 44, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位44", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 430, "y" : 282 }
,"45":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2180 } ], "baseFailTimes" : 8, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 45, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位45", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 520, "y" : 215 }
,"46":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 } ], "baseFailTimes" : 8, "baseRate" : 0.4, "breakType" : "0", "grade" : 4, "id" : 46, "itemId" : "itemTemplate-51002", "itemNum" : 15, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位46", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 530, "y" : 282 }
,"47":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 }, { "class" : "all", "attr" : "hpMax", "value" : 1500 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 4, "id" : 47, "itemId" : "itemTemplate-51003", "itemNum" : 15, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位47", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 590, "y" : 280 }
,"48":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1720 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 48, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位48", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 100, "y" : 175 }
,"49":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 570 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 49, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位49", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 155, "y" : 190 }
,"50":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 260 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 50, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位50", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 130, "y" : 260 }
,"51":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 260 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 51, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位51", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 230, "y" : 230 }
,"52":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 52, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位52", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 205, "y" : 310 }
,"53":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 260 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 260 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 130 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 130 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 130 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 130 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 260 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 260 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 53, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位53", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 330, "y" : 340 }
,"54":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 260 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 54, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位54", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 280, "y" : 280 }
,"55":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 260 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 55, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位55", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 310, "y" : 220 }
,"56":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 90 } ], "baseFailTimes" : 8, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 56, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位56", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 375, "y" : 210 }
,"57":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 90 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 57, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位57", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 390, "y" : 270 }
,"58":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 340 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 340 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 170 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 170 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 340 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 340 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 58, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位58", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 445, "y" : 230 }
,"59":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2410 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 59, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位59", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 530, "y" : 250 }
,"60":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 5, "id" : 60, "itemId" : "itemTemplate-51002", "itemNum" : 30, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位60", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 500, "y" : 200 }
,"61":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 33 }, { "class" : "all", "attr" : "hpMax", "value" : 1650 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 5, "id" : 61, "itemId" : "itemTemplate-51003", "itemNum" : 30, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位61", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 560, "y" : 190 }
,"62":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 290 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 290 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 145 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 145 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 145 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 145 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 290 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 62, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位62", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 120, "y" : 280 }
,"63":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 63, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位63", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 150, "y" : 200 }
,"64":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 64, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位64", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 210, "y" : 170 }
,"65":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 1930 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 65, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位65", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 280, "y" : 220 }
,"66":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 66, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位66", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 220, "y" : 270 }
,"67":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 290 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 290 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 145 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 145 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 145 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 145 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 290 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 67, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位67", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 240, "y" : 320 }
,"68":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 68, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位68", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 320, "y" : 350 }
,"69":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 290 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 69, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位69", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 350, "y" : 270 }
,"70":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 320 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 320 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 160 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 160 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 160 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 160 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 320 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 320 } ], "baseFailTimes" : 9, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 70, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位70", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 430, "y" : 350 }
,"71":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 110 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 71, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位71", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 460, "y" : 250 }
,"72":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 110 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 72, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位72", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 380, "y" : 200 }
,"73":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2700 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 73, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位73", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 480, "y" : 160 }
,"74":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 6, "id" : 74, "itemId" : "itemTemplate-51002", "itemNum" : 50, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位74", "rateModify" : 0.04, "serviceType" : "liantidan", "x" : 550, "y" : 200 }
,"75":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 36 }, { "class" : "all", "attr" : "hpMax", "value" : 1800 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 6, "id" : 75, "itemId" : "itemTemplate-51003", "itemNum" : 50, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位75", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 530, "y" : 250 }
,"76":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2000 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 76, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位76", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 100, "y" : 250 }
,"77":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 300 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 77, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位77", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 150, "y" : 280 }
,"78":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 300 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 78, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位78", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 120, "y" : 200 }
,"79":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 670 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 79, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位79", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 160, "y" : 150 }
,"80":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 80, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位80", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 200, "y" : 267 }
,"81":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 300 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 300 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 150 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 150 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 150 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 150 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 300 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 300 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 81, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位81", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 280, "y" : 344 }
,"82":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 90 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 82, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位82", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 250, "y" : 250 }
,"83":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 90 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 83, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位83", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 280, "y" : 160 }
,"84":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 84, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位84", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 359, "y" : 170 }
,"85":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2200 } ], "baseFailTimes" : 10, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 85, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位85", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 370, "y" : 247 }
,"86":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 360 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 360 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 180 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 180 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 180 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 180 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 360 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 360 } ], "baseFailTimes" : 11, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 86, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位86", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 430, "y" : 180 }
,"87":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 870 } ], "baseFailTimes" : 11, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 87, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位87", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 510, "y" : 237 }
,"88":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 130 } ], "baseFailTimes" : 11, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 88, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位88", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 470, "y" : 305 }
,"89":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 140 } ], "baseFailTimes" : 11, "baseRate" : 0.5, "breakType" : "0", "grade" : 7, "id" : 89, "itemId" : "itemTemplate-51002", "itemNum" : 70, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位89", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 530, "y" : 340 }
,"90":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 }, { "class" : "all", "attr" : "hpMax", "value" : 2000 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 7, "id" : 90, "itemId" : "itemTemplate-51003", "itemNum" : 70, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位90", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 450, "y" : 370 }
,"91":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 690 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 91, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位91", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 50, "y" : 180 }
,"92":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 92, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位92", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 150, "y" : 160 }
,"93":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 93, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位93", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 130, "y" : 250 }
,"94":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2060 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 94, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位94", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 180, "y" : 250 }
,"95":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 95, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位95", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 250, "y" : 200 }
,"96":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 310 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 96, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位96", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 200, "y" : 300 }
,"97":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 97, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位97", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 300, "y" : 340 }
,"98":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 98, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位98", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 279, "y" : 250 }
,"99":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 310 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 155 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 155 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 310 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 310 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 99, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位99", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 365, "y" : 270 }
,"100":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2060 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 100, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位100", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 350, "y" : 200 }
,"101":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 340 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 340 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 170 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 170 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 170 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 340 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 340 } ], "baseFailTimes" : 11, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 101, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位101", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 420, "y" : 160 }
,"102":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 102, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位102", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 480, "y" : 200 }
,"103":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 120 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 103, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位103", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 430, "y" : 280 }
,"104":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 130 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 104, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位104", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 460, "y" : 340 }
,"105":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 470 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 470 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 235 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 235 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 235 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 235 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 470 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 470 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 8, "id" : 105, "itemId" : "itemTemplate-51002", "itemNum" : 90, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位105", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 520, "y" : 280 }
,"106":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 44 }, { "class" : "all", "attr" : "hpMax", "value" : 2200 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 8, "id" : 106, "itemId" : "itemTemplate-51003", "itemNum" : 90, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位106", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 580, "y" : 320 }
,"107":{ "attrList" : [ { "class" : "all", "attr" : "mpMax", "value" : 730 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 107, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位107", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 70, "y" : 280 }
,"108":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 108, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位108", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 115, "y" : 200 }
,"109":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 109, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位109", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 150, "y" : 250 }
,"110":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2180 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 110, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位110", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 180, "y" : 160 }
,"111":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 111, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位111", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 200, "y" : 250 }
,"112":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 330 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 330 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 165 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 165 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 165 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 165 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 330 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 112, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位112", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 220, "y" : 320 }
,"113":{ "attrList" : [ { "class" : "all", "attr" : "phyDefence", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 113, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位113", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 250, "y" : 260 }
,"114":{ "attrList" : [ { "class" : "all", "attr" : "spellDefence", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 114, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位114", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 300, "y" : 230 }
,"115":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 330 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 330 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 165 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 165 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 165 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 165 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 330 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 330 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 115, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位115", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 360, "y" : 290 }
,"116":{ "attrList" : [ { "class" : "all", "attr" : "hpMax", "value" : 2180 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 116, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位116", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 370, "y" : 210 }
,"117":{ "attrList" : [ { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 360 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 360 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 180 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 180 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 180 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 180 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 360 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 360 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 117, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位117", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 420, "y" : 170 }
,"118":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 40 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 118, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位118", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 460, "y" : 250 }
,"119":{ "attrList" : [ { "class" : "all", "attr" : "criticalResist", "value" : 130 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 119, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位119", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 380, "y" : 350 }
,"120":{ "attrList" : [ { "class" : "all", "attr" : "criticalRating", "value" : 140 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 120, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位120", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 530, "y" : 370 }
,"121":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 50 } ], "baseFailTimes" : 12, "baseRate" : 0.4, "breakType" : "0", "grade" : 9, "id" : 121, "itemId" : "itemTemplate-51002", "itemNum" : 120, "maxProgress" : 0, "minProgress" : 0, "name" : "穴位121", "rateModify" : 0.035, "serviceType" : "liantidan", "x" : 520, "y" : 280 }
,"122":{ "attrList" : [ { "class" : "all", "attr" : "baseDamage", "value" : 50 }, { "class" : "all", "attr" : "hpMax", "value" : 2500 } ], "baseFailTimes" : 0, "baseRate" : 0, "breakType" : "1", "grade" : 9, "id" : 122, "itemId" : "itemTemplate-51003", "itemNum" : 120, "maxProgress" : 1500, "minProgress" : 500, "name" : "穴位122", "rateModify" : 0, "serviceType" : "jinghuadan", "x" : 460, "y" : 320 }
};

		}
	}
}