package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class jadejarBook extends MovieClip
	{
		public var configData:Object = null;

		public function jadejarBook()
		{
			Security.allowDomain('*');

			configData = 

{"y-1":{ "appearance" : "yujingping1jie", "attrList" : [], "descOpen" : "玉净瓶升至1阶松绿天青瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>松绿天青瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至1阶松绿天青瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如蓬莱仙山松绿翡翠，物华天宝，流光溢彩，散发天地万物灵气。</font>", "icon" : "image/icon/item/yujingping1_32.png", "id" : "y-1", "imgClose" : "image/ui/yujingping/tujiansuo1.png", "imgOpen" : "image/ui/yujingping/tujian1.png", "imgShow" : "image/swf/yujingping/1jie.swf", "name" : "松绿天青瓶", "worth" : 0 }
,"y-10":{ "appearance" : "yujingping5ji", "attrList" : [], "descOpen" : "玉净瓶升至10阶龙雀澄影樽可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>龙雀澄影樽</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至10阶龙雀澄影樽可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如上古神兵大夏龙雀，金身澄影，霞光如画，灵韵封印六界妖邪。</font>", "icon" : "image/icon/item/yujingping10_32.png", "id" : "y-10", "imgClose" : "image/ui/yujingping/tujiansuo10.png", "imgOpen" : "image/ui/yujingping/tujian10.png", "imgShow" : "image/swf/yujingping/10jie.swf", "name" : "龙雀澄影樽", "worth" : 0 }
,"y-11":{ "appearance" : "yujingping6ji", "attrList" : [], "descOpen" : "玉净瓶升至11阶绛云离火盏可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>绛云离火盏</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至11阶绛云离火盏可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如星君神殿绛云离火，飞雯化绡，落霞成绮，彤云惊绝九重青天。</font>", "icon" : "image/icon/item/yujingping11_32.png", "id" : "y-11", "imgClose" : "image/ui/yujingping/tujiansuo11.png", "imgOpen" : "image/ui/yujingping/tujian11.png", "imgShow" : "image/swf/yujingping/11jie.swf", "name" : "绛云离火盏", "worth" : 0 }
,"y-12":{ "appearance" : "yujingping7jie", "attrList" : [], "descOpen" : "玉净瓶升至12阶寒魄琉璃樽可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>寒魄琉璃樽</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至12阶寒魄琉璃樽可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如寒山天池望舒月轮，净月琉璃，寒魄若雪，凝霜封印千载冰魂。</font>", "icon" : "image/icon/item/yujingping12_32.png", "id" : "y-12", "imgClose" : "image/ui/yujingping/tujiansuo12.png", "imgOpen" : "image/ui/yujingping/tujian12.png", "imgShow" : "image/swf/yujingping/12jie.swf", "name" : "寒魄琉璃樽", "worth" : 0 }
,"y-13":{ "appearance" : "yujingping8jie", "attrList" : [], "descOpen" : "玉净瓶升至13阶炽焰焚心盏可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>炽焰焚心盏</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至13阶炽焰焚心盏可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如天光璀璨羲和炽焰，焚心以火，怒焱擎天，烈焰吞噬百万邪灵。</font>", "icon" : "image/icon/item/yujingping13_32.png", "id" : "y-13", "imgClose" : "image/ui/yujingping/tujiansuo13.png", "imgOpen" : "image/ui/yujingping/tujian13.png", "imgShow" : "image/swf/yujingping/13jie.swf", "name" : "炽焰焚心盏", "worth" : 0 }
,"y-14":{ "appearance" : "yujingping9jie", "attrList" : [], "descOpen" : "玉净瓶升至14阶五彩仙光瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>五彩仙光瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至14阶五彩仙光瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如九天玄女无缝天衣，五彩翎羽，仙光萦绕，返璞归真逐至太平。</font>", "icon" : "image/icon/item/yujingping14_32.png", "id" : "y-14", "imgClose" : "image/ui/yujingping/tujiansuo14.png", "imgOpen" : "image/ui/yujingping/tujian14.png", "imgShow" : "image/swf/yujingping/14jie.swf", "name" : "五彩仙光瓶", "worth" : 0 }
,"y-15":{ "appearance" : "yujingping10jie", "attrList" : [], "descOpen" : "玉净瓶升至15阶金龙逐日瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>金龙逐日瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至15阶金龙逐日瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如东海金龙飞驰逐日，仙韵漫天，灵气遍地，天地万物任心纵横。</font>", "icon" : "image/icon/item/yujingping15_32.png", "id" : "y-15", "imgClose" : "image/ui/yujingping/tujiansuo15.png", "imgOpen" : "image/ui/yujingping/tujian15.png", "imgShow" : "image/swf/yujingping/15jie.swf", "name" : "金龙逐日瓶", "worth" : 0 }
,"y-2":{ "appearance" : "yujingping1jie2ji", "attrList" : [], "descOpen" : "玉净瓶升至2阶碧绮翠毓壶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>碧绮翠毓壶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至2阶碧绮翠毓壶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如王母瑶池凝碧翠玉，秦桑绿绮，浮翠流丹，所见之人心生清净。</font>", "icon" : "image/icon/item/yujingping2_32.png", "id" : "y-2", "imgClose" : "image/ui/yujingping/tujiansuo2.png", "imgOpen" : "image/ui/yujingping/tujian2.png", "imgShow" : "image/swf/yujingping/2jie.swf", "name" : "碧绮翠毓壶", "worth" : 0 }
,"y-3":{ "appearance" : "yujingping1jie3ji", "attrList" : [], "descOpen" : "玉净瓶升至3阶晴岚云苍瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>晴岚云苍瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至3阶晴岚云苍瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如出水洛神晴岚羽衣，一碧千里，净无瑕秽，摒除一切五浊之气。</font>", "icon" : "image/icon/item/yujingping3_32.png", "id" : "y-3", "imgClose" : "image/ui/yujingping/tujiansuo3.png", "imgOpen" : "image/ui/yujingping/tujian3.png", "imgShow" : "image/swf/yujingping/3jie.swf", "name" : "晴岚云苍瓶", "worth" : 0 }
,"y-4":{ "appearance" : "yujingping2jie1ji", "attrList" : [], "descOpen" : "玉净瓶升至4阶青金黛月樽可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>青金黛月樽</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至4阶青金黛月樽可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如冷月蟾宫青黛墨玉，霜若寒江，灿若天星，隐隐散发天辰星光。</font>", "icon" : "image/icon/item/yujingping4_32.png", "id" : "y-4", "imgClose" : "image/ui/yujingping/tujiansuo4.png", "imgOpen" : "image/ui/yujingping/tujian4.png", "imgShow" : "image/swf/yujingping/4jie.swf", "name" : "青金黛月樽", "worth" : 0 }
,"y-5":{ "appearance" : "yujingping2jie2ji", "attrList" : [], "descOpen" : "玉净瓶升至5阶净云澜夜盏可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>净云澜夜盏</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至5阶净云澜夜盏可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如巫山神女七纱羽衣，秋澜点翠，氤氲烟起，吸纳百川水蕴瑶光。</font>", "icon" : "image/icon/item/yujingping5_32.png", "id" : "y-5", "imgClose" : "image/ui/yujingping/tujiansuo5.png", "imgOpen" : "image/ui/yujingping/tujian5.png", "imgShow" : "image/swf/yujingping/5jie.swf", "name" : "净云澜夜盏", "worth" : 0 }
,"y-6":{ "appearance" : "yujingping3jie1ji", "attrList" : [], "descOpen" : "玉净瓶升至6阶幻天凝碧壶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>幻天凝碧壶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至6阶幻天凝碧壶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如神将出云幻剑惊天，身若天苍，形若湛海，飘渺灵气挥洒九州。</font>", "icon" : "image/icon/item/yujingping6_32.png", "id" : "y-6", "imgClose" : "image/ui/yujingping/tujiansuo6.png", "imgOpen" : "image/ui/yujingping/tujian6.png", "imgShow" : "image/swf/yujingping/6jie.swf", "name" : "幻天凝碧壶", "worth" : 0 }
,"y-7":{ "appearance" : "yujingping3jie2ji", "attrList" : [], "descOpen" : "玉净瓶升至7阶紫玉耀月瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>紫玉耀月瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至7阶紫玉耀月瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如兜率天宫紫霞耀月，玉叶金柯，紫霄凌云，仙风神韵倾泻万里。</font>", "icon" : "image/icon/item/yujingping7_32.png", "id" : "y-7", "imgClose" : "image/ui/yujingping/tujiansuo7.png", "imgOpen" : "image/ui/yujingping/tujian7.png", "imgShow" : "image/swf/yujingping/7jie.swf", "name" : "紫玉耀月瓶", "worth" : 0 }
,"y-8":{ "appearance" : "yujingping4jie1ji", "attrList" : [], "descOpen" : "玉净瓶升至8阶御风青莲盏可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>御风青莲盏</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至8阶御风青莲盏可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如云裳仙子画堂青莲，莲心化雾，凭虚御风，仙露浸染十方净土。</font>", "icon" : "image/icon/item/yujingping8_32.png", "id" : "y-8", "imgClose" : "image/ui/yujingping/tujiansuo8.png", "imgOpen" : "image/ui/yujingping/tujian8.png", "imgShow" : "image/swf/yujingping/8jie.swf", "name" : "御风青莲盏", "worth" : 0 }
,"y-9":{ "appearance" : "yujingping4jie2ji", "attrList" : [], "descOpen" : "玉净瓶升至9阶玄梦弑魂瓶可获得此外形", "description" : "<font size='12' color='#00FFFF'><font size='16' color='#FFFF00'><b>玄梦弑魂瓶</b></font>\n<font color='#00FF00'>激活条件：</font>\n　玉净瓶升至9阶玄梦弑魂瓶可获得此外形。\n<font color='#00FF00'>图鉴描述：</font>\n　如玄梦天尊弑魂双刃，临风御灵，天地肃杀，化魑魅魍魉于无形。</font>", "icon" : "image/icon/item/yujingping9_32.png", "id" : "y-9", "imgClose" : "image/ui/yujingping/tujiansuo9.png", "imgOpen" : "image/ui/yujingping/tujian9.png", "imgShow" : "image/swf/yujingping/9jie.swf", "name" : "玄梦弑魂瓶", "worth" : 0 }
};

		}
	}
}