package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class logingifts extends MovieClip
	{
		public var configData:Object = null;

		public function logingifts()
		{
			Security.allowDomain('*');

			configData = 

{"gift-01001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9027", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "随机获得绑定钱币10金、传送符补充包*1、仙灵丹*1、仙符宝箱*1、八卦图*10", "giftId" : "gift-01001", "name" : "蓝钻每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9116", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-120554", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-9117", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-120555", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-9118", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-120556", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-9119", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "连续登录领取奖品", "giftId" : "gift-01002", "name" : "蓝钻连续登录奖励", "privilegeLevelLimit" : -1, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01003":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50217", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*4、修理锤*2", "giftId" : "gift-01003", "name" : "蓝钻1级每日礼包", "privilegeLevelLimit" : 1, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01004":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50218", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3", "giftId" : "gift-01004", "name" : "蓝钻2级每日礼包", "privilegeLevelLimit" : 2, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01005":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50219", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*1", "giftId" : "gift-01005", "name" : "蓝钻3级每日礼包", "privilegeLevelLimit" : 3, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01006":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50220", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2", "giftId" : "gift-01006", "name" : "蓝钻4级每日礼包", "privilegeLevelLimit" : 4, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01007":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50221", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*1", "giftId" : "gift-01007", "name" : "蓝钻5级每日礼包", "privilegeLevelLimit" : 5, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01008":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50222", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*2", "giftId" : "gift-01008", "name" : "蓝钻6级每日礼包", "privilegeLevelLimit" : 6, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01009":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50223", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得洗炼石*1、坐骑资质丹*2", "giftId" : "gift-01009", "name" : "蓝钻年费每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "blue", "privilegeValue" : 2, "sFrom" : [ "qqgame", "3366" ] }
,"gift-01010":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120323", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*3", "giftId" : "gift-01010", "name" : "蓝钻7级每日礼包", "privilegeLevelLimit" : 7, "privilegeName" : "blue", "privilegeValue" : 1, "sFrom" : [ "qqgame", "3366" ] }
,"gift-02001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9072", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "随机获得绑定钱币10金、传送符补充包*1、仙灵丹*1、仙符宝箱*1、八卦图*10", "giftId" : "gift-02001", "name" : "3366登录日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "3366" ] }
,"gift-02002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-3449", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-3494", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-203", "count" : 3, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-170", "count" : 2, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-149", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-43086", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-143", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从3366网站连续登录可领取奖品", "giftId" : "gift-02002", "name" : "3366连续登陆奖励", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "3366" ] }
,"gift-03001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9071", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "随机获得绑定钱币10金、传送符补充包*1、仙灵丹*1、仙符宝箱*1、八卦图*10", "giftId" : "gift-03001", "name" : "QQ游戏大厅每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "qqgame" ] }
,"gift-03002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9120", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-120551", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-9121", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-120552", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-9122", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-120553", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-9123", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从QQ游戏大厅连续登录可领取奖品", "giftId" : "gift-03002", "name" : "QQ游戏大厅连续登录奖励", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "qqgame" ] }
,"gift-04002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9223", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*4、修理锤*2", "giftId" : "gift-04002", "name" : "黄钻1级每日礼包", "privilegeLevelLimit" : 1, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04003":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9224", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3", "giftId" : "gift-04003", "name" : "黄钻2级每日礼包", "privilegeLevelLimit" : 2, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04004":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9225", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*1", "giftId" : "gift-04004", "name" : "黄钻3级每日礼包", "privilegeLevelLimit" : 3, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04005":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9226", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2", "giftId" : "gift-04005", "name" : "黄钻4级每日礼包", "privilegeLevelLimit" : 4, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04006":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9227", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*1", "giftId" : "gift-04006", "name" : "黄钻5级每日礼包", "privilegeLevelLimit" : 5, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04007":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9228", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*2", "giftId" : "gift-04007", "name" : "黄钻6级每日礼包", "privilegeLevelLimit" : 6, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04008":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9229", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*3", "giftId" : "gift-04008", "name" : "黄钻7级每日礼包", "privilegeLevelLimit" : 7, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04009":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9230", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得洗练石*1，坐骑资质丹*2", "giftId" : "gift-04009", "name" : "黄钻年费每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "yellow", "privilegeValue" : 2, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04010":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-9229", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "可获得八卦图*6、修理锤*3、幻化晶石*2、三阶强化石*3", "giftId" : "gift-04010", "name" : "黄钻8级每日礼包", "privilegeLevelLimit" : 8, "privilegeName" : "yellow", "privilegeValue" : 1, "sFrom" : [ "qzone", "xiaoyou", "box" ] }
,"gift-04011":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-3449", "count" : 10, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-3494", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-8964", "count" : 3, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-43086", "count" : 3, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-149", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-43037", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-43120", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从Qzone连续登录可领取奖品", "giftId" : "gift-04011", "name" : "QQ空间连续登录奖励", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "qzone" ] }
,"gift-04012":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-3449", "count" : 10, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-3494", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-8964", "count" : 3, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-43086", "count" : 3, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-149", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-43037", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-43120", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从朋友网连续登录可领取奖品", "giftId" : "gift-04012", "name" : "QQ朋友连续登录奖励", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "xiaoyou" ] }
,"gift-04013":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-3449", "count" : 10, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 2, "itemId" : "itemTemplate-50526", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-3494", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 4, "itemId" : "itemTemplate-149", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-50978", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 6, "itemId" : "itemTemplate-43037", "count" : 5, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-50809", "count" : 10, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从游戏盒子连续登录可领取奖品", "giftId" : "gift-04013", "name" : "盒子连续登陆奖励", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "box" ] }
,"gift-05001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-203", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 3, "itemId" : "itemTemplate-6123", "count" : 20, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 5, "itemId" : "itemTemplate-178", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" }, { "dayNum" : 7, "itemId" : "itemTemplate-9115", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从官网连续登录可领取奖品", "giftId" : "gift-05001", "name" : "QQ九仙连续登录礼包", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "website" ] }
,"gift-06001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50051", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "从Qplus登录每日都可领取该礼包。打开可获得八卦图*10、幻化晶石*3、修理锤*5。", "giftId" : "gift-06001", "name" : "Q+每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-07001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-50387", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "随机获得下列物品中一种：八卦图*5、坐骑资质丹*1、幻化晶石*1、狂暴药剂*1、双倍灵气丹*1", "giftId" : "gift-07001", "name" : "QQ会员每日礼包", "privilegeLevelLimit" : -1, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120332", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日1级礼包", "giftId" : "gift-07002", "name" : "QQ会员每日1级礼包", "privilegeLevelLimit" : 1, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07003":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120333", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日2级礼包", "giftId" : "gift-07003", "name" : "QQ会员每日2级礼包", "privilegeLevelLimit" : 2, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07004":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120334", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日3级礼包", "giftId" : "gift-07004", "name" : "QQ会员每日3级礼包", "privilegeLevelLimit" : 3, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07005":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120335", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日4级礼包", "giftId" : "gift-07005", "name" : "QQ会员每日4级礼包", "privilegeLevelLimit" : 4, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07006":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120336", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日5级礼包", "giftId" : "gift-07006", "name" : "QQ会员每日5级礼包", "privilegeLevelLimit" : 5, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07007":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120337", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日6级礼包", "giftId" : "gift-07007", "name" : "QQ会员每日6级礼包", "privilegeLevelLimit" : 6, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07008":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120338", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "QQ会员每日7级礼包", "giftId" : "gift-07008", "name" : "QQ会员每日7级礼包", "privilegeLevelLimit" : 7, "privilegeName" : "vip", "privilegeValue" : 1, "sFrom" : [ "qqvip" ] }
,"gift-07009":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120339", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "年费会员额外礼包", "giftId" : "gift-07009", "name" : "年费会员额外礼包", "privilegeLevelLimit" : -1, "privilegeName" : "vip", "privilegeValue" : 2, "sFrom" : [ "qqvip" ] }
,"gift-15001":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120087", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*10、修理锤*6、幻化晶石*3", "giftId" : "gift-15001", "name" : "Q+每日1级礼包", "privilegeLevelLimit" : 1, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15002":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120088", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*3", "giftId" : "gift-15002", "name" : "Q+每日2级礼包", "privilegeLevelLimit" : 2, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15003":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120089", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4", "giftId" : "gift-15003", "name" : "Q+每日3级礼包", "privilegeLevelLimit" : 3, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15004":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120090", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4、坐骑资质丹*1", "giftId" : "gift-15004", "name" : "Q+每日4级礼包", "privilegeLevelLimit" : 4, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15005":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120091", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4、坐骑资质丹*2", "giftId" : "gift-15005", "name" : "Q+每日5级礼包", "privilegeLevelLimit" : 5, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15006":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120092", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4、坐骑资质丹*3", "giftId" : "gift-15006", "name" : "Q+每日6级礼包", "privilegeLevelLimit" : 6, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15007":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120093", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4、坐骑资质丹*4", "giftId" : "gift-15007", "name" : "Q+每日7级礼包", "privilegeLevelLimit" : 7, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15008":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120094", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "礼包中包含八卦图*12、修理锤*6、幻化晶石*4、坐骑资质丹*5", "giftId" : "gift-15008", "name" : "Q+每日8级礼包", "privilegeLevelLimit" : 8, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
,"gift-15009":{ "bonus" : [ { "dayNum" : 1, "itemId" : "itemTemplate-120086", "count" : 1, "quality" : "", "bound" : 1, "class" : "", "runeSlotMax" : "" } ], "description" : "Q+每日0级礼包包含八卦图*6、修理锤*3、幻化晶石*1", "giftId" : "gift-15009", "name" : "Q+每日0级礼包", "privilegeLevelLimit" : 0, "privilegeName" : "qplus", "privilegeValue" : 0, "sFrom" : [ "qplus" ] }
};

		}
	}
}