package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class mwquality extends MovieClip
	{
		public var configData:Object = null;

		public function mwquality()
		{
			Security.allowDomain('*');

			configData = 

{"1":{ "baseFailTimes" : 0, "baseRate" : 0, "color" : "ffffff", "fixRate" : 0, "intelligenceList" : [ { "name" : "生命资质", "value" : 60, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 30, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 10, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 10, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 30, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 10, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "凡品", "qualityId" : 1, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 0 }
,"2":{ "baseFailTimes" : 0, "baseRate" : 1, "color" : "ffffff", "fixRate" : 0.01, "intelligenceList" : [ { "name" : "生命资质", "value" : 67, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 40, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 13, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 20, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 40, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 20, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "良品", "qualityId" : 2, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 1 }
,"3":{ "baseFailTimes" : 3, "baseRate" : 0.5, "color" : "ffffff", "fixRate" : 0.1, "intelligenceList" : [ { "name" : "生命资质", "value" : 100, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 60, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 30, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 30, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 50, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 30, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "优品", "qualityId" : 3, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 5 }
,"4":{ "baseFailTimes" : 5, "baseRate" : 0.3, "color" : "ffffff", "fixRate" : 0.1, "intelligenceList" : [ { "name" : "生命资质", "value" : 120, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 80, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 40, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 47, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 66, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 47, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "精品", "qualityId" : 4, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 10 }
,"5":{ "baseFailTimes" : 10, "baseRate" : 0.1, "color" : "00ff00", "fixRate" : 0.05, "intelligenceList" : [ { "name" : "生命资质", "value" : 160, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 120, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 60, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 80, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 100, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 80, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "稀品", "qualityId" : 5, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 25 }
,"6":{ "baseFailTimes" : 30, "baseRate" : 0.05, "color" : "00ff00", "fixRate" : 0.03, "intelligenceList" : [ { "name" : "生命资质", "value" : 240, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 180, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 120, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 120, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 120, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 120, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "珍品", "qualityId" : 6, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 50 }
,"7":{ "baseFailTimes" : 50, "baseRate" : 0.05, "color" : "3adcff", "fixRate" : 0.02, "intelligenceList" : [ { "name" : "生命资质", "value" : 320, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 240, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 160, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 160, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 160, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 160, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "极品", "qualityId" : 7, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 85 }
,"8":{ "baseFailTimes" : 60, "baseRate" : 0.03, "color" : "3adcff", "fixRate" : 0.02, "intelligenceList" : [ { "name" : "生命资质", "value" : 397, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 340, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 227, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 255, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 226, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 255, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "绝品", "qualityId" : 8, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 150 }
,"9":{ "baseFailTimes" : 70, "baseRate" : 0.03, "color" : "f157ff", "fixRate" : 0.02, "intelligenceList" : [ { "name" : "生命资质", "value" : 513, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 440, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 330, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 330, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 257, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 330, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "至尊", "qualityId" : 9, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 275 }
,"10":{ "baseFailTimes" : 80, "baseRate" : 0.01, "color" : "ff9900", "fixRate" : 0.01, "intelligenceList" : [ { "name" : "生命资质", "value" : 653, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 560, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 420, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 420, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 327, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 420, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "通灵", "qualityId" : 10, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 380 }
,"11":{ "baseFailTimes" : 100, "baseRate" : 0.01, "color" : "ecea64", "fixRate" : 0.01, "intelligenceList" : [ { "name" : "生命资质", "value" : 817, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "6" ] } ] }, { "name" : "法力资质", "value" : 700, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "7" ] } ] }, { "name" : "基础伤害资质", "value" : 525, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "10" ] } ] }, { "name" : "暴击资质", "value" : 525, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "19" ] } ] }, { "name" : "暴抗资质", "value" : 408, "worthRatio" : 1, "attrList" : [ { "class" : "", "list" : [ "20" ] } ] }, { "name" : "五行伤害资质", "value" : 525, "worthRatio" : 2, "attrList" : [ { "class" : "tianxiang", "list" : [ "25", "26" ] }, { "class" : "taishang", "list" : [ "25", "27" ] }, { "class" : "tianlong", "list" : [ "24", "26" ] }, { "class" : "jiuzhou", "list" : [ "24", "28" ] }, { "class" : "leiyin", "list" : [ "27", "28" ] }, { "class" : "yaochi", "list" : [ "24", "25", "26", "27", "28" ] } ] } ], "name" : "化神", "qualityId" : 11, "serviceType" : "fabaodzf", "upqualityItemId" : "itemTemplate-43143", "upqualityItemNum" : 500 }
};

		}
	}
}