package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class petShapeDict extends MovieClip
	{
		public var configData:Object = null;

		public function petShapeDict()
		{
			Security.allowDomain('*');

			configData = 

{"petshape-1":{ "addExp" : "", "appearance" : "xiantu1", "attackNonsense" : "兔子急了也会咬人哦！╭(╯3╰)╮\n怪物来了，主人你先上！", "description" : "萝卜村里，最会捣蛋的那个。", "direction" : 7, "elemental" : "metal", "name" : "乖乖兔（普通）", "nonsense" : "主人，顺顺毛。O(∩_∩)O~\n主人，你需要帮忙吗？\n小兔子乖乖，把门开开~\n呜呜呜……我昨天做梦，家里PM2.5超标了……\n主人猜猜我是雌是雄？", "page" : "1", "sFrom" : [], "serviceType" : "", "shapeAttrDictId" : "dict-100007", "shapeId" : "petshape-1", "shapeLevelDictId" : "dict-200010", "shapeType" : "normal", "superMoney" : "", "x" : "105", "y" : "100" }
,"petshape-10":{ "activateItemId" : "itemTemplate-51028", "addExp" : "10", "appearance" : "xiaoyaojing", "attackNonsense" : "竟然敢打姐，不迷死你，姐不活啦！", "description" : "1", "direction" : 0, "elemental" : "metal", "name" : "小妖精（神级）", "nonsense" : "这有个小妖精！边上的那个，嗯，啊，那个。。。。", "page" : "1", "sFrom" : [], "serviceType" : "xiaoyaojing", "shapeAttrDictId" : "dict-100011", "shapeId" : "petshape-10", "shapeLevelDictId" : "dict-200010", "shapeType" : "supernal", "x" : "360", "y" : "310" }
,"petshape-11":{ "activateItemId" : "itemTemplate-51030", "addExp" : "10", "appearance" : "xiaojiangshi", "attackNonsense" : "啊。。嘞。。哥身上就剩那么点油了，你还来！", "description" : "1", "direction" : 0, "elemental" : "fire", "name" : "小僵尸（神级）", "nonsense" : "你搓衣，我搓衣，大家都来搓搓衣！", "page" : "1", "sFrom" : [], "serviceType" : "xiaojiangshi", "shapeAttrDictId" : "dict-100011", "shapeId" : "petshape-11", "shapeLevelDictId" : "dict-200010", "shapeType" : "supernal", "x" : "205", "y" : "240" }
,"petshape-12":{ "activateItemId" : "itemTemplate-51049", "addExp" : "10", "appearance" : "gutoulong", "attackNonsense" : "天地不平一声吼，吼完转身我就走！\n看招！亢龙有悔！\n主人，你打怪，我打酱油！", "description" : "龙！真龙！来自幽冥界的神龙！", "direction" : 7, "elemental" : "fire", "name" : "龙千骨（神级）", "nonsense" : "呀拉索~那就是青~藏~高~噢噢噢啊啊啊啊~原\n主人，什么时候给我找只小龙女呢？\n我头上有犄角，我身后有尾巴......\n古老的东方有一群人，他们全都是我的传人。\n一万年前私自降雨的那条笨龙不是我！", "page" : "1", "sFrom" : [], "serviceType" : "gutoulong", "shapeAttrDictId" : "dict-100010", "shapeId" : "petshape-12", "shapeLevelDictId" : "dict-200010", "shapeType" : "supernal", "x" : "205", "y" : "350" }
,"petshape-13":{ "activateItemId" : "itemTemplate-51110", "addExp" : "10", "appearance" : "chongwutuzi", "attackNonsense" : "不耍你不知道什么叫狡兔三窟！\n看我神兔飞天！冲向月球！\n兔子不吃窝边草，不打你是不屑！", "description" : "来自九重天外的如意仙兔，具有飞天遁地的本领，将祥瑞带给每一个人。", "direction" : 0, "elemental" : "water", "name" : "月兔（神级）", "nonsense" : "静若处子，动如疯兔！不，脱兔！\n多年前赛跑我没有输给那只乌龟！\n你守着一棵树是在等我么？\n双兔傍地走，安能辨我是雌雄！\n请叫我兔爷~", "page" : "1", "sFrom" : [], "serviceType" : "cwyuetu", "shapeAttrDictId" : "dict-100008", "shapeId" : "petshape-13", "shapeLevelDictId" : "dict-200010", "shapeType" : "supernal", "x" : "320", "y" : "230" }
,"petshape-2":{ "addExp" : "10", "appearance" : "xianguolingyuan1", "attackNonsense" : "吃俺小孙一棒！↖(^ω^)↗\n金箍~棒打个棒打个棒~", "description" : "仙果灵源中机缘巧合中出生的仙果之灵。", "direction" : 1, "elemental" : "wood", "name" : "孙小圣（神级）", "nonsense" : "筋斗云，走起。~\\(≧▽≦)/~\n啦啦啦德玛西亚~\n曾经有一份真挚的爱情摆在我面前，可惜我忙着吃桃去了。", "page" : "1", "sFrom" : [], "serviceType" : "sunxiaosheng", "shapeAttrDictId" : "dict-100008", "shapeId" : "petshape-2", "shapeLevelDictId" : "dict-200011", "shapeType" : "normal", "superMoney" : "", "x" : "420", "y" : "200" }
,"petshape-3":{ "addExp" : "10", "appearance" : "songshu1", "attackNonsense" : "别碰我的榛子！(#‵′)凸\n坚果攻击！\n看，有灰机！", "description" : "出身上古大森林，喜爱在苍松翠柏中蹦跶。", "direction" : 1, "elemental" : "fire", "name" : "坚果（普通）", "nonsense" : "主人，种个榛子林吧。（¯﹃¯）\n亲爱的榛子，我们也来双修一下吧。\n主人，看我的平衡能力怎么样~", "page" : "1", "sFrom" : [], "serviceType" : "", "shapeAttrDictId" : "dict-100012", "shapeId" : "petshape-3", "shapeLevelDictId" : "dict-200011", "shapeType" : "normal", "superMoney" : "", "x" : "325", "y" : "95" }
,"petshape-4":{ "addExp" : "10", "appearance" : "shejing1", "attackNonsense" : "主人，保护我！o(>﹏<)o\n我们的祖先在忽悠着你~", "description" : "新年迎春它来报，金蛇贺喜笑开颜。", "direction" : 7, "elemental" : "water", "name" : "小夕（普通）", "nonsense" : "什么时候才能有主人的美貌呢？╭(╯^╰)╮\n不要叫我大王，要叫我女王大人！\n法海你不懂爱~雷峰塔它掉下来~主人你为什么捂耳朵？\n你不知道美女闭上眼睛，就是要你亲她吗？", "page" : "1", "sFrom" : [], "serviceType" : "", "shapeAttrDictId" : "dict-100013", "shapeId" : "petshape-4", "shapeLevelDictId" : "dict-200011", "shapeType" : "normal", "superMoney" : "", "x" : "75", "y" : "235" }
,"petshape-5":{ "activateItemId" : "", "addExp" : "10", "appearance" : "xiongmaoren1", "attackNonsense" : "看我灼热波动拳！(╰_╯)#\n为了部落！咦，我在说啥？", "description" : "国宝，国宝！", "direction" : 0, "elemental" : "earth", "name" : "京京（神级）", "nonsense" : "一起伸伸懒腰吧(*^o^*)\n有什么好吃的吗？我饿了……\n昨天做梦有只浣熊跟我抢包子，我一个也没吃着呜呜……\n主人我好累啊，你看我的黑眼圈多重。", "page" : "1", "sFrom" : [], "serviceType" : "jingjing", "shapeAttrDictId" : "dict-100011", "shapeId" : "petshape-5", "shapeLevelDictId" : "dict-200012", "shapeType" : "normal", "superMoney" : "", "x" : "215", "y" : "110" }
,"petshape-6":{ "addExp" : "10", "appearance" : "zhangyu", "attackNonsense" : "看我的360°全方位攻击！\n那个敌人看起来值得一战！\n可敬的对手，真让我感到荣耀！", "description" : "你猜得没错，我就是传说中的预言帝！", "direction" : 7, "elemental" : "wood", "name" : "保罗（神级）", "nonsense" : "曾经我也是名战士，直到我的膝盖中了一箭。\n圣光啊！你有看见那个敌人吗！\n眼前有个强大的敌手！", "page" : "1", "sFrom" : [], "serviceType" : "baoluo", "shapeAttrDictId" : "dict-100009", "shapeId" : "petshape-6", "shapeLevelDictId" : "dict-200011", "shapeType" : "normal", "x" : "55", "y" : "350" }
,"petshape-7":{ "addExp" : "10", "appearance" : "xueren", "attackNonsense" : "靠近我，冻死你。\n别想夺走我的礼帽！\n别让你那身老土的装扮，污了本座的法眼！\n你懂不懂什么叫fashion？\n颤抖吧，凡人！", "description" : "我是邪恶的大雪人！", "direction" : 1, "elemental" : "water", "name" : "凉心（神级）", "nonsense" : "偷偷告诉你，其实姜饼人是我亲戚。\n温室效应让我压力很大。\n我们雪人一直站在潮流的尖端。\n兔子，离我的鼻子远点！\n你以为这是灯笼，其实这是制冷器。\n你以为这是围巾，其实这是皮带。\n你以为这是帽子，其实这就是帽子。", "page" : "1", "sFrom" : [], "serviceType" : "liangxin", "shapeAttrDictId" : "dict-100010", "shapeId" : "petshape-7", "shapeLevelDictId" : "dict-200011", "shapeType" : "normal", "x" : "525", "y" : "270" }
,"petshape-8":{ "addExp" : "", "appearance" : "bulu", "attackNonsense" : "看我的布鲁光波！\n充能完毕，发动雷霆一击！\n能量护甲损耗，发动反击模式。", "description" : "蓝钻特权仙宠", "direction" : 0, "elemental" : "water", "name" : "布鲁", "nonsense" : "我是来自次世代的仙宠！\n我来自一个遥远的星系，那里有蔚蓝的天空和海洋。\n有机会一定带你到我的母星看看。\n主人，维持在这个星系很消耗能量，记得定时给我充能哦。", "page" : "1", "sFrom" : [ "qqgame", "3366" ], "serviceType" : "", "shapeAttrDictId" : "dict-100014", "shapeId" : "petshape-8", "shapeLevelDictId" : "dict-200014", "shapeType" : "normal", "x" : "1", "y" : "1" }
,"petshape-9":{ "addExp" : "", "appearance" : "xiongmaobaobao", "attackNonsense" : "别想欺负主人！\n卖萌一击~！\n你才看不到自己的脚趾头！\n打你，打你！\n拍你右脚丫！", "description" : "黄钻特权仙宠", "direction" : 0, "elemental" : "fire", "name" : "熊猫宝宝", "nonsense" : "主人，请你吃竹zhi~~\n我的梦想就是拍一张彩色照片~~\n我是宝宝~\n主人，记得定时给宝宝喂竹子，不然宝宝就离家出走！\n妈妈说宝宝的翅膀是真的能飞呢！\n能坐着绝不站着，能躺着绝不坐着！这才是喵生啊~~", "page" : "1", "sFrom" : [ "qzone", "xiaoyou", "box" ], "serviceType" : "", "shapeAttrDictId" : "dict-100014", "shapeId" : "petshape-9", "shapeLevelDictId" : "dict-200014", "shapeType" : "normal", "x" : "1", "y" : "1" }
};

		}
	}
}