package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class souls extends MovieClip
	{
		public var configData:Object = null;

		public function souls()
		{
			Security.allowDomain('*');

			configData = 

{"SoulTemplate-0001":{ "baseExp" : 3, "defaultPropertyId" : 10, "expReqDictId" : "dict-000015", "icon" : "image/icon/yaohe/2_3.png", "kind" : 2, "name" : "应龙妖将", "price" : 30, "propertyList" : [ { "id" : 10, "class" : "leiyin" }, { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000046", "quality" : 3, "soulId" : "SoulTemplate-0001", "type" : 1 }
,"SoulTemplate-0002":{ "baseExp" : 3, "defaultPropertyId" : 13, "expReqDictId" : "dict-000015", "icon" : "image/icon/yaohe/1_3.png", "kind" : 3, "name" : "白虎妖将", "price" : 30, "propertyList" : [ { "id" : 13, "class" : "tianxiang" }, { "id" : 13, "class" : "tianlong" }, { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "yaochi" }, { "id" : 13, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000052", "quality" : 3, "soulId" : "SoulTemplate-0002", "type" : 1 }
,"SoulTemplate-0003":{ "baseExp" : 3, "defaultPropertyId" : 14, "expReqDictId" : "dict-000015", "icon" : "image/icon/yaohe/2_3.png", "kind" : 4, "name" : "青鸾妖将", "price" : 30, "propertyList" : [ { "id" : 14, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "tianlong" }, { "id" : 14, "class" : "yaochi" }, { "id" : 13, "class" : "leiyin" }, { "id" : 13, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000052", "quality" : 3, "soulId" : "SoulTemplate-0003", "type" : 1 }
,"SoulTemplate-0004":{ "baseExp" : 0, "defaultPropertyId" : 0, "expReqDictId" : "", "icon" : "image/icon/yaohe/canhun.png", "kind" : 0, "name" : "残核", "price" : 25, "propertyList" : [], "propertyValueDictId" : "", "quality" : 1, "soulId" : "SoulTemplate-0004", "type" : 3 }
,"SoulTemplate-0005":{ "baseExp" : 0, "defaultPropertyId" : 0, "expReqDictId" : "", "icon" : "image/icon/yaohe/yaohesuipian.png", "kind" : 0, "name" : "妖核碎片", "price" : 100, "propertyList" : [], "propertyValueDictId" : "", "quality" : 2, "soulId" : "SoulTemplate-0005", "type" : 4 }
,"SoulTemplate-0006":{ "baseExp" : 200, "defaultPropertyId" : 2, "expReqDictId" : "", "icon" : "image/icon/yaohe/hundun.png", "kind" : 3, "name" : "混沌", "price" : 200, "propertyList" : [], "propertyValueDictId" : "", "quality" : 2, "soulId" : "SoulTemplate-0006", "type" : 2 }
,"SoulTemplate-0009":{ "baseExp" : 3, "defaultPropertyId" : 11, "description" : "", "expReqDictId" : "dict-000015", "icon" : "image/icon/yaohe/1_3.png", "kind" : 15, "name" : "烛龙妖将", "price" : 30, "propertyList" : [ { "id" : 11, "class" : "tianxiang" }, { "id" : 11, "class" : "tianlong" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 11, "class" : "leiyin" }, { "id" : 12, "class" : "yaochi" }, { "id" : 12, "class" : "taishang" } ], "propertyValueDictId" : "dict-000050", "quality" : 3, "soulId" : "SoulTemplate-0009", "type" : 1 }
,"SoulTemplate-0010":{ "baseExp" : 3, "defaultPropertyId" : 12, "description" : "", "expReqDictId" : "dict-000015", "icon" : "image/icon/yaohe/2_3.png", "kind" : 16, "name" : "蛊雕妖将", "price" : 30, "propertyList" : [ { "id" : 12, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "tianlong" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "leiyin" }, { "id" : 11, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000050", "quality" : 3, "soulId" : "SoulTemplate-0010", "type" : 1 }
,"SoulTemplate-0011":{ "baseExp" : 8, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/1_4.png", "kind" : 1, "name" : "金乌妖帅", "price" : 60, "propertyList" : [ { "id" : 10, "class" : "leiyin" }, { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000047", "quality" : 4, "soulId" : "SoulTemplate-0011", "type" : 1 }
,"SoulTemplate-0012":{ "baseExp" : 8, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 2, "name" : "应龙妖帅", "price" : 60, "propertyList" : [ { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000048", "quality" : 4, "soulId" : "SoulTemplate-0012", "type" : 1 }
,"SoulTemplate-0013":{ "baseExp" : 8, "defaultPropertyId" : 13, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/1_4.png", "kind" : 3, "name" : "白虎妖帅", "price" : 60, "propertyList" : [ { "id" : 13, "class" : "jiuzhou" }, { "id" : 13, "class" : "tianxiang" }, { "id" : 13, "class" : "tianlong" }, { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "yaochi" }, { "id" : 14, "class" : "taishang" } ], "propertyValueDictId" : "dict-000058", "quality" : 4, "soulId" : "SoulTemplate-0013", "type" : 1 }
,"SoulTemplate-0014":{ "baseExp" : 8, "defaultPropertyId" : 14, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 4, "name" : "青鸾妖帅", "price" : 60, "propertyList" : [ { "id" : 14, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "tianlong" }, { "id" : 14, "class" : "yaochi" }, { "id" : 13, "class" : "leiyin" }, { "id" : 13, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000058", "quality" : 4, "soulId" : "SoulTemplate-0014", "type" : 1 }
,"SoulTemplate-0015":{ "baseExp" : 8, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 6, "name" : "龙犼妖帅", "price" : 60, "propertyList" : [ { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000054", "quality" : 4, "soulId" : "SoulTemplate-0015", "type" : 1 }
,"SoulTemplate-0016":{ "baseExp" : 8, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 10, "name" : "玄武妖帅", "price" : 60, "propertyList" : [ { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" }, { "id" : 6, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000070", "quality" : 4, "soulId" : "SoulTemplate-0016", "type" : 1 }
,"SoulTemplate-0017":{ "baseExp" : 8, "defaultPropertyId" : 15, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/1_4.png", "kind" : 13, "name" : "风兽妖帅", "price" : 60, "propertyList" : [ { "id" : 15, "class" : "tianxiang" }, { "id" : 15, "class" : "taishang" }, { "id" : 15, "class" : "tianlong" }, { "id" : 15, "class" : "jiuzhou" }, { "id" : 15, "class" : "yaochi" }, { "id" : 15, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000058", "quality" : 4, "soulId" : "SoulTemplate-0017", "type" : 1 }
,"SoulTemplate-0018":{ "baseExp" : 8, "defaultPropertyId" : 16, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 14, "name" : "化蛇妖帅", "price" : 60, "propertyList" : [ { "id" : 16, "class" : "tianxiang" }, { "id" : 16, "class" : "taishang" }, { "id" : 16, "class" : "tianlong" }, { "id" : 16, "class" : "jiuzhou" }, { "id" : 16, "class" : "yaochi" }, { "id" : 16, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000058", "quality" : 4, "soulId" : "SoulTemplate-0018", "type" : 1 }
,"SoulTemplate-0019":{ "baseExp" : 8, "defaultPropertyId" : 11, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/1_4.png", "kind" : 15, "name" : "烛龙妖帅", "price" : 60, "propertyList" : [ { "id" : 11, "class" : "tianxiang" }, { "id" : 11, "class" : "tianlong" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 11, "class" : "leiyin" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000052", "quality" : 4, "soulId" : "SoulTemplate-0019", "type" : 1 }
,"SoulTemplate-0020":{ "baseExp" : 8, "defaultPropertyId" : 12, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/2_4.png", "kind" : 16, "name" : "蛊雕妖帅", "price" : 60, "propertyList" : [ { "id" : 12, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "tianlong" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 11, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000052", "quality" : 4, "soulId" : "SoulTemplate-0020", "type" : 1 }
,"SoulTemplate-0021":{ "baseExp" : 8, "defaultPropertyId" : 21, "description" : "", "expReqDictId" : "dict-000042", "icon" : "image/icon/yaohe/1_4.png", "kind" : 17, "name" : "夔牛妖帅", "price" : 60, "propertyList" : [ { "id" : 21, "class" : "tianxiang" }, { "id" : 21, "class" : "taishang" }, { "id" : 21, "class" : "tianlong" }, { "id" : 21, "class" : "jiuzhou" }, { "id" : 21, "class" : "yaochi" }, { "id" : 21, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000052", "quality" : 4, "soulId" : "SoulTemplate-0021", "type" : 1 }
,"SoulTemplate-0022":{ "baseExp" : 20, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 1, "name" : "金乌妖王", "price" : 90, "propertyList" : [ { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000049", "quality" : 5, "soulId" : "SoulTemplate-0022", "type" : 1 }
,"SoulTemplate-0023":{ "baseExp" : 20, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 2, "name" : "应龙妖王", "price" : 90, "propertyList" : [ { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000051", "quality" : 5, "soulId" : "SoulTemplate-0023", "type" : 1 }
,"SoulTemplate-0024":{ "baseExp" : 20, "defaultPropertyId" : 13, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 3, "name" : "白虎妖王", "price" : 90, "propertyList" : [ { "id" : 13, "class" : "tianxiang" }, { "id" : 13, "class" : "tianlong" }, { "id" : 13, "class" : "jiuzhou" }, { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000063", "quality" : 5, "soulId" : "SoulTemplate-0024", "type" : 1 }
,"SoulTemplate-0025":{ "baseExp" : 20, "defaultPropertyId" : 14, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 4, "name" : "青鸾妖王", "price" : 90, "propertyList" : [ { "id" : 14, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "tianlong" }, { "id" : 14, "class" : "yaochi" }, { "id" : 13, "class" : "leiyin" }, { "id" : 13, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000063", "quality" : 5, "soulId" : "SoulTemplate-0025", "type" : 1 }
,"SoulTemplate-0026":{ "baseExp" : 20, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 5, "name" : "白泽妖王", "price" : 90, "propertyList" : [ { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000053", "quality" : 5, "soulId" : "SoulTemplate-0026", "type" : 1 }
,"SoulTemplate-0027":{ "baseExp" : 20, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 6, "name" : "龙犼妖王", "price" : 90, "propertyList" : [ { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000057", "quality" : 5, "soulId" : "SoulTemplate-0027", "type" : 1 }
,"SoulTemplate-0028":{ "baseExp" : 20, "defaultPropertyId" : 20, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 8, "name" : "河罗妖王", "price" : 90, "propertyList" : [ { "id" : 20, "class" : "tianxiang" }, { "id" : 20, "class" : "taishang" }, { "id" : 20, "class" : "tianlong" }, { "id" : 20, "class" : "jiuzhou" }, { "id" : 20, "class" : "yaochi" }, { "id" : 20, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000057", "quality" : 5, "soulId" : "SoulTemplate-0028", "type" : 1 }
,"SoulTemplate-0029":{ "baseExp" : 20, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 9, "name" : "辟邪妖王", "price" : 90, "propertyList" : [ { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" }, { "id" : 6, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000072", "quality" : 5, "soulId" : "SoulTemplate-0029", "type" : 1 }
,"SoulTemplate-0030":{ "baseExp" : 20, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 10, "name" : "玄武妖王", "price" : 90, "propertyList" : [ { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" }, { "id" : 6, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000076", "quality" : 5, "soulId" : "SoulTemplate-0030", "type" : 1 }
,"SoulTemplate-0031":{ "baseExp" : 20, "defaultPropertyId" : 7, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 12, "name" : "苍狼妖王", "price" : 90, "propertyList" : [ { "id" : 7, "class" : "tianxiang" }, { "id" : 7, "class" : "taishang" }, { "id" : 7, "class" : "tianlong" }, { "id" : 7, "class" : "jiuzhou" }, { "id" : 7, "class" : "yaochi" }, { "id" : 7, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000067", "quality" : 5, "soulId" : "SoulTemplate-0031", "type" : 1 }
,"SoulTemplate-0032":{ "baseExp" : 20, "defaultPropertyId" : 15, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 13, "name" : "风兽妖王", "price" : 90, "propertyList" : [ { "id" : 15, "class" : "tianxiang" }, { "id" : 15, "class" : "taishang" }, { "id" : 15, "class" : "tianlong" }, { "id" : 15, "class" : "jiuzhou" }, { "id" : 15, "class" : "yaochi" }, { "id" : 15, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000063", "quality" : 5, "soulId" : "SoulTemplate-0032", "type" : 1 }
,"SoulTemplate-0033":{ "baseExp" : 20, "defaultPropertyId" : 16, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 14, "name" : "化蛇妖王", "price" : 90, "propertyList" : [ { "id" : 16, "class" : "tianxiang" }, { "id" : 16, "class" : "taishang" }, { "id" : 16, "class" : "tianlong" }, { "id" : 16, "class" : "yaochi" }, { "id" : 16, "class" : "jiuzhou" }, { "id" : 16, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000063", "quality" : 5, "soulId" : "SoulTemplate-0033", "type" : 1 }
,"SoulTemplate-0034":{ "baseExp" : 20, "defaultPropertyId" : 11, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 15, "name" : "烛龙妖王", "price" : 90, "propertyList" : [ { "id" : 11, "class" : "tianxiang" }, { "id" : 11, "class" : "tianlong" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 11, "class" : "leiyin" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000055", "quality" : 5, "soulId" : "SoulTemplate-0034", "type" : 1 }
,"SoulTemplate-0035":{ "baseExp" : 20, "defaultPropertyId" : 12, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/2_5.png", "kind" : 16, "name" : "蛊雕妖王", "price" : 90, "propertyList" : [ { "id" : 12, "class" : "yaochi" }, { "id" : 12, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "tianlong" }, { "id" : 11, "class" : "leiyin" }, { "id" : 11, "class" : "jiuzhou" } ], "propertyValueDictId" : "dict-000055", "quality" : 5, "soulId" : "SoulTemplate-0035", "type" : 1 }
,"SoulTemplate-0036":{ "baseExp" : 240, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 1, "name" : "金乌妖皇", "price" : 900, "propertyList" : [ { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000053", "quality" : 6, "soulId" : "SoulTemplate-0036", "type" : 1 }
,"SoulTemplate-0037":{ "baseExp" : 240, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 2, "name" : "应龙妖皇", "price" : 900, "propertyList" : [ { "id" : 10, "class" : "leiyin" }, { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000057", "quality" : 6, "soulId" : "SoulTemplate-0037", "type" : 1 }
,"SoulTemplate-0038":{ "baseExp" : 240, "defaultPropertyId" : 13, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 3, "name" : "白虎妖皇", "price" : 900, "propertyList" : [ { "id" : 13, "class" : "tianxiang" }, { "id" : 13, "class" : "tianlong" }, { "id" : 13, "class" : "jiuzhou" }, { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "yaochi" }, { "id" : 14, "class" : "taishang" } ], "propertyValueDictId" : "dict-000066", "quality" : 6, "soulId" : "SoulTemplate-0038", "type" : 1 }
,"SoulTemplate-0039":{ "baseExp" : 240, "defaultPropertyId" : 14, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 4, "name" : "青鸾妖皇", "price" : 900, "propertyList" : [ { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "tianlong" }, { "id" : 13, "class" : "jiuzhou" }, { "id" : 14, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000066", "quality" : 6, "soulId" : "SoulTemplate-0039", "type" : 1 }
,"SoulTemplate-0040":{ "baseExp" : 240, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 5, "name" : "白泽妖皇", "price" : 900, "propertyList" : [ { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000059", "quality" : 6, "soulId" : "SoulTemplate-0040", "type" : 1 }
,"SoulTemplate-0041":{ "baseExp" : 240, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 6, "name" : "龙犼妖皇", "price" : 900, "propertyList" : [ { "id" : 19, "class" : "leiyin" }, { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000064", "quality" : 6, "soulId" : "SoulTemplate-0041", "type" : 1 }
,"SoulTemplate-0042":{ "baseExp" : 240, "defaultPropertyId" : 20, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 7, "name" : "朱厌妖皇", "price" : 900, "propertyList" : [ { "id" : 20, "class" : "tianxiang" }, { "id" : 20, "class" : "taishang" }, { "id" : 20, "class" : "tianlong" }, { "id" : 20, "class" : "jiuzhou" }, { "id" : 20, "class" : "yaochi" }, { "id" : 20, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000059", "quality" : 6, "soulId" : "SoulTemplate-0042", "type" : 1 }
,"SoulTemplate-0043":{ "baseExp" : 240, "defaultPropertyId" : 20, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 8, "name" : "河罗妖皇", "price" : 900, "propertyList" : [ { "id" : 20, "class" : "leiyin" }, { "id" : 20, "class" : "tianxiang" }, { "id" : 20, "class" : "taishang" }, { "id" : 20, "class" : "tianlong" }, { "id" : 20, "class" : "jiuzhou" }, { "id" : 20, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000064", "quality" : 6, "soulId" : "SoulTemplate-0043", "type" : 1 }
,"SoulTemplate-0044":{ "baseExp" : 240, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 9, "name" : "辟邪妖皇", "price" : 900, "propertyList" : [ { "id" : 6, "class" : "yaochi" }, { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000075", "quality" : 6, "soulId" : "SoulTemplate-0044", "type" : 1 }
,"SoulTemplate-0045":{ "baseExp" : 240, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 10, "name" : "玄武妖皇", "price" : 900, "propertyList" : [ { "id" : 6, "class" : "leiyin" }, { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000078", "quality" : 6, "soulId" : "SoulTemplate-0045", "type" : 1 }
,"SoulTemplate-0046":{ "baseExp" : 240, "defaultPropertyId" : 7, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 11, "name" : "灵狐妖皇", "price" : 900, "propertyList" : [ { "id" : 7, "class" : "yaochi" }, { "id" : 7, "class" : "tianxiang" }, { "id" : 7, "class" : "taishang" }, { "id" : 7, "class" : "tianlong" }, { "id" : 7, "class" : "jiuzhou" }, { "id" : 7, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000068", "quality" : 6, "soulId" : "SoulTemplate-0046", "type" : 1 }
,"SoulTemplate-0047":{ "baseExp" : 240, "defaultPropertyId" : 7, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 12, "name" : "苍狼妖皇", "price" : 900, "propertyList" : [ { "id" : 7, "class" : "leiyin" }, { "id" : 7, "class" : "tianxiang" }, { "id" : 7, "class" : "tianlong" }, { "id" : 7, "class" : "jiuzhou" }, { "id" : 7, "class" : "yaochi" }, { "id" : 7, "class" : "taishang" } ], "propertyValueDictId" : "dict-000073", "quality" : 6, "soulId" : "SoulTemplate-0047", "type" : 1 }
,"SoulTemplate-0048":{ "baseExp" : 240, "defaultPropertyId" : 15, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 13, "name" : "风兽妖皇", "price" : 900, "propertyList" : [ { "id" : 15, "class" : "taishang" }, { "id" : 15, "class" : "tianxiang" }, { "id" : 15, "class" : "jiuzhou" }, { "id" : 15, "class" : "tianlong" }, { "id" : 15, "class" : "yaochi" }, { "id" : 15, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000066", "quality" : 6, "soulId" : "SoulTemplate-0048", "type" : 1 }
,"SoulTemplate-0049":{ "baseExp" : 240, "defaultPropertyId" : 16, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 14, "name" : "化蛇妖皇", "price" : 900, "propertyList" : [ { "id" : 16, "class" : "leiyin" }, { "id" : 16, "class" : "yaochi" }, { "id" : 16, "class" : "jiuzhou" }, { "id" : 16, "class" : "tianlong" }, { "id" : 16, "class" : "taishang" }, { "id" : 16, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000066", "quality" : 6, "soulId" : "SoulTemplate-0049", "type" : 1 }
,"SoulTemplate-0050":{ "baseExp" : 240, "defaultPropertyId" : 11, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 15, "name" : "烛龙妖皇", "price" : 900, "propertyList" : [ { "id" : 11, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 11, "class" : "tianlong" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000060", "quality" : 6, "soulId" : "SoulTemplate-0050", "type" : 1 }
,"SoulTemplate-0051":{ "baseExp" : 240, "defaultPropertyId" : 12, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/2_6.png", "kind" : 16, "name" : "蛊雕妖皇", "price" : 900, "propertyList" : [ { "id" : 11, "class" : "leiyin" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 12, "class" : "tianlong" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000060", "quality" : 6, "soulId" : "SoulTemplate-0051", "type" : 1 }
,"SoulTemplate-0052":{ "baseExp" : 480, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 1, "name" : "金乌妖圣", "price" : 1800, "propertyList" : [ { "id" : 10, "class" : "tianxiang" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000056", "quality" : 7, "soulId" : "SoulTemplate-0052", "type" : 1 }
,"SoulTemplate-0053":{ "baseExp" : 480, "defaultPropertyId" : 10, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 2, "name" : "应龙妖圣", "price" : 1800, "propertyList" : [ { "id" : 10, "class" : "leiyin" }, { "id" : 10, "class" : "yaochi" }, { "id" : 10, "class" : "jiuzhou" }, { "id" : 10, "class" : "tianlong" }, { "id" : 10, "class" : "taishang" }, { "id" : 10, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000061", "quality" : 7, "soulId" : "SoulTemplate-0053", "type" : 1 }
,"SoulTemplate-0054":{ "baseExp" : 480, "defaultPropertyId" : 13, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 3, "name" : "白虎妖圣", "price" : 1800, "propertyList" : [ { "id" : 13, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 13, "class" : "tianlong" }, { "id" : 13, "class" : "jiuzhou" }, { "id" : 14, "class" : "yaochi" }, { "id" : 13, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000069", "quality" : 7, "soulId" : "SoulTemplate-0054", "type" : 1 }
,"SoulTemplate-0055":{ "baseExp" : 480, "defaultPropertyId" : 14, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 4, "name" : "青鸾妖圣", "price" : 1800, "propertyList" : [ { "id" : 13, "class" : "leiyin" }, { "id" : 14, "class" : "tianxiang" }, { "id" : 14, "class" : "taishang" }, { "id" : 14, "class" : "tianlong" }, { "id" : 13, "class" : "jiuzhou" }, { "id" : 14, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000069", "quality" : 7, "soulId" : "SoulTemplate-0055", "type" : 1 }
,"SoulTemplate-0056":{ "baseExp" : 480, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 5, "name" : "白泽妖圣", "price" : 1800, "propertyList" : [ { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000062", "quality" : 7, "soulId" : "SoulTemplate-0056", "type" : 1 }
,"SoulTemplate-0057":{ "baseExp" : 480, "defaultPropertyId" : 19, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 6, "name" : "龙犼妖圣", "price" : 1800, "propertyList" : [ { "id" : 19, "class" : "tianxiang" }, { "id" : 19, "class" : "taishang" }, { "id" : 19, "class" : "tianlong" }, { "id" : 19, "class" : "jiuzhou" }, { "id" : 19, "class" : "yaochi" }, { "id" : 19, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000065", "quality" : 7, "soulId" : "SoulTemplate-0057", "type" : 1 }
,"SoulTemplate-0058":{ "baseExp" : 480, "defaultPropertyId" : 20, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 7, "name" : "朱厌妖圣", "price" : 1800, "propertyList" : [ { "id" : 20, "class" : "leiyin" }, { "id" : 20, "class" : "yaochi" }, { "id" : 20, "class" : "jiuzhou" }, { "id" : 20, "class" : "tianlong" }, { "id" : 20, "class" : "taishang" }, { "id" : 20, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000062", "quality" : 7, "soulId" : "SoulTemplate-0058", "type" : 1 }
,"SoulTemplate-0059":{ "baseExp" : 480, "defaultPropertyId" : 20, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 8, "name" : "河罗妖圣", "price" : 1800, "propertyList" : [ { "id" : 20, "class" : "tianxiang" }, { "id" : 20, "class" : "taishang" }, { "id" : 20, "class" : "tianlong" }, { "id" : 20, "class" : "jiuzhou" }, { "id" : 20, "class" : "yaochi" }, { "id" : 20, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000065", "quality" : 7, "soulId" : "SoulTemplate-0059", "type" : 1 }
,"SoulTemplate-0060":{ "baseExp" : 480, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 9, "name" : "辟邪妖圣", "price" : 1800, "propertyList" : [ { "id" : 6, "class" : "leiyin" }, { "id" : 6, "class" : "tianxiang" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000077", "quality" : 7, "soulId" : "SoulTemplate-0060", "type" : 1 }
,"SoulTemplate-0061":{ "baseExp" : 480, "defaultPropertyId" : 6, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 10, "name" : "玄武妖圣", "price" : 1800, "propertyList" : [ { "id" : 6, "class" : "leiyin" }, { "id" : 6, "class" : "jiuzhou" }, { "id" : 6, "class" : "yaochi" }, { "id" : 6, "class" : "tianlong" }, { "id" : 6, "class" : "taishang" }, { "id" : 6, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000079", "quality" : 7, "soulId" : "SoulTemplate-0061", "type" : 1 }
,"SoulTemplate-0062":{ "baseExp" : 480, "defaultPropertyId" : 7, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 11, "name" : "灵狐妖圣", "price" : 1800, "propertyList" : [ { "id" : 7, "class" : "tianxiang" }, { "id" : 7, "class" : "taishang" }, { "id" : 7, "class" : "tianlong" }, { "id" : 7, "class" : "jiuzhou" }, { "id" : 7, "class" : "yaochi" }, { "id" : 7, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000071", "quality" : 7, "soulId" : "SoulTemplate-0062", "type" : 1 }
,"SoulTemplate-0063":{ "baseExp" : 480, "defaultPropertyId" : 7, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 12, "name" : "苍狼妖圣", "price" : 1800, "propertyList" : [ { "id" : 7, "class" : "leiyin" }, { "id" : 7, "class" : "tianxiang" }, { "id" : 7, "class" : "taishang" }, { "id" : 7, "class" : "tianlong" }, { "id" : 7, "class" : "jiuzhou" }, { "id" : 7, "class" : "yaochi" } ], "propertyValueDictId" : "dict-000074", "quality" : 7, "soulId" : "SoulTemplate-0063", "type" : 1 }
,"SoulTemplate-0064":{ "baseExp" : 480, "defaultPropertyId" : 15, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 13, "name" : "风兽妖圣", "price" : 1800, "propertyList" : [ { "id" : 15, "class" : "tianxiang" }, { "id" : 15, "class" : "taishang" }, { "id" : 15, "class" : "tianlong" }, { "id" : 15, "class" : "jiuzhou" }, { "id" : 15, "class" : "yaochi" }, { "id" : 15, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000069", "quality" : 7, "soulId" : "SoulTemplate-0064", "type" : 1 }
,"SoulTemplate-0065":{ "baseExp" : 480, "defaultPropertyId" : 16, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 14, "name" : "化蛇妖圣", "price" : 1800, "propertyList" : [ { "id" : 16, "class" : "leiyin" }, { "id" : 16, "class" : "jiuzhou" }, { "id" : 16, "class" : "yaochi" }, { "id" : 16, "class" : "tianlong" }, { "id" : 16, "class" : "taishang" }, { "id" : 16, "class" : "tianxiang" } ], "propertyValueDictId" : "dict-000069", "quality" : 7, "soulId" : "SoulTemplate-0065", "type" : 1 }
,"SoulTemplate-0066":{ "baseExp" : 480, "defaultPropertyId" : 11, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 15, "name" : "烛龙妖圣", "price" : 1800, "propertyList" : [ { "id" : 11, "class" : "tianlong" }, { "id" : 11, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000063", "quality" : 7, "soulId" : "SoulTemplate-0066", "type" : 1 }
,"SoulTemplate-0067":{ "baseExp" : 480, "defaultPropertyId" : 12, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/2_7.png", "kind" : 16, "name" : "蛊雕妖圣", "price" : 1800, "propertyList" : [ { "id" : 12, "class" : "tianxiang" }, { "id" : 12, "class" : "taishang" }, { "id" : 12, "class" : "tianlong" }, { "id" : 11, "class" : "jiuzhou" }, { "id" : 12, "class" : "yaochi" }, { "id" : 11, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000063", "quality" : 7, "soulId" : "SoulTemplate-0067", "type" : 1 }
,"SoulTemplate-0068":{ "baseExp" : 20, "defaultPropertyId" : 21, "description" : "", "expReqDictId" : "dict-000043", "icon" : "image/icon/yaohe/1_5.png", "kind" : 17, "name" : "夔牛妖王", "price" : 90, "propertyList" : [ { "id" : 21, "class" : "tianxiang" }, { "id" : 21, "class" : "taishang" }, { "id" : 21, "class" : "tianlong" }, { "id" : 21, "class" : "jiuzhou" }, { "id" : 21, "class" : "yaochi" }, { "id" : 21, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000114", "quality" : 5, "soulId" : "SoulTemplate-0068", "type" : 1 }
,"SoulTemplate-0069":{ "baseExp" : 240, "defaultPropertyId" : 21, "description" : "", "expReqDictId" : "dict-000044", "icon" : "image/icon/yaohe/1_6.png", "kind" : 17, "name" : "夔牛妖皇", "price" : 900, "propertyList" : [ { "id" : 21, "class" : "tianxiang" }, { "id" : 21, "class" : "taishang" }, { "id" : 21, "class" : "tianlong" }, { "id" : 21, "class" : "jiuzhou" }, { "id" : 21, "class" : "yaochi" }, { "id" : 21, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000115", "quality" : 6, "soulId" : "SoulTemplate-0069", "type" : 1 }
,"SoulTemplate-0070":{ "baseExp" : 480, "defaultPropertyId" : 21, "description" : "", "expReqDictId" : "dict-000045", "icon" : "image/icon/yaohe/1_7.png", "kind" : 17, "name" : "夔牛妖圣", "price" : 1800, "propertyList" : [ { "id" : 21, "class" : "tianxiang" }, { "id" : 21, "class" : "taishang" }, { "id" : 21, "class" : "tianlong" }, { "id" : 21, "class" : "jiuzhou" }, { "id" : 21, "class" : "yaochi" }, { "id" : 21, "class" : "leiyin" } ], "propertyValueDictId" : "dict-000116", "quality" : 7, "soulId" : "SoulTemplate-0070", "type" : 1 }
};

		}
	}
}