package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class vehicle_recipes extends MovieClip
	{
		public var configData:Object = null;

		public function vehicle_recipes()
		{
			Security.allowDomain('*');

			configData = 

{"vehicleRecipeTemplate-10":{ "consumeAmount" : 0, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-10", "stuff" : [ { "itemId" : "itemTemplate-8845", "amount" : 1 }, { "itemId" : "itemTemplate-8844", "amount" : 200 } ], "vehicle" : [], "vehicleId" : "vehicleTemplate-8" }
,"vehicleRecipeTemplate-11":{ "consumeAmount" : 0, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-11", "stuff" : [ { "itemId" : "itemTemplate-8845", "amount" : 1 }, { "itemId" : "itemTemplate-8844", "amount" : 200 } ], "vehicle" : [], "vehicleId" : "vehicleTemplate-9" }
,"vehicleRecipeTemplate-12":{ "consumeAmount" : 0, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-12", "stuff" : [ { "itemId" : "itemTemplate-8845", "amount" : 1 }, { "itemId" : "itemTemplate-8844", "amount" : 200 } ], "vehicle" : [], "vehicleId" : "vehicleTemplate-10" }
,"vehicleRecipeTemplate-13":{ "consumeAmount" : 0, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-13", "stuff" : [ { "itemId" : "itemTemplate-8845", "amount" : 1 }, { "itemId" : "itemTemplate-8844", "amount" : 200 } ], "vehicle" : [], "vehicleId" : "vehicleTemplate-11" }
,"vehicleRecipeTemplate-14":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-14", "stuff" : [ { "itemId" : "itemTemplate-8855", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-55", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-47", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-12" }
,"vehicleRecipeTemplate-15":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-15", "stuff" : [ { "itemId" : "itemTemplate-8846", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-7", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-13" }
,"vehicleRecipeTemplate-16":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-16", "stuff" : [ { "itemId" : "itemTemplate-8846", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-8", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-14" }
,"vehicleRecipeTemplate-17":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-17", "stuff" : [ { "itemId" : "itemTemplate-8846", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-9", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-15" }
,"vehicleRecipeTemplate-18":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-18", "stuff" : [ { "itemId" : "itemTemplate-8846", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-10", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-16" }
,"vehicleRecipeTemplate-19":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-19", "stuff" : [ { "itemId" : "itemTemplate-8846", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-11", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-17" }
,"vehicleRecipeTemplate-20":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-20", "stuff" : [ { "itemId" : "itemTemplate-8855", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-59", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-48", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-18" }
,"vehicleRecipeTemplate-21":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-21", "stuff" : [ { "itemId" : "itemTemplate-8855", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-60", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-49", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-19" }
,"vehicleRecipeTemplate-22":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-22", "stuff" : [ { "itemId" : "itemTemplate-8855", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-61", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-50", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-20" }
,"vehicleRecipeTemplate-23":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-23", "stuff" : [ { "itemId" : "itemTemplate-8855", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-62", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-51", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-21" }
,"vehicleRecipeTemplate-24":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-24", "stuff" : [ { "itemId" : "itemTemplate-8856", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-47", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-32", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-22" }
,"vehicleRecipeTemplate-25":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-25", "stuff" : [ { "itemId" : "itemTemplate-8847", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-7", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-23" }
,"vehicleRecipeTemplate-26":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-26", "stuff" : [ { "itemId" : "itemTemplate-8856", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-48", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-36", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-24" }
,"vehicleRecipeTemplate-27":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-27", "stuff" : [ { "itemId" : "itemTemplate-8856", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-49", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-38", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-25" }
,"vehicleRecipeTemplate-28":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-28", "stuff" : [ { "itemId" : "itemTemplate-8856", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-50", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-40", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-26" }
,"vehicleRecipeTemplate-29":{ "consumeAmount" : 500, "money" : [], "moneyAmount" : 200000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-29", "stuff" : [ { "itemId" : "itemTemplate-8856", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-51", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-41", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-27" }
,"vehicleRecipeTemplate-30":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-30", "stuff" : [ { "itemId" : "itemTemplate-8847", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-8", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-28" }
,"vehicleRecipeTemplate-31":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-31", "stuff" : [ { "itemId" : "itemTemplate-8847", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-9", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-29" }
,"vehicleRecipeTemplate-32":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-32", "stuff" : [ { "itemId" : "itemTemplate-8847", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-10", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-30" }
,"vehicleRecipeTemplate-33":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-33", "stuff" : [ { "itemId" : "itemTemplate-8847", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-11", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-31" }
,"vehicleRecipeTemplate-34":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-34", "stuff" : [ { "itemId" : "itemTemplate-8840", "amount" : 1000 }, { "itemId" : "itemTemplate-8852", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-63", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-32" }
,"vehicleRecipeTemplate-35":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-35", "stuff" : [ { "itemId" : "itemTemplate-8848", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-7", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-33" }
,"vehicleRecipeTemplate-36":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-36", "stuff" : [ { "itemId" : "itemTemplate-8848", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-8", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-34" }
,"vehicleRecipeTemplate-37":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-37", "stuff" : [ { "itemId" : "itemTemplate-8848", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-9", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-35" }
,"vehicleRecipeTemplate-38":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-38", "stuff" : [ { "itemId" : "itemTemplate-8840", "amount" : 1000 }, { "itemId" : "itemTemplate-8852", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-65", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-36" }
,"vehicleRecipeTemplate-39":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-39", "stuff" : [ { "itemId" : "itemTemplate-8848", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-10", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-37" }
,"vehicleRecipeTemplate-40":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-40", "stuff" : [ { "itemId" : "itemTemplate-8840", "amount" : 1000 }, { "itemId" : "itemTemplate-8852", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-66", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-38" }
,"vehicleRecipeTemplate-41":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-41", "stuff" : [ { "itemId" : "itemTemplate-8848", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-11", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-39" }
,"vehicleRecipeTemplate-42":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-42", "stuff" : [ { "itemId" : "itemTemplate-8840", "amount" : 1000 }, { "itemId" : "itemTemplate-8852", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-67", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-40" }
,"vehicleRecipeTemplate-43":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-43", "stuff" : [ { "itemId" : "itemTemplate-8840", "amount" : 1000 }, { "itemId" : "itemTemplate-8852", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-68", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-41" }
,"vehicleRecipeTemplate-44":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-44", "stuff" : [ { "itemId" : "itemTemplate-8849", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-7", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-42" }
,"vehicleRecipeTemplate-45":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-45", "stuff" : [ { "itemId" : "itemTemplate-8849", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-8", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-43" }
,"vehicleRecipeTemplate-46":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-46", "stuff" : [ { "itemId" : "itemTemplate-8849", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-9", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-44" }
,"vehicleRecipeTemplate-47":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-47", "stuff" : [ { "itemId" : "itemTemplate-8849", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-10", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-45" }
,"vehicleRecipeTemplate-48":{ "consumeAmount" : 10, "money" : [], "moneyAmount" : 20000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-48", "stuff" : [ { "itemId" : "itemTemplate-8849", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-11", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-46" }
,"vehicleRecipeTemplate-49":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-49", "stuff" : [ { "itemId" : "itemTemplate-8853", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-53", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-63", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-47" }
,"vehicleRecipeTemplate-50":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-50", "stuff" : [ { "itemId" : "itemTemplate-8853", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-54", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-65", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-48" }
,"vehicleRecipeTemplate-51":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-51", "stuff" : [ { "itemId" : "itemTemplate-8853", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-56", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-66", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-49" }
,"vehicleRecipeTemplate-52":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-52", "stuff" : [ { "itemId" : "itemTemplate-8853", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-57", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-67", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-50" }
,"vehicleRecipeTemplate-53":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-53", "stuff" : [ { "itemId" : "itemTemplate-8853", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-58", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-68", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-51" }
,"vehicleRecipeTemplate-54":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-54", "stuff" : [ { "itemId" : "itemTemplate-8850", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-13", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-23", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-53" }
,"vehicleRecipeTemplate-55":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-55", "stuff" : [ { "itemId" : "itemTemplate-8850", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-14", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-28", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-54" }
,"vehicleRecipeTemplate-56":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-56", "stuff" : [ { "itemId" : "itemTemplate-8841", "amount" : 1000 }, { "itemId" : "itemTemplate-8854", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-53", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-55" }
,"vehicleRecipeTemplate-57":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-57", "stuff" : [ { "itemId" : "itemTemplate-8850", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-15", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-29", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-56" }
,"vehicleRecipeTemplate-58":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-58", "stuff" : [ { "itemId" : "itemTemplate-8850", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-16", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-30", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-57" }
,"vehicleRecipeTemplate-59":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-59", "stuff" : [ { "itemId" : "itemTemplate-8850", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-17", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-31", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-58" }
,"vehicleRecipeTemplate-60":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-60", "stuff" : [ { "itemId" : "itemTemplate-8841", "amount" : 1000 }, { "itemId" : "itemTemplate-8854", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-54", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-59" }
,"vehicleRecipeTemplate-61":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-61", "stuff" : [ { "itemId" : "itemTemplate-8841", "amount" : 1000 }, { "itemId" : "itemTemplate-8854", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-56", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-60" }
,"vehicleRecipeTemplate-62":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-62", "stuff" : [ { "itemId" : "itemTemplate-8841", "amount" : 1000 }, { "itemId" : "itemTemplate-8854", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-57", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-61" }
,"vehicleRecipeTemplate-63":{ "consumeAmount" : 200, "money" : [], "moneyAmount" : 100000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-63", "stuff" : [ { "itemId" : "itemTemplate-8841", "amount" : 1000 }, { "itemId" : "itemTemplate-8854", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-58", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-62" }
,"vehicleRecipeTemplate-64":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-64", "stuff" : [ { "itemId" : "itemTemplate-8851", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-33", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-42", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-63" }
,"vehicleRecipeTemplate-65":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-65", "stuff" : [ { "itemId" : "itemTemplate-8851", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-34", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-43", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-65" }
,"vehicleRecipeTemplate-66":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-66", "stuff" : [ { "itemId" : "itemTemplate-8851", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-35", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-44", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-66" }
,"vehicleRecipeTemplate-67":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-67", "stuff" : [ { "itemId" : "itemTemplate-8851", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-37", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-45", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-67" }
,"vehicleRecipeTemplate-68":{ "consumeAmount" : 50, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-68", "stuff" : [ { "itemId" : "itemTemplate-8851", "amount" : 2000 } ], "vehicle" : [ { "vehicleId" : "vehicleTemplate-39", "amount" : 1 }, { "vehicleId" : "vehicleTemplate-46", "amount" : 1 } ], "vehicleId" : "vehicleTemplate-68" }
,"vehicleRecipeTemplate-7":{ "recipeId" : "vehicleRecipeTemplate-7", "vehicleId" : "vehicleTemplate-1", "consumeAmount" : 0, "moneyAmount" : 0, "money" : [], "pill" : [], "stuff" : [], "vehicle" : [] }
,"vehicleRecipeTemplate-8":{ "recipeId" : "vehicleRecipeTemplate-8", "vehicleId" : "vehicleTemplate-2", "consumeAmount" : 0, "moneyAmount" : 0, "money" : [], "pill" : [], "stuff" : [], "vehicle" : [] }
,"vehicleRecipeTemplate-9":{ "consumeAmount" : 0, "money" : [], "moneyAmount" : 50000, "pill" : [], "recipeId" : "vehicleRecipeTemplate-9", "stuff" : [ { "itemId" : "itemTemplate-8845", "amount" : 1 }, { "itemId" : "itemTemplate-8844", "amount" : 200 } ], "vehicle" : [], "vehicleId" : "vehicleTemplate-7" }
};

		}
	}
}