package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class vehicles extends MovieClip
	{
		public var configData:Object = null;

		public function vehicles()
		{
			Security.allowDomain('*');

			configData = 

{"vehicleTemplate-100":{ "appearance" : "heitiane", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/heitiane.png", "mportrait" : "", "name" : "黑天鹅", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-100", "vitRatio" : 0.33 }
,"vehicleTemplate-101":{ "appearance" : "heifenghuang", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/heifenghuang.png", "mportrait" : "", "name" : "黑凰", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-101", "vitRatio" : 0.33 }
,"vehicleTemplate-102":{ "appearance" : "jileniaob", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/jileniaob.png", "mportrait" : "", "name" : "翠风鸟", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-102", "vitRatio" : 0.33 }
,"vehicleTemplate-103":{ "appearance" : "shanggulongyingd", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/shanggulongyingd.png", "mportrait" : "", "name" : "金色龙鹰", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-103", "vitRatio" : 0.33 }
,"vehicleTemplate-104":{ "appearance" : "shangguxuanshe", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/shangguxuanshe.png", "mportrait" : "", "name" : "上古腾蛇", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.25, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-104", "vitRatio" : 0.33 }
,"vehicleTemplate-105":{ "appearance" : "shanggulongyinga", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/shanggulongyinga.png", "mportrait" : "", "name" : "蓝色龙鹰", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-105", "vitRatio" : 0.33 }
,"vehicleTemplate-106":{ "appearance" : "chiyanfeilong", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/chiyanfeilong.png", "mportrait" : "", "name" : "赤焰飞龙", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.25, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-106", "vitRatio" : 0.33 }
,"vehicleTemplate-108":{ "appearance" : "kunpeng", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/kunpeng.png", "mportrait" : "", "name" : "九天鲲鹏", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.25, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-108", "vitRatio" : 0.33 }
,"vehicleTemplate-109":{ "appearance" : "longzhou", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/longzhou.png", "mportrait" : "", "name" : "龙舟", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-109", "vitRatio" : 0.33 }
,"vehicleTemplate-110":{ "appearance" : "binglong", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/binglong.png", "mportrait" : "", "name" : "冰龙", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-110", "vitRatio" : 0.33 }
,"vehicleTemplate-112":{ "appearance" : "tuzizuoqi", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/ruijinyuetu132.png", "mportrait" : "", "name" : "瑞锦月兔", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-112", "vitRatio" : 0.33 }
,"vehicleTemplate-113":{ "appearance" : "liyufengzheng", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/liyu32.png", "mportrait" : "", "name" : "锦鲤纸鸢", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-113", "vitRatio" : 0.33 }
,"vehicleTemplate-32":{ "appearance" : "xuanwu2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 4, "icon" : "image/icon/shopItem/mountRelated/haigui.png", "mportrait" : "", "name" : "海龟", "portrait" : "", "quality" : 2, "rank" : 1, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-32", "vitRatio" : 0.33 }
,"vehicleTemplate-33":{ "appearance" : "lianhua", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/lianhua.png", "mportrait" : "", "name" : "莲花", "portrait" : "", "quality" : 2, "rank" : 3, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-33", "vitRatio" : 0.33 }
,"vehicleTemplate-42":{ "appearance" : "hudie", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/hudie.png", "mportrait" : "", "name" : "蝴蝶", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-42", "vitRatio" : 0.33 }
,"vehicleTemplate-47":{ "appearance" : "fenghuolun", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 4, "icon" : "image/icon/shopItem/mountRelated/fenghuolun.png", "mportrait" : "", "name" : "风火轮", "portrait" : "", "quality" : 2, "rank" : 3, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-47", "vitRatio" : 0.33 }
,"vehicleTemplate-69":{ "appearance" : "fenghuolun", "attackRatio" : 10, "damageRatio" : 10, "defenseRatio" : 10, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 5, "icon" : "image/icon/shopItem/mountRelated/fenghuolun.png", "mportrait" : "", "name" : "超级风火轮", "portrait" : "", "quality" : 7, "rank" : 6, "speed" : 1, "type" : 5, "vehicleId" : "vehicleTemplate-69", "vitRatio" : 10 }
,"vehicleTemplate-7":{ "appearance" : "feijian", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/feijian.png", "mportrait" : "", "name" : "飞剑", "portrait" : "", "quality" : 2, "rank" : 1, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-7", "vitRatio" : 0.33 }
,"vehicleTemplate-70":{ "appearance" : "baohulu3", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/hulu.png", "mportrait" : "", "name" : "葫芦", "portrait" : "", "quality" : 2, "rank" : 2, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-70", "vitRatio" : 0.33 }
,"vehicleTemplate-71":{ "appearance" : "fenghuang", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/fenghuang.png", "mportrait" : "", "name" : "凤凰", "portrait" : "", "quality" : 5, "rank" : 5, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-71", "vitRatio" : 0.33 }
,"vehicleTemplate-72":{ "appearance" : "baohulu", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/baohulu.png", "mportrait" : "", "name" : "宝葫芦", "portrait" : "", "quality" : 2, "rank" : 3, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-72", "vitRatio" : 0.33 }
,"vehicleTemplate-73":{ "appearance" : "dayan", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/dayan.png", "mportrait" : "", "name" : "大雁", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-73", "vitRatio" : 0.33 }
,"vehicleTemplate-74":{ "appearance" : "yao", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/yao.png", "mportrait" : "", "name" : "鳐鱼", "portrait" : "", "quality" : 2, "rank" : 1, "speed" : 0.2, "vehicleId" : "vehicleTemplate-74", "vitRatio" : 0.33 }
,"vehicleTemplate-75":{ "appearance" : "yun", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/caiyun.png", "mportrait" : "", "name" : "彩云", "portrait" : "", "quality" : 2, "rank" : 2, "speed" : 0.2, "vehicleId" : "vehicleTemplate-75", "vitRatio" : 0.33 }
,"vehicleTemplate-76":{ "appearance" : "diao2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/diao2.png", "mportrait" : "", "name" : "黑雕", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-76", "vitRatio" : 0.33 }
,"vehicleTemplate-77":{ "appearance" : "yun2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/yun2.png", "mportrait" : "", "name" : "金斗云", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-77", "vitRatio" : 0.33 }
,"vehicleTemplate-78":{ "appearance" : "long", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/long.png", "mportrait" : "", "name" : "圣龙", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.25, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-78", "vitRatio" : 0.33 }
,"vehicleTemplate-79":{ "appearance" : "xuanwu", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/shengui.png", "mportrait" : "", "name" : "玄武", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-79", "vitRatio" : 0.33 }
,"vehicleTemplate-80":{ "appearance" : "fangzhou", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 4, "icon" : "image/icon/shopItem/mountRelated/fangzhou.png", "mportrait" : "", "name" : "方舟", "portrait" : "", "quality" : 2, "rank" : 2, "speed" : 0.2, "type" : 1, "vehicleId" : "vehicleTemplate-80", "vitRatio" : 0.33 }
,"vehicleTemplate-81":{ "appearance" : "jinnang2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/jinnang2.png", "mportrait" : "", "name" : "碧纱锦囊", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-81", "vitRatio" : 0.33 }
,"vehicleTemplate-82":{ "appearance" : "jinnang1", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/jinnang.png", "mportrait" : "", "name" : "红缎锦囊", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-82", "vitRatio" : 0.33 }
,"vehicleTemplate-83":{ "appearance" : "fenghuang2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/fenghuang2.png", "mportrait" : "", "name" : "火凤凰", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-83", "vitRatio" : 0.33 }
,"vehicleTemplate-84":{ "appearance" : "jinyuzuoji", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/jinyu.png", "mportrait" : "", "name" : "凤尾龙睛", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-84", "vitRatio" : 0.33 }
,"vehicleTemplate-85":{ "appearance" : "ruyi", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/yuruyi.png", "mportrait" : "", "name" : "玉如意", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-85", "vitRatio" : 0.33 }
,"vehicleTemplate-86":{ "appearance" : "shanzi", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/yushan.png", "mportrait" : "", "name" : "青纶玉扇", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-86", "vitRatio" : 0.33 }
,"vehicleTemplate-87":{ "appearance" : "feijian2", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/shanggufeijian.png", "mportrait" : "", "name" : "上古飞剑", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-87", "vitRatio" : 0.33 }
,"vehicleTemplate-88":{ "appearance" : "shanggulongying", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/shanggulongying32.png", "mportrait" : "", "name" : "上古龙鹰", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-88", "vitRatio" : 0.33 }
,"vehicleTemplate-89":{ "appearance" : "mieguihunchuan", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/meiguihunche32.png", "mportrait" : "", "name" : "玫瑰传情", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-89", "vitRatio" : 0.33 }
,"vehicleTemplate-92":{ "appearance" : "jileniao", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/jileniao.png", "mportrait" : "", "name" : "极乐鸟", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-92", "vitRatio" : 0.33 }
,"vehicleTemplate-93":{ "appearance" : "feijian3", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/xueyingfeijian.png", "mportrait" : "", "name" : "血影飞剑", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-93", "vitRatio" : 0.33 }
,"vehicleTemplate-94":{ "appearance" : "jinnang", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 1, "icon" : "image/icon/shopItem/mountRelated/jinnang.png", "mportrait" : "", "name" : "彩锦锦囊", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-94", "vitRatio" : 0.33 }
,"vehicleTemplate-96":{ "appearance" : "dayao", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/dayao.png", "mportrait" : "", "name" : "尊魟", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-96", "vitRatio" : 0.33 }
,"vehicleTemplate-97":{ "appearance" : "feijian1", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/feijian1.png", "mportrait" : "", "name" : "逍遥飞剑", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-97", "vitRatio" : 0.33 }
,"vehicleTemplate-98":{ "appearance" : "feijian4", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/feijian4.png", "mportrait" : "", "name" : "麒麟飞剑", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-98", "vitRatio" : 0.33 }
,"vehicleTemplate-99":{ "appearance" : "dayanc", "attackRatio" : 0.33, "damageRatio" : 0.33, "defenseRatio" : 0.33, "description" : "", "effectId" : "EffectTemplate-23", "grade" : 2, "icon" : "image/icon/shopItem/mountRelated/dayanc.png", "mportrait" : "", "name" : "惊鸿", "portrait" : "", "quality" : 2, "rank" : 4, "speed" : 0.2, "type" : 1, "useMountAction" : 0, "vehicleId" : "vehicleTemplate-99", "vitRatio" : 0.33 }
};

		}
	}
}