package
{
	import flash.display.MovieClip;
	import flash.system.Security;

	public class wingsBook extends MovieClip
	{
		public var configData:Object = null;

		public function wingsBook()
		{
			Security.allowDomain('*');

			configData = 

{"book-001":{ "activeDescription" : "使用白云天翼可激活此图鉴", "activePic" : "image/ui/wings/tujian1.png", "appearance" : "c1", "appendAttrs" : [], "bookId" : "book-001", "description" : "修仙之人模仿天上白云制成的翅膀，经高人点化，具有灵性。", "itemActive" : 0, "itemImage" : "", "name" : "白云天翼", "notactivePic" : "image/ui/wings/tujiansuo1.png", "percent" : 0, "worth" : 0 }
,"book-002":{ "activeDescription" : "使用首充礼包中的流荧天翼，或将天翼淬炼至2阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian2.png", "appearance" : "c2", "appendAttrs" : [], "bookId" : "book-002", "description" : "精灵一般闪耀的羽翼，夜空中轻柔飞过，如同流动的荧光。", "itemActive" : 0, "itemImage" : "", "name" : "流荧天翼", "notactivePic" : "image/ui/wings/tujiansuo2.png", "percent" : 0, "worth" : 0 }
,"book-003":{ "activeDescription" : "将天翼淬炼至4阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian3.png", "appearance" : "c3", "appendAttrs" : [], "bookId" : "book-003", "description" : "光明的反面，是无边的暗影。羽翼轻扇，优雅而沉静，无声无息出现在你身旁。", "itemActive" : 0, "itemImage" : "", "name" : "影幽天翼", "notactivePic" : "image/ui/wings/tujiansuo3.png", "percent" : 0, "worth" : 0 }
,"book-004":{ "activeDescription" : "将天翼淬炼至6阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian4.png", "appearance" : "c4", "appendAttrs" : [], "bookId" : "book-004", "description" : "采集深秋的柔光编织而成的羽翼，凝结着凡人丰收的喜悦，所过之处散播幸福的气息。", "itemActive" : 0, "itemImage" : "", "name" : "秋光天翼", "notactivePic" : "image/ui/wings/tujiansuo4.png", "percent" : 0, "worth" : 0 }
,"book-005":{ "activeDescription" : "将天翼淬炼至8阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian5.png", "appearance" : "c5", "appendAttrs" : [], "bookId" : "book-005", "description" : "天蚕化蝶之羽，如真似幻。流转之间，孰能分清是庄周梦蝶，异或蝶梦庄周？", "itemActive" : 0, "itemImage" : "", "name" : "蝶梦天翼", "notactivePic" : "image/ui/wings/tujiansuo5.png", "percent" : 0, "worth" : 0 }
,"book-006":{ "activeDescription" : "将天翼淬炼至10阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian6.png", "appearance" : "c6", "appendAttrs" : [], "bookId" : "book-006", "description" : "取百花之灵凝聚成翼，至真至美。羽翼轻扇，花香满溢，留下一路芬芳。", "itemActive" : 0, "itemImage" : "", "name" : "花语天翼", "notactivePic" : "image/ui/wings/tujiansuo6.png", "percent" : 0, "worth" : 0 }
,"book-007":{ "activeDescription" : "将天翼淬炼至11阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian7.png", "appearance" : "c7", "appendAttrs" : [], "bookId" : "book-007", "description" : "羽似清风，白莲为翼。乘风而来，不占半点凡尘。", "itemActive" : 0, "itemImage" : "", "name" : "乘风天翼", "notactivePic" : "image/ui/wings/tujiansuo7.png", "percent" : 0, "worth" : 0 }
,"book-008":{ "activeDescription" : "将天翼淬炼至12阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian8.png", "appearance" : "c8", "appendAttrs" : [], "bookId" : "book-008", "description" : "老子西行，见海市蜃楼仿若咫尺，心有所悟一笔画成。", "itemActive" : 0, "itemImage" : "", "name" : "幻海天翼", "notactivePic" : "image/ui/wings/tujiansuo8.png", "percent" : 0, "worth" : 0 }
,"book-009":{ "activeDescription" : "将天翼淬炼至13阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian9.png", "appearance" : "c9", "appendAttrs" : [], "bookId" : "book-009", "description" : "龙族王者褪下的皮与鳞片制成，其羽薄如蝉翼，其骨灿若流金，开合之间流光不断。", "itemActive" : 0, "itemImage" : "", "name" : "金鳞天翼", "notactivePic" : "image/ui/wings/tujiansuo9.png", "percent" : 0, "worth" : 0 }
,"book-010":{ "activeDescription" : "将天翼淬炼至14阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian10.png", "appearance" : "c10", "appendAttrs" : [], "bookId" : "book-010", "description" : "上古妖皇的羽翼制成，所到之处万妖慑服。", "itemActive" : 0, "itemImage" : "", "name" : "逐妖天翼", "notactivePic" : "image/ui/wings/tujiansuo10.png", "percent" : 0, "worth" : 0 }
,"book-011":{ "activeDescription" : "将天翼淬炼至15阶1级可激活此图鉴", "activePic" : "image/ui/wings/tujian13.png", "appearance" : "c13", "appendAttrs" : [], "bookId" : "book-011", "description" : "羽翼如利剑划破长空，扫清一切虚妄浊气，让士气如日中天。", "itemActive" : 0, "itemImage" : "", "name" : "冲虚天翼", "notactivePic" : "image/ui/wings/tujiansuo13.png", "percent" : 0, "worth" : 0 }
,"book-012":{ "activeDescription" : "使用虹光天翼可激活此图鉴", "activePic" : "image/ui/wings/tujian12.png", "appearance" : "c12", "appendAttrs" : [ { "class" : "all", "attr" : "baseDamage", "value" : 30 }, { "class" : "all", "attr" : "phyDefence", "value" : 500 }, { "class" : "all", "attr" : "spellDefence", "value" : 500 } ], "bookId" : "book-012", "description" : "恶魔退散后出现的瑰丽色彩，拥有这种色彩意味着拥有着让恶魔闻风丧胆的力量。", "itemActive" : 1, "itemImage" : "", "name" : "虹光天翼", "notactivePic" : "image/ui/wings/tujiansuo12.png", "percent" : 0, "worth" : 858 }
,"book-013":{ "activeDescription" : "使用凤翔天翼可激活此图鉴", "activePic" : "image/ui/wings/tujian15.png", "appearance" : "c15", "appendAttrs" : [ { "class" : "all", "attr" : "criticalRating", "value" : 200 }, { "class" : "all", "attr" : "criticalResist", "value" : 200 } ], "bookId" : "book-013", "description" : "集百鸟之王的美貌和权力于一身，转身之间留下最高贵的背影。", "itemActive" : 1, "itemImage" : "", "name" : "凤翔天翼", "notactivePic" : "image/ui/wings/tujiansuo15.png", "percent" : 0, "worth" : 880 }
,"book-014":{ "activeDescription" : "使用龙泪天翼可获得此图鉴", "activePic" : "image/ui/wings/tujian17.png", "appearance" : "c203", "appendAttrs" : [ { "class" : "all", "attr" : "hpMax", "value" : 20000 }, { "class" : "all", "attr" : "baseDamage", "value" : 100 }, { "class" : "all", "attr" : "criticalRating", "value" : 300 }, { "class" : "all", "attr" : "criticalResist", "value" : 300 } ], "bookId" : "book-014", "description" : "传说东海沿岸曾逢多年干旱，龙女不愿见黎民受苦，日日流泪祈求上苍，最终感动天地降下甘霖。凡人感其恩德，用龙女之泪织成美丽的羽翼，献给最无私的人。", "itemActive" : 1, "itemImage" : "image/icon64/item/longleitianyi.png", "name" : "龙泪天翼", "notactivePic" : "image/ui/wings/tujiansuo17.png", "percent" : 0, "worth" : 3980 }
,"book-017":{ "activeDescription" : "参与各种活动有机会获得", "activePic" : "image/ui/wings/tujian19.png", "appearance" : "c17", "appendAttrs" : [ { "class" : "all", "attr" : "hpMax", "value" : 20000 }, { "class" : "all", "attr" : "baseDamage", "value" : 100 }, { "class" : "all", "attr" : "phyDefence", "value" : 1000 }, { "class" : "all", "attr" : "spellDefence", "value" : 1000 } ], "bookId" : "book-017", "description" : "牛郎织女鹊桥相见，祝福相恋之人长相厮守，永不分离。", "itemActive" : 1, "itemImage" : "image/icon64/item/xiangliantianyi.png", "name" : "爱恋天翼", "notactivePic" : "image/ui/wings/tujiansuo19.png", "percent" : 0, "worth" : 3980 }
,"book-018":{ "activeDescription" : "使用冰晶天翼可激活此图鉴", "activePic" : "image/ui/wings/tujian201.png", "appearance" : "c201", "appendAttrs" : [ { "class" : "all", "attr" : "phyDefence", "value" : 1000 }, { "class" : "all", "attr" : "spellDefence", "value" : 1000 } ], "bookId" : "book-018", "description" : "冰雪女神的羽翼，拥有世间最纯净的美丽。", "itemActive" : 1, "itemImage" : "", "name" : "冰晶天翼", "notactivePic" : "image/ui/wings/tujiansuo201.png", "percent" : 0, "worth" : 1320 }
,"book-019":{ "activeDescription" : "参与各种活动，领取黛月天翼", "activePic" : "image/ui/wings/tujian20.png", "appearance" : "c18", "appendAttrs" : [ { "class" : "all", "attr" : "baseDamage", "value" : 120 }, { "class" : "all", "attr" : "hpMax", "value" : 12000 }, { "class" : "leiyin", "attr" : "phyAttackPower", "value" : 3030 }, { "class" : "jiuzhou", "attr" : "phyAttackPower", "value" : 3030 }, { "class" : "tianxiang", "attr" : "phyAttackPower", "value" : 1515 }, { "class" : "tianlong", "attr" : "phyAttackPower", "value" : 1515 }, { "class" : "taishang", "attr" : "spellAttackPower", "value" : 3030 }, { "class" : "yaochi", "attr" : "spellAttackPower", "value" : 3030 }, { "class" : "tianxiang", "attr" : "spellAttackPower", "value" : 1515 }, { "class" : "tianlong", "attr" : "spellAttackPower", "value" : 1515 } ], "bookId" : "book-019", "description" : "在朦胧的月色下，望舒月神用青黛墨玉打造的天翼，清冷而神秘，华美绝伦。", "itemActive" : 1, "itemImage" : "image/icon64/item/zhongqiuchibang64.png", "name" : "黛月天翼", "notactivePic" : "image/ui/wings/tujiansuo20.png", "percent" : 0, "worth" : 3980 }
,"book-020":{ "activeDescription" : "参与开服活动，领取专属天翼", "activePic" : "image/ui/wings/tujian16.png", "appearance" : "c16", "appendAttrs" : [ { "class" : "all", "attr" : "hpMax", "value" : 20000 }, { "class" : "all", "attr" : "baseDamage", "value" : 100 }, { "class" : "all", "attr" : "criticalRating", "value" : 300 }, { "class" : "all", "attr" : "criticalResist", "value" : 300 } ], "bookId" : "book-020", "description" : "仙界璇梦青鸟的羽毛编织而成的天翼，具有神秘而强大的力量。", "itemActive" : 1, "itemImage" : "image/icon64/item/zhongqiuchibang64.png", "name" : "璇羽天翼", "notactivePic" : "image/ui/wings/tujiansuo16.png", "percent" : 0, "worth" : 3980 }
,"book-021":{ "activeDescription" : "参与活动，领取清琉天翼", "activePic" : "image/ui/wings/tujian21.png", "appearance" : "c19", "appendAttrs" : [ { "class" : "all", "attr" : "baseDamage", "value" : 80 } ], "bookId" : "book-021", "description" : "清歌伴浅眸，织梦醉琉璃，仙界清尊神殿的琉璃幻羽打造成的天翼，梦幻而绝艳。", "itemActive" : 1, "itemImage" : "image/icon64/item/qingliutianyi64.png", "name" : "清琉天翼", "notactivePic" : "image/ui/wings/tujiansuo21.png", "percent" : 0, "worth" : 528 }
,"book-022":{ "activeDescription" : "参与活动，领取朱盈天翼", "activePic" : "image/ui/wings/tujian22.png", "appearance" : "c20", "appendAttrs" : [ { "class" : "all", "attr" : "hpMax", "value" : 2000 }, { "class" : "all", "attr" : "phyDefence", "value" : 500 }, { "class" : "all", "attr" : "spellDefence", "value" : 500 } ], "bookId" : "book-022", "description" : "朱羽拂红尘，盈月倾紫陌。上古四兽朱雀之羽制成的天翼，华美而斑斓。", "itemActive" : 1, "itemImage" : "image/icon64/item/zhuyingtianyi64.png", "name" : "朱盈天翼", "notactivePic" : "image/ui/wings/tujiansuo22.png", "percent" : 0, "worth" : 860 }
,"book-023":{ "activeDescription" : "参与家族争霸战，获得专属冠军天翼", "activePic" : "image/ui/wings/tujian22.png", "appearance" : "c14", "appendAttrs" : [ { "class" : "all", "attr" : "hpMax", "value" : 20000 }, { "class" : "all", "attr" : "resistDamage", "value" : 60 }, { "class" : "all", "attr" : "criticalRating", "value" : 200 }, { "class" : "all", "attr" : "criticalResist", "value" : 200 } ], "bookId" : "book-023", "description" : "家族战", "itemActive" : 1, "itemImage" : "image/icon64/item/zhuyingtianyi64.png", "name" : "家族战天翼", "notactivePic" : "image/ui/wings/tujiansuo22.png", "percent" : 0, "worth" : 3276 }
};

		}
	}
}